### ISSUE TITLE
I cannot drag and drop items after `npm start`

### ISSUE THREAD

**Issue by happier2** [Kiho/react-form-builder#1]
Cool fork!!!

After git clone this repository, npm install, npm start and npm run serve:api, I open 'http://localhost:8080/'. I can see the result page, But I cannot drag and drop items from toolbar to canvas. There is no error on DevTool's console.

**Comment by happier2** [comment]
It is not support drag and drop items from toolitems.

**Comment by Kiho** [comment]
@happier2 It supports drag and drop items from toolitems if you have at least 1 item in the canvas.
Because that function is extended from drag & drop position changes.

**Comment by Kiho** [comment]
@happier2 Check this branch https://github.com/Kiho/react-form-builder/tree/initial-drag
It should be good to go
