### ISSUE TITLE
Local development of package

### ISSUE THREAD

**Issue by brobey8** [Kiho/react-form-builder#100]
Just wanted to raise an issue as I'm unsure of the workflow I should be using when altering this package. I have tried to use `npm link` to create a symlink of a local version of this repository in my projects `node_modules`, however I was getting a lot of errors using this approach. Are you able to advise the best way to develop on this package locally? Thank you.

**Comment by Kiho** [comment]
You can point to react-form-builder2 package by relative local path.
In case, if you use example/demo as client app then put ` "react-form-builder2": "file:../../"` in package.json dependencies section.

**Comment by brobey8** [comment]
@Kiho Thank you for your reply. I will give this a try tomorrow and let you know how it works. Right now I have cloned the repo and am building the `/lib` files: `npm run build:lib` and them copying them over to the `/lib` directory in my `node_modules` folder which is kind of clunky but at least it works without errors.

**Comment by brobey8** [comment]
Hi @Kiho this workflow does work for the initial 'installation' of the local package however I can't seem to find a good workflow for updating the code once it has been installed this way. I will close this issue as it seems that there is a bit of hackiness involved no matter which method you choose for local dev.
