### ISSUE TITLE
/api/formdata

### ISSUE THREAD

**Issue by sbyrdsell** [Kiho/react-form-builder#101]
How can I run local https://safe-springs-35306.herokuapp.com/api/formdata?cid=${cid} can you post the source?

**Comment by Kiho** [comment]
I have not touched project for a while, so have to spend time to find out the code.
It's nothing special, it just same as this code https://github.com/Kiho/react-form-builder/blob/master/server/api/routes.js
except store temporary data in separate place in memory based on query string. In local environment you don't need that because of don't need to deal with multiple instance of clients.

**Comment by sbyrdsell** [comment]
This is exactly what I’m doing I want to have multiple instances of the form.

Do you think it’s possible to share the code from the other server?

V/R,
 
Stan Byrdsell

**Comment by Kiho** [comment]
var express = require('express');
var formData = require('./formData');

var app = express();

require('../data/routes')(app);

app.route('/formdata/')
  .get((req, res) => {
    const cid = req.query.cid;
    console.log('get formdata - cid: ', cid);
    if (!formData.data[cid]) {
      formData.data[cid] = Object.assign({}, formData.formData);
    }
    // console.log('get formdata: ', formData.data);
    res.send(formData.data[cid].task_data);
  })
  .post((req, res) => {
    const cid = req.query.cid;
    console.log('post formdata - cid: ', cid);
    formData.data[cid] = req.body;
    // console.log('post formdata: ', formData.data);
    res.status(200).send();
  });

module.exports = app;

**Comment by Kiho** [comment]
Then you need adjust code here to pass cid https://github.com/Kiho/react-form-builder/blob/master/server/api/form.js#L31
```js
      const cid = req.query.cid;
      if (!file) {
        res.redirect(`/api/form?cid=${cid}`);
        return;
      }
```

**Comment by nadiamarie296** [comment]
@Kiho @sbyrdsell 
I want to create multiple instance of the form, and i took the Next-Mongo example to implement that,
I updated the route.js of this project but my app crash
Do you have any suggestion of what i have to update in my route.js to implement that (with a database such as Mongodb i mean) ? 

@sbyrdsell how did you implement to have multiple instances of the form ??


this is my routes.js

Ps : the app crash especially with this line :	
`await formData.save(req.db, data);`
```
var express = require("express");
var formData = require("./formData");

var app = express();

function fixFormData(data) {
	return !data || data === "[]" || data.length === 0 ? [] : data;
}

app
	.route("/formdata/")
	.get((req, res) => {
		const cid = req.query.cid;
		console.log('get formdata - cid: ', cid);
		if (!formData.data[cid]) {
			

		  formData.data[cid] = Object.assign({}, formData.formData);

		 
		}
		// console.log('get formdata: ', formData.data);
		res.send(formData.data[cid].task_data);
	  })
	.post((req, res) => {
		const cid = req.query.cid;
		//console.log('post formdata - cid: ', cid);
		formData.data[cid] = req.body;
		// console.log('post formdata: ', formData.data);
		
		res.status(200).send();

		
		const data = fixFormData(formData.data[cid].task_data);
		await formData.save(req.db, data);
	
	  });
	


module.exports = app;

```
