### ISSUE TITLE
FormGenerator issue

### ISSUE THREAD

**Issue by brobey8** [Kiho/react-form-builder#102]
For some reason when rendering the FormGenerator I am having an error:

```
Uncaught TypeError: Cannot read property 'dropdown_0C509A53-08D6-46C5-9895-C424946A0D69' of undefined
```
I've narrowed it down to an issue with `form.jsx` - specifically this line:

```
  _getDefaultValue(item) {
    return this.answerData[item.field_name];
  }
```

Looks like `this.answerData` for me is `undefined`...

Temporary fix:

```
_getDefaultValue(item) {
    if (this.answerData) {
      return this.answerData[item.field_name];
    }
    return '';
  }
```

**Comment by Kiho** [comment]
routes.js
```js
var express = require('express');
// var handleForm = require('./form');
var formData = require('./formData');

var app = express();

require('../data/routes')(app);

app.route('/formdata/')
  .get((req, res) => {
    const cid = req.query.cid;
    console.log('get formdata - cid: ', cid);
    if (!formData.data[cid]) {
      formData.data[cid] = Object.assign(formData.formData);
    }
    // console.log('get formdata: ', formData.data);
    res.send(formData.data[cid].task_data);
  })
  .post((req, res) => {
    const cid = req.query.cid;
    console.log('post formdata - cid: ', cid);
    formData.data[cid] = req.body;
    // console.log('post formdata: ', formData.data);
    res.status(200).send();
  });

module.exports = app;
```

**Comment by Kiho** [comment]
Then you need adjust code here to pass cid https://github.com/Kiho/react-form-builder/blob/master/server/api/form.js#L31
```js
      const cid = req.query.cid;
      if (!file) {
        res.redirect(`/api/form?cid=${cid}`);
        return;
      }
```

**Comment by Kiho** [comment]
I have not much idea on this without more details.

**Comment by brobey8** [comment]
Hi @Kiho,

What else do you need? By the way I think I have conflated terms here, I meant to say that I am getting this error when I am rendering the **ReactFormGenerator** component, this how I am rendering it:

`            <ReactFormGenerator
                form_action="/path/to/form/submit"
                form_method="POST"
                task_id={form_id} // Used to submit a hidden variable with the id to the form from the database.
                data={data} // Question data
            />
`

Perhaps it is because I am not passing an **answer_data** prop?

**Comment by Kiho** [comment]
Hi @brobey8,
You are right, form generator crashes if answer_data was not supplied.
Thanks for reporting issue, it should work now.

**Comment by brobey8** [comment]
@Kiho No problem I am glad I could help contribute to this very useful package! Thank you. Did you want me to close this issue now?

**Comment by Kiho** [comment]
Yes, please close.
