### ISSUE TITLE
Multi column row for advanced form design

### ISSUE THREAD

**Issue by jjakob666** [Kiho/react-form-builder#103]
It would be a huge advantage of this package if it supported adding a multi column row onto the form. to allow complex form designing.

I was able to add the capability to add a multi column row. But I don't know how to make the div inside the row a drop target for other controls.

I have attached the files that changed to make this work.  Can you look at what it would take to make the div column inside the row a drop target?

It would effectively give us a control like this premium monthly cost one:  https://formbuilder.dev/demo/

![multi column row](https://user-images.githubusercontent.com/54422756/101704960-e4304f80-3a53-11eb-915f-9a9a774c9b02.jpg)

[src.zip](https://github.com/Kiho/react-form-builder/files/5669489/src.zip)

**Comment by Kiho** [comment]
I know it's good to have but it's big work, I will try to find out time but not near future.

**Comment by Kiho** [comment]
@jjakob666 If you can contribute CSS work then this feature could be implemented in short time.

**Comment by jjakob666** [comment]
Sure is be happy to help.

Jason

**Comment by Kiho** [comment]
Hi @jjakob666, you can test out this branch https://github.com/Kiho/react-form-builder/tree/multi-column
Let me know if you find issues. if you can improve styles then it will be great.

**Comment by jjakob666** [comment]
I just did a pull. I'll check the css

Regards,

Jason G Jakob
j.evolutia@gmail.com
Cel: 1- 519-841-8617

**Comment by jjakob666** [comment]
I didn't have rights to push my css changes to the multi column branch,  so
I had to fork.

https://github.com/jjakob666/react-form-builder

Looks good and now very usefull !

[image: image.png]

Regards,

Jason G Jakob
j.evolutia@gmail.com
Cel: 1- 519-841-8617

**Comment by Kiho** [comment]
@jjakob666 Thanks for contribution, It's merged & published. 
I just revert min-height back for my requirement.

**Comment by sbyrdsell** [comment]
Is this multi-column available yet? If so can I test it? 
This link doesn't work:
 https://github.com/Kiho/react-form-builder/tree/multi-column

Also, if I want to add additional features in the Edit Window i.e.:
> - Read Only
> - Disabled
> - Hide
> - Tooltip

Default value for Input types:
> - Text
> - Password

What is the best way and where should I start?

Stan Byrdsell
stan.byrdsell@gmail.com
407-485-3403

**Comment by jjakob666** [comment]
Yes it got merged but the toolbox icons are not there to drag onto the page
dropzone.

Jason

**Comment by sbyrdsell** [comment]
OK,
I'll play with it... 

Also, I was able to add additional features in the Edit Window. 
But how to get the ReactFormGenerator to use the value from the feature? i.e. the read-only does not work...

**Comment by sbyrdsell** [comment]
? is there any way to get the data from the form without doing a POST? Or is there a way to do a POST without using the built-in Submit?

**Comment by Kiho** [comment]
@sbyrdsell  You can add different type of TextBox to toolbar, check here https://github.com/Kiho/react-form-builder/pull/63#issuecomment-588606545 ReadOnly, Disabled etc. are not easy to implement, a lot of place to touch.
Find example for posting data by ajax here https://github.com/Kiho/react-form-builder/blob/master/examples/custom/app.js#L55

**Comment by jjakob666** [comment]
I see you merged the css changes I made, but forgot to merge the code so
the two new controls 2 column and 3 column are missing from the toolbox
list.

Can you merge so I can use the new features?

Regards,

Jason G Jakob
j.evolutia@gmail.com
Cel: 1- 519-841-8617

**Comment by Kiho** [comment]
It is all merged, you should see multi-column components if you update rfb to 0.7.1 in package.json

**Comment by jjakob666** [comment]
Ok I guess your online demo needs to be updated.

Jason

**Comment by Kiho** [comment]
On-line demo uses github & heroku, so it's not easy to update.
I need to do some rework and find out better platform, but don't have enough time.

**Comment by AdnanBoota** [comment]
@Kiho Great Functionality, used in one of my new projects, was wondering if it is possible, 

Thanks a lot.

**Comment by Kiho** [comment]
I am not sure what is your issue?

**Comment by AdnanBoota** [comment]
@Kiho actually I want to have 4-columns in the form-builder, can you please update it, thanks in advance, or can you tell me, if i can do it by myself?

Thanks
Adnan

**Comment by Kiho** [comment]
You need to create component after ThreeColumnRow component then export it here https://github.com/Kiho/react-form-builder/blob/master/src/multi-column/MultiColumnRow.jsx#L72
```js
const FourColumnRow = ({ data, class_name, ...rest }) => {
  const className = class_name || 'col-md-3';
  if (!data.childItems) {
    // eslint-disable-next-line no-param-reassign
    data.childItems = [null, null, null, null]; data.isContainer = true;
  }
  return (
    <MultiColumnRow {...rest} className={className} data={data} />
  );
};
```
Search ThreeColumnRow from src folder then made similar changes there.

**Comment by AdnanBoota** [comment]
@Kiho Thanks for the details, so I updated and created the PR, please check if everything is ok and approve.
https://github.com/Kiho/react-form-builder/pull/112
