### ISSUE TITLE
Question: any way to set display horizontally in the code

### ISSUE THREAD

**Issue by RoosterH** [Kiho/react-form-builder#104]
Hi Kiho,

I got a long radio button option that has 30+ choices inside. I would like to save a mouse click so it will be displayed horizontally by default.  Is there any way to set it?  I looked through the codes but didn't get an idea how to set it.

Here is my option definition:
```
{
    key: 'RadioButtons',
    canHaveAnswer: true,
    name: 'Choices',
    icon: 'far fa-dot-circle',
    label: '<strong>Your Choice</strong>',
    field_name: 'YourChoice-',
    required: true,
    canHaveDisplayHorizontal: true,
    options: [
	    {
		    value: '0',
		    text: 'APPLE',
		    key: `choiceOption_0`
	    },
                          ...
                  ]
}
```

Thanks in advance!

**Comment by Kiho** [comment]
@RoosterH You can do it with v 0.6.2, just add inline: true,
```js
      {
        key: 'RadioButtons',
        ........
        field_name: 'radiobuttons_',
        inline: true,
        ........
      },
```

**Comment by RoosterH** [comment]
It works as a charm. Thanks so much!  Happy holidays!
