### ISSUE TITLE
Invalid hook call when compiled

### ISSUE THREAD

**Issue by mkljczk** [Kiho/react-form-builder#105]
That's what I get when yarn link-ed react-form-builder previously built with `yarn build:lib && yarn build`. What could be the problem?
It only happens in one of two apps where I import my fork.

![unknown](https://user-images.githubusercontent.com/21127288/103176958-4f608b00-4876-11eb-9843-65a26d1e1f49.png)

**Comment by Kiho** [comment]
I ma not sure but looks like you got 2 instances of react installed.
lerna usually works fine with mono repo arrangement. or you might need to host npm repo with your copy of rfb somewhere...

**Comment by mkljczk** [comment]
@Kiho `npm ls react` in the app where I import my build only lists one version of React (`react@16.14.0`)

**Comment by Kiho** [comment]
I found issue here https://github.com/react-dnd/react-dnd/issues/1566 with react-dnd 9.x which is case antd branch uses.
If your rfb use it then try upgrade to 10.x or grater.

**Comment by mkljczk** [comment]
Thanks, I’m not using antd branch but I’m using antd in my project, that was the case.
