### ISSUE TITLE
Saving data from multiple forms

### ISSUE THREAD

**Issue by sbyrdsell** [Kiho/react-form-builder#109]
Kiho,
I’m using multiple preview forms in different sections of my web app. How can I keep track of the data entry for each form and post it all at once? Is there an on change option where I can update the JSON used to feed the multiple ReactFormGenerator? Or is there a way to store the entered data in a state variable for all preview forms before calling a post to the server?

**Comment by Kiho** [comment]
There is no built-in mechanism for this, you can assign tusk_id to each form and possibly click all the submit buttons with vanilla js might be a workaround.

**Comment by sbyrdsell** [comment]
Which class is used to create the components i.e: text input, dropdown etc...? If I can dynamically add an onchange handler or a ref binding to each component, I can loop throw the components and get the data before I exit each ReactFormGenerator. What are your thoughts about this approach?

Thanks,
Stan

**Comment by Kiho** [comment]
I think you just need to call handleSubmit of generated form.
```js
  triggerFormSubmit(e) {
    this.childForm.handleSubmit(e);
  }
```
```js
<ReactFormGenerator
    download_path=""
    back_action="/"
    back_name="Back"
    answer_data={answers}
    action_name="Save"
    form_action="/api/form"
    form_method="POST"
    ref={c => this.childForm = c}
    // skip_validations={true}
    onSubmit={this._onSubmit}
    variables={this.props.variables}
    data={this.state.data} />

<button type="button" className="btn btn-default" data-dismiss="modal" 
  onClick={this.triggerFormSubmit.bind(this)}>Trigger Form Submit</button>
```
