### ISSUE TITLE
In Tags answer data is not auto populating in case of edit form

### ISSUE THREAD

**Issue by bhupesh-sf** [Kiho/react-form-builder#11]
I have created a form where I am using **Tags** and when I submit the form I get the data in following format

`0:
key: "tags_option_8F4C8281-CDC6-44E0-8BAF-4C7BCA0019F0"
label: "We"
text: "We"
value: "2"
__proto__: Object
1:
key: "tags_option_BF277F93-D7FA-4502-87BE-42AC6690A630"
label: "Go"
text: "Go"
value: "3"
__proto__: Object
length: 2
__proto__: Array(0)`

But when I open the same form in edit mode i.e. with **answer_data** populated then it expect comma separated string as in following code:

`class Tags extends React.Component {
  constructor(props) {
    super(props);
    this.inputField = React.createRef();
  }

  state = { value: this.props.defaultValue !== undefined ? this.props.defaultValue.split(',') : [] };
`

I made my array to be like this but problem is it throws react warning that there should be unique **key**  present for each value of select.

Please advice.

**Comment by Kiho** [comment]
I am not sure what is your problem here, maybe you need to check this document https://reactjs.org/docs/lists-and-keys.html

**Comment by bhupesh-sf** [comment]
Problem is Tags component.
If you got his file https://github.com/Kiho/react-form-builder/blob/master/src/form-elements.jsx

And go to line 512 there it is expecting the value as comma separated string and using split function to make it as array. But when I try to save the generated form with values it gives me data as array of objects for **Tags** component. If I pass back the same value of array of objects, which was given me while saving the form,  in **answer_data** while editing the previously saved form then it throws an exception for split function. Then I converted the given array of objects to plain object and then passed it as comma separated string then it didn't throw the exception but it gave the above warning in the console because it couldn't find the unique for each element as well it didn't showed the value as pre-selected.

Hope I am able to explain this time. This whole scenarios is about I generated a custom form where I used tag component. Then I saved that form by selecting the values in that form and now I am opening the same form in edit mode. So in that case Tags component is working as desired as its not showing the values as selected and throwing warnings or exceptions.

**Comment by Kiho** [comment]
I updated Tags component to receive value props to either comma separated string "1, 3" or object array [options[0], options[1]] https://github.com/Kiho/react-form-builder/blob/master/src/form-elements.jsx#L515

**Comment by bhupesh-sf** [comment]
Is it published on NPM?

**Comment by Kiho** [comment]
https://www.npmjs.com/package/react-form-builder2

**Comment by bhupesh-sf** [comment]
Its working now. Thanks !!
