### ISSUE TITLE
onPost for Generator

### ISSUE THREAD

**Issue by taylorpalm** [Kiho/react-form-builder#113]
I'm using the generated form as part of a larger form, I want to capture user answers without them having to hit submit similar to the onPost method in the builder. Is there a way to accomplish this?

**Comment by Kiho** [comment]
onPost is used in form builder, you should use onSubmit in form generator.
Check this out https://github.com/Kiho/react-form-builder/issues/109#issuecomment-767338828 something similar setup should work in your case.

**Comment by taylorpalm** [comment]
Thanks that pointed me in the right direction!
