### ISSUE TITLE
Showing html code in TextInput Field

### ISSUE THREAD

**Issue by pratapshiv1992** [Kiho/react-form-builder#114]
![Screenshot (12)](https://user-images.githubusercontent.com/35814161/106890654-a6783c00-670f-11eb-8540-0d28cce7b002.png)
![Screenshot (13)](https://user-images.githubusercontent.com/35814161/106890657-a7a96900-670f-11eb-9b28-260cdf29f526.png)
![Screenshot (14)](https://user-images.githubusercontent.com/35814161/106890658-a841ff80-670f-11eb-8f10-c38e38960bdd.png)
![Screenshot (15)](https://user-images.githubusercontent.com/35814161/106890660-a841ff80-670f-11eb-8cb4-b445134b7a9a.png)

**Comment by Kiho** [comment]
That looks like upstream issue (draftjs-to-html), if the feature is really required then we need to add additional field to enter hyper link after DisplayLabel  I think .

**Comment by pratapshiv1992** [comment]
@Kiho issue reproduced on your demo env.

![image](https://user-images.githubusercontent.com/35814161/107003328-99f8ef80-67b2-11eb-8da7-b87c62c2b9c2.png)


It should not show the html code.

**Comment by Kiho** [comment]
That's limitation from [draftjs-to-html](https://github.com/jpuri/draftjs-to-html) the library, sorry but I can't provide solution for that.

**Comment by Kiho** [comment]
I fixed problem with link, still I see some issue with editor, but I don't think I can fix it.
