### ISSUE TITLE
Get answers from multiple form

### ISSUE THREAD

**Issue by nadiamarie296** [Kiho/react-form-builder#116]
Hello,
I'm using the example "Next-Mongo" provided with this project, and it is great.
However, I would like to render the answers from the "answers" collection (in other words the response that the user has entered in the form).
I found in "http://localhost:3000/api/form" that the answers are rendered but only for the last response (so the last user), and I would like to GET all the answers (in other words all datas in "answers" collection for a specific form)

Any help would be great.

Thanks

**Comment by Kiho** [comment]
You could implement something like this pointing to "answers" collection. https://github.com/pratapshiv1992/react-hooks-express-mongodb-crud

**Comment by nadiamarie296** [comment]
@Kiho Thank you so much
