### ISSUE TITLE
@Kiho @sbyrdsell

### ISSUE THREAD

**Issue by ghilasbelkaci** [Kiho/react-form-builder#117]
@Kiho @sbyrdsell 
I want to create multiple instance of the form, and i took the Next-Mongo example to implement that,
I updated the route.js of this project (as you explain in this issue : https://github.com/Kiho/react-form-builder/issues/101) but my app crash
Do you have any suggestion of what i have to update in my route.js to implement that (with a database such as Mongodb i mean) ? 

@sbyrdsell how did you implement to have multiple instances of the form ??

this is my routes.js

Ps : the app crash especially with this line :	
`await formData.save(req.db, data);`
```
var express = require("express");
var formData = require("./formData");

var app = express();

function fixFormData(data) {
	return !data || data === "[]" || data.length === 0 ? [] : data;
}

app
	.route("/formdata/")
	.get((req, res) => {
		const cid = req.query.cid;
		console.log('get formdata - cid: ', cid);
		if (!formData.data[cid]) {
			

		  formData.data[cid] = Object.assign({}, formData.formData);

		 
		}
		// console.log('get formdata: ', formData.data);
		res.send(formData.data[cid].task_data);
	  })
	.post((req, res) => {
		const cid = req.query.cid;
		//console.log('post formdata - cid: ', cid);
		formData.data[cid] = req.body;
		// console.log('post formdata: ', formData.data);
		
		res.status(200).send();

		
		const data = fixFormData(formData.data[cid].task_data);
		await formData.save(req.db, data);
	
	  });
	


module.exports = app;

```

_Originally posted by @nadiamarie296 in https://github.com/Kiho/react-form-builder/issues/101#issuecomment-775989422_

**Comment by Kiho** [comment]
It's hard to know the reason of crash without source code & stack trace.
Just couple of things I can think of... You should make sure passing cid with url like this https://github.com/Kiho/react-form-builder/blob/master/docs/form-builder.js#L20
Uncomment console.log('post formdata: ', formData.data); can give you better idea, so you should try.
