### ISSUE TITLE
whenever ı post , Adds 2 objects

### ISSUE THREAD

**Issue by fdurna** [Kiho/react-form-builder#119]
Hello Guys whenever ı post , Adds 2 objects one under the other, I want one to be , how can ı do this ?
code -> https://prnt.sc/zhjxwy
but mine like this - > https://prnt.sc/zhk3wo
ı want do this -> https://prnt.sc/zhk1iy

**Comment by Kiho** [comment]
I don't understand what is your exact problem but you can transform data as you want if you follow this example.
https://github.com/Kiho/react-form-builder/blob/master/examples/custom/app.js#L37
