### ISSUE TITLE
CheckBox onClick Event

### ISSUE THREAD

**Issue by fdurna** [Kiho/react-form-builder#120]
Whenever I click here I want it to trigger an onClick event , how can ı do this ?
https://prnt.sc/zm3sy2

**Comment by Kiho** [comment]
There is no built-in mechanism for that.
Maybe you can try event delegation https://maddevs.io/blog/a-bit-about-event-delegation-in-react/

**Comment by fdurna** [comment]
> There is no built-in mechanism for that.
> Maybe you can try event delegation https://maddevs.io/blog/a-bit-about-event-delegation-in-react/

ok thanks

**Comment by fdurna** [comment]
I want to give an event to the section here? , Is not it possible ?
https://prnt.sc/zn0yl6
@Kiho
