### ISSUE TITLE
ReactFormBuilder: Error when using data props Vs: 0.7.3 - Works in Vs: 0.6.1

### ISSUE THREAD

**Issue by sbyrdsell** [Kiho/react-form-builder#122]
The below code worked in version 0.6.1 but after upgrading to version 0.7.3 now receiving Error: **Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.**

**Code:** 
```
<ReactFormBuilder
                    key={step.stepId}
                    onPost={onPost(step)}
                    data={_.get(step, "data.task_data", [])}
/>
```

**Step 1:**
Add Text Input to canvas, it  triggers a Post.
onPost:
{task_data: Array(1)}
task_data: Array(1)
0: {id: "E6681914-0232-4406-873E-F3D67262C32C", element: "TextInput", text: "Text Input", static: undefined, required: false, …}
length: 1
__proto__: Array(0)
__proto__: Object 

**Step 2:** In the form-elements-edit.jsx window check Required Checkbox to reproduce the error
Error in :
index.js:1 The above error occurred in the <Preview> component:
    in Preview (created by ReactFormBuilder)
    in div (created by ReactFormBuilder)
    in div (created by ReactFormBuilder)
    in div (created by ReactFormBuilder)
    in Unknown (created by ReactFormBuilder)
    in ReactFormBuilder (at formBuilder.js:129)
    in div (created by StepZilla)
    in StepZilla (at formBuilder.js:107)
    in div (at formBuilder.js:106)
    in div (at formBuilder.js:103)
    in FormBuilder (at App.js:10)
    in Unknown (at App.js:9)
    in App (at src/index.js:12)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
console.<computed> @ index.js:1
overrideMethod @ react_devtools_backend.js:2430
logCapturedError @ react-dom.development.js:19527
logError @ react-dom.development.js:19564
update.callback @ react-dom.development.js:20708
callCallback @ react-dom.development.js:12490
commitUpdateQueue @ react-dom.development.js:12511
commitLifeCycles @ react-dom.development.js:19883
commitLayoutEffects @ react-dom.development.js:22803
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
commitRootImpl @ react-dom.development.js:22541
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
flushPendingDiscreteUpdates @ react-dom.development.js:21847
flushDiscreteUpdates @ react-dom.development.js:21827
finishEventHandler @ react-dom.development.js:764
batchedEventUpdates @ react-dom.development.js:798
dispatchEventForLegacyPluginEventSystem @ react-dom.development.js:3568
attemptToDispatchEvent @ react-dom.development.js:4267
dispatchEvent @ react-dom.development.js:4189
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
discreteUpdates$1 @ react-dom.development.js:21887
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
Show 5 more frames
react-dom.development.js:23093 Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at checkForNestedUpdates (react-dom.development.js:23093)
    at scheduleUpdateOnFiber (react-dom.development.js:21164)
    at Object.enqueueSetState (react-dom.development.js:12639)
    at Preview.push../node_modules/react/cjs/react.development.js.Component.setState (react.development.js:471)
    at Preview._onChange (preview.js:174)
    at preview.js:105
    at beedle.js:1
    at Array.forEach (<anonymous>)
    at Store.processCallbacks (beedle.js:1)
    at Object.set (beedle.js:1)
    at Object.setData (store.js:89)
    at Store.commit (beedle.js:1)
    at Object.setData (store.js:23)
    at Object.updateOrder (store.js:72)
    at Store.dispatch (beedle.js:1)
    at getDerivedStateFromProps (preview.js:430)
    at applyDerivedStateFromProps (react-dom.development.js:12603)
    at updateClassInstance (react-dom.development.js:13207)
    at updateClassComponent (react-dom.development.js:17107)
    at beginWork (react-dom.development.js:18620)
    at beginWork$1 (react-dom.development.js:23179)
    at performUnitOfWork (react-dom.development.js:22154)
    at workLoopSync (react-dom.development.js:22130)
    at performSyncWorkOnRoot (react-dom.development.js:21756)
    at react-dom.development.js:11089
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084)
    at flushSyncCallbackQueue (react-dom.development.js:11072)
    at flushPendingDiscreteUpdates (react-dom.development.js:21847)
    at flushDiscreteUpdates (react-dom.development.js:21827)
    at finishEventHandler (react-dom.development.js:764)
    at batchedEventUpdates (react-dom.development.js:798)
    at dispatchEventForLegacyPluginEventSystem (react-dom.development.js:3568)
    at attemptToDispatchEvent (react-dom.development.js:4267)
    at dispatchEvent (react-dom.development.js:4189)
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at discreteUpdates$1 (react-dom.development.js:21887)
    at discreteUpdates (react-dom.development.js:806)
    at dispatchDiscreteEvent (react-dom.development.js:4168)
checkForNestedUpdates @ react-dom.development.js:23093
scheduleUpdateOnFiber @ react-dom.development.js:21164
enqueueSetState @ react-dom.development.js:12639
push../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:471
_onChange @ preview.js:174
(anonymous) @ preview.js:105
(anonymous) @ beedle.js:1
processCallbacks @ beedle.js:1
set @ beedle.js:1
setData @ store.js:89
commit @ beedle.js:1
setData @ store.js:23
updateOrder @ store.js:72
dispatch @ beedle.js:1
getDerivedStateFromProps @ preview.js:430
applyDerivedStateFromProps @ react-dom.development.js:12603
updateClassInstance @ react-dom.development.js:13207
updateClassComponent @ react-dom.development.js:17107
beginWork @ react-dom.development.js:18620
beginWork$1 @ react-dom.development.js:23179
performUnitOfWork @ react-dom.development.js:22154
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
flushPendingDiscreteUpdates @ react-dom.development.js:21847
flushDiscreteUpdates @ react-dom.development.js:21827
finishEventHandler @ react-dom.development.js:764
batchedEventUpdates @ react-dom.development.js:798
dispatchEventForLegacyPluginEventSystem @ react-dom.development.js:3568
attemptToDispatchEvent @ react-dom.development.js:4267
dispatchEvent @ react-dom.development.js:4189
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
discreteUpdates$1 @ react-dom.development.js:21887
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
Show 10 more frames

**Comment by sbyrdsell** [comment]
![form-elements-edit](https://user-images.githubusercontent.com/228974/108924809-6539c480-7609-11eb-8e7d-770a22b17e75.jpg)

**Comment by sbyrdsell** [comment]
![Screen Shot 2021-02-23 at 7 03 07 PM](https://user-images.githubusercontent.com/228974/108925024-dda08580-7609-11eb-81f9-8453d633f164.png)

**Comment by Kiho** [comment]
It might be caused by react-draft-wysiwyg, can you try 0.7.4?

**Comment by sbyrdsell** [comment]
I upgraded to: "react-form-builder2": "^0.7.4" no luck. Then I delete node_modules and reinstalled still no luck still getting the same error: Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
 
**DATA:**
[task_data:[
  {
    "id": "A623E478-43D4-43F4-A170-4E5B9103E286",
    "element": "TextInput",
    "text": "Text Input",
    "required": true,
    "canHaveAnswer": true,
    "canHavePageBreakBefore": true,
    "canHaveAlternateForm": true,
    "canHaveDisplayHorizontal": true,
    "canHaveOptionCorrect": true,
    "canHaveOptionValue": true,
    "canPopulateFromApi": true,
    "field_name": "text_input_F41BFF45-EF7A-4850-B0E1-A8601294348E",
    "label": "Placeholder Label",
    "dirty": true
  }
]](url)

**Comment by Kiho** [comment]
Infinity loops usually caused by hooks but rfb2 does not use hooks. I see you assigned key `key={step.stepId}`
and use it as parameter `onPost={onPost(step)}`, why you need key? If it is removed, still problem?

**Comment by sbyrdsell** [comment]
I narrowed the problem down to data. Whenever the store is updating the data somehow or another the state goes into an infinite loop. So if you click on any input build it forces an update on blur or on click which starts the infinite loop.

So when I common data it works fine but does not refresh because there's no data.

<ReactFormBuilder
                  key={step.stepId} //is a Unique GUID 
                  onPost={onPost(step)} //step is the data
                  //data={_.get(step, "data.task_data", [])}
/>

**Comment by Kiho** [comment]
Please try 0.7.5, I hope it fixes your problem.

**Comment by sbyrdsell** [comment]
First and foremost thank you very much for your support.
After testing the error has disappeared but, After adding a component on to the canvas and updating any item in the edit. You are no longer able to add any other items from the toolbox or delete or move the item. 

Test results from "react-form-builder2": "^0.7.5"

Best regards,
Stan

**Comment by Kiho** [comment]
You can try 0.7.6, if this does not work, I am run out of idea.

**Comment by sbyrdsell** [comment]
Do you have time for a quick telephone call or zoom?
So I can get a better idea of the architecture for the data? Or do you create a Design document?

**Comment by sbyrdsell** [comment]
I have not done a full regression test but the preliminary test looks good.....
Thank you very much for all your help I'll let you know once I can test the full thing.

How can I view your necessary updates?

**Comment by sbyrdsell** [comment]
No need to answer the last question found in the comments thank you for being thorough
