### ISSUE TITLE
Compatibility with React 17

### ISSUE THREAD

**Issue by aymkin** [Kiho/react-form-builder#123]
During installation got an error 

```
❯ npm i react-form-builder2
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!   peer react@">=16.8.6" from react-form-builder2@0.7.6
npm ERR!   node_modules/react-form-builder2
npm ERR!     react-form-builder2@"*" from the root project
npm ERR!   1 more (draft-js)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.2" from react-bootstrap-slider@2.2.3
npm ERR! node_modules/react-form-builder2/node_modules/react-bootstrap-slider
npm ERR!   react-bootstrap-slider@"^2.2.3" from react-form-builder2@0.7.6
npm ERR!   node_modules/react-form-builder2
npm ERR!     react-form-builder2@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/admin/.npm/eresolve-report.txt for a full report.
```

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2021-03-02T06_52_00_488Z-debug.log

After retriyng `npm i react-form-builder2 --legacy-peer-deps `

![image](https://user-images.githubusercontent.com/10321850/109611497-fbed1080-7b36-11eb-9a1b-9b0b507d0088.png)

The import can not be resolved
![image](https://user-images.githubusercontent.com/10321850/109611586-1fb05680-7b37-11eb-991a-169a34a3bab7.png)

But after restarting the project

![image](https://user-images.githubusercontent.com/10321850/109612369-4b800c00-7b38-11eb-89ac-aae80fcef930.png)

Running the `npm i bootstrap-slider` doesn't help as well

With command `npm i react-form-builder2 --force ` no luck and the same errors

**Comment by Kiho** [comment]
You need to follow instruction here https://github.com/seiyria/bootstrap-slider#how-do-i-exclude-the-optional-jquery-dependency-from-my-build

**Comment by aymkin** [comment]
Example of file `jquery-stub.js`

https://github.com/Kiho/react-form-builder/blob/master/examples/custom/jquery-stub.js

**Comment by Kiho** [comment]
This example https://github.com/Kiho/react-form-builder/tree/master/examples/cra works fine without modification.
I used yarn to build and debug instead of npm.
