### ISSUE TITLE
onSave prop for <ReactFormBuilder />

### ISSUE THREAD

**Issue by curatorsantos123** [Kiho/react-form-builder#125]
Hello and what a great project! just started playing with it and I think it would be better if it has a some sort of a prop to access the generated JSON of the form builder and pass it to a custom function upon saving the user created form. Just my opinion :D

**Comment by Kiho** [comment]
Are you looking for this https://github.com/Kiho/react-form-builder/blob/master/examples/custom/app.js#L37 or something else?

**Comment by juansa91** [comment]
Hi Kiho. Thank you very much for continuing this awesome project.
I don't think curatorsantos123 was refering to that. In my case it would be cool to pass the json generated by the form to a state (react useState), but correct me if im wrong, there isn't a param for the form builder to do this.

**Comment by Kiho** [comment]
You can get form state from form-generator like this https://github.com/Kiho/react-form-builder/blob/master/examples/custom/demobar.js#L54 
In this case you should post JSON data to back-end by yourself.
Some people like to do that anyway.

**Comment by juansa91** [comment]
I want to do it this way because I want to save the body of the form and also a title and a description in MySQL. You said I can do it with the form-generator, but is it possible to also do it with form-builder?
Thank you very much in advance.

**Comment by Kiho** [comment]
You can do with onPost and onLoad event handlers in form-builder https://github.com/Kiho/react-form-builder/blob/master/examples/custom/app.js#L85
