### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by rodrigogaraujo** [Kiho/react-form-builder#126]
How I can the placeholder texts? 
Like: 
'Required' to: 'Obrigatório'
'Text input' to: 'Campo de texto'
'Placeholder label' to: 'Placeholder'
'Number input' to: 'Campo de número'

Has a away to got this?

**Comment by Kiho** [comment]
There is no easy & clean way, you may need to search parts in form.jsx & form-elements-edit.jsx.

**Comment by Kiho** [comment]
https://github.com/Kiho/react-form-builder/issues/88
