### ISSUE TITLE
Signature not working on Modal/Accordion

### ISSUE THREAD

**Issue by ProgramacionesWeb** [Kiho/react-form-builder#128]
Hello. If you make a form and insert it into a modal or a colapsable component, the signature is not working. 

Width and height of the canvas sets to 0. You can't do anything from CSS because those properties are set as Inline CSS.

Required seems that is not working on signatures neither. Nothings happens if a required signature is empty when you press save.

**Comment by Kiho** [comment]
I can't reproduce your problem, if you can provide code with problem in github repo then I can take a look.
