### ISSUE TITLE
Dynamic Load of ReactFormGenerator for answer data

### ISSUE THREAD

**Issue by buckled0** [Kiho/react-form-builder#129]
I'm currently loading a list of forms I've stored and want to dynamically load the data into the answer_data field. 

Im loading the answer_data from state and rendering the ReactFormGenerator with that answer data, it loads correctly on the first form but if I go to another form the fields are changing (as I used the ElementStore) but the answer data isn't populating. 

Am I missing something??

**Comment by Kiho** [comment]
I am not sure what is your problem, can you provide sample code?
