### ISSUE TITLE
answer_data not load data in edit form

### ISSUE THREAD

**Issue by angularli** [Kiho/react-form-builder#13]
<ReactFormGenerator
                        back_action="/"
                        back_name="Back"
                        answer_data={{ answer }}
                        action_name="Save"
                        hide_actions={false}
                        data={this.state.data}
                    />

**Comment by Kiho** [comment]
Looks like you need single curly brace.
```
const answer = { 'text_input_7B0FEBEB-1E2C-4CF2-BDF1-3AFB0289A389': 'answer' };
....
<ReactFormGenerator
back_action="/"
back_name="Back"
answer_data={answer}
action_name="Save"
hide_actions={false}
data={this.state.data}
/>
```
