### ISSUE TITLE
callBind is not a function

### ISSUE THREAD

**Issue by zakiAzfar** [Kiho/react-form-builder#130]
![image](https://user-images.githubusercontent.com/61076339/114511813-0500ef80-9c56-11eb-90aa-2445831f9eed.png)

Check My Code 
```js
import React from 'react';

import { ReactFormBuilder } from 'react-form-builder2';
import 'react-form-builder2/dist/app.css';

const FormBuilder = () => {
  return (
    <div>
      hey Man
      <ReactFormBuilder />
    </div>
  );
};

export default FormBuilder;

```

**Comment by Kiho** [comment]
I don't think snowpack & react is good combination at this point.
https://www.npmjs.com/package/@snowpack/app-template-react
