### ISSUE TITLE
Tags returning null

### ISSUE THREAD

**Issue by ProgramacionesWeb** [Kiho/react-form-builder#133]
Hello! I just find an issue that is throwing 'Unexpected Errors on my Application'

It is caused by tag type fields.

These fields by default (without selecting anything) return the following content...

    {
        "name": "tags_D7C832DA-011C-4FE1-A8C4-6493B41055E6",
        "value": []
    }

If we select any of the items from the drop-down it returns them without problems too.

The problem occurs when, After selecting an item from the list, you deselect it and leave the field empty. Then the json looks like this.

    {
        "name": "tags_6AAE2523-1B82-4C78-AB3B-B8DD400D3F19",
        "value": null
    },

That null breaks my app. Something you can do to help? Thanks you so much!

**Comment by Kiho** [comment]
Please update and let me know if you are still facing a issue.

**Comment by ProgramacionesWeb** [comment]
v^0.8.6

Still happening after removing an Item from the Tag Field leaving the field empty.
