### ISSUE TITLE
Build File not created

### ISSUE THREAD

**Issue by AjithKumarRaviChandran** [Kiho/react-form-builder#134]
I tried to create the build file with npm run build: dist script but the build file is not creating, instead of build folder, dist folder is creating in the public folder.

**Comment by Kiho** [comment]
It will create `app.js` in `dist` folder based on this setting https://github.com/Kiho/react-form-builder/blob/master/webpack.production.config.js#L8
I need `dist` folder in public to run server for application test. I don't think anything wrong here.

**Comment by AjithKumarRaviChandran** [comment]
**This is my server code**
server {
    server_name example.com www.example.com;
location / {
proxy_set_header 'Access-Control-Allow-Origin' '*';
        root /var/www/html/formbuilder/dist;
         try_files $uri $uri/ /index.html ;
        include  /etc/nginx/mime.types;
  }
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
server {
    if ($host = www.example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
    if ($host = example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
    server_name example.com www.example.com;
    listen 80;
    return 404; # managed by Certbot
}

**This is my config file:**
var path = require('path');
var webpack = require('webpack');

module.exports = {
  entry: './src/index.jsx',

  output: {
    path: path.resolve('./dist'),
    filename: 'app.js',
    library: 'ReactFormBuilder',
    libraryTarget: 'umd',
    umdNamedDefine: true,
  },

  externals: {
    //don't bundle the 'react' npm package with our bundle.js
    //but get it from a global 'React' variable
    'react': {
      'commonjs': 'react',
      'commonjs2': 'react',
      'amd': 'react',
      'root': 'React'
    },
    'react-dom': {
      'commonjs': 'react-dom',
      'commonjs2': 'react-dom',
      'amd': 'react-dom',
      'root': 'ReactDOM'
    },
    // 'react-datepicker': 'react-datepicker',
    // 'classnames': 'classnames',
    // 'jquery': 'jquery',
    'bootstrap': 'bootstrap'
  },

  resolve: {
    extensions: ['./mjs', '.js', '.jsx', '.scss', '.css', '.json'],
    alias: {
      "jquery": path.join(__dirname, "./jquery-stub.js")
    }
  },

  module: {
    rules: [
      {
        exclude: /node_modules/,
        test: /\.js|.jsx?$/,
        use: [
          { loader: 'babel-loader' }
        ]
      },
      {
        test: /\.scss$/,
        use: [
          {
            loader: 'style-loader'
          },
          {
            loader: 'css-loader'
          },
          {
            loader: 'sass-loader', options: {
              sassOptions: {
                includePaths: ['./node_modules'],
              },
            }
          }
        ]
      },
    ]
  },
  performance: {
    hints: false
  }
};


@Kiho When i build and run the project an empty page is showing,

![Screenshot 2021-04-28 124226](https://user-images.githubusercontent.com/71871514/116362406-a45ddf00-a81f-11eb-8228-b6cbdb9296c0.png)
![Screenshot 2021-04-28 124326](https://user-images.githubusercontent.com/71871514/116362427-a889fc80-a81f-11eb-911e-fcd39dc03f7a.png)

**Comment by Kiho** [comment]
That configuration is for building a library not for the application. you should make input and output like this https://github.com/Kiho/react-form-builder/blob/master/webpack.config.babel.js#L5 but need to adjust it for production.

**Comment by AjithKumarRaviChandran** [comment]
@Kiho  We are using the same configuration, can you kindly help us to understand what kind of adjustment to be made in the production, in the nginx server configuration, do i need to call dist folder contains(app.js) or the public folder(public folder contains index.html).

**Comment by Kiho** [comment]
If you need to build app from source then copy index.html from `public`, and app.js from `dist` folder after build. Also do `npm run build:style` then copy app.css from `dist` folder. if you don't need to modify form-builder then follow this example https://github.com/Kiho/react-form-builder/blob/master/examples/custom/index.html

**Comment by AjithKumarRaviChandran** [comment]
@Kiho I Have done what you have mentioned in the previous reply, but still I am getting the blank screen after hosting to server,
This is my index.html code in public folder
`<!DOCTYPE html>
<html lang="en">
<head>
  <meta  charset="utf-8"/>
  
  <title>React Form Builder </title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <style>
    body {
      font-size: 14px;
      background: #fafafa;
      font-weight: 300;
      color: #404d5b;
       width: 98%; 
        /* height: 100; */
      margin:  20px;
   
    overflow-y: scroll;
    overflow-x: scroll;
    }
    .modal { background: rgba(0,0,0, 0.3);}
    .modal-content { padding: 30px; max-height: 800px; width: 600px ; margin-right:400px ; overflow-y: auto }
  </style>
</head>
<body>
  <script>
    var FORM_ACTION = "/testing";
    var FORM_METHOD = "POST";
  </script>
  <div id="demo-bar"></div>
  <div id="form-builder"></div>
  <div id="show-form"></div>
  <script type="text/babel" src="/app.js"></script>
</body>
</html>
`
This is my public folder
![Screenshot 2021-05-13 092455](https://user-images.githubusercontent.com/71871514/118075548-d6e60b00-b3cd-11eb-97d2-9a7759fedd47.png)

This is my dist folder
![Screenshot 2021-05-13 092515](https://user-images.githubusercontent.com/71871514/118075575-ecf3cb80-b3cd-11eb-835f-cc86065c3379.png)

My config.js is
var path = require('path');
var webpack = require('webpack');

module.exports = {
  entry: './src/index.jsx',

  output: {
    path: path.resolve('./dist'),
    filename: 'app.js',
    library: 'ReactFormBuilder',
    libraryTarget: 'umd',
    umdNamedDefine: true,
    publicPath: "/"
  },

  externals: {
    //don't bundle the 'react' npm package with our bundle.js
    //but get it from a global 'React' variable
    'react': {
      'commonjs': 'react',
      'commonjs2': 'react',
      'amd': 'react',
      'root': 'React'
    },
    'react-dom': {
      'commonjs': 'react-dom',
      'commonjs2': 'react-dom',
      'amd': 'react-dom',
      'root': 'ReactDOM'
    },
    // 'react-datepicker': 'react-datepicker',
    // 'classnames': 'classnames',
    // 'jquery': 'jquery',
    'bootstrap': 'bootstrap'
  },

  resolve: {
    extensions: ['./mjs', '.js', '.jsx', '.scss', '.css', '.json'],
    alias: {
      "jquery": path.join(__dirname, "./jquery-stub.js")
    }
  },

  module: {
    rules: [
      {
        exclude: /node_modules/,
        test: /\.js|.jsx?$/,
        use: [
          { loader: 'babel-loader' }
        ]
      },
      {
        test: /\.scss$/,
        use: [
          {
            loader: 'style-loader'
          },
          {
            loader: 'css-loader'
          },
          {
            loader: 'sass-loader', options: {
              sassOptions: {
                includePaths: ['./node_modules'],
              },
            }
          }
        ]
      },
    ]
  },
  performance: {
    hints: false
  }
};

And my server configuration is
server {
    server_name forms.example.com www.forms.example.com;
location / {
proxy_set_header 'Access-Control-Allow-Origin' '*';
        root /var/www/html/formbuilder/public;
         try_files $uri $uri/ /index.html ;
        include  /etc/nginx/mime.types;
  }
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
server {
    if ($host = www.forms.example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
    if ($host = forms.example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
    server_name forms.example.com www.forms.example.com;
    listen 80;
    return 404; # managed by Certbot
}

I have tried this solution but it doesn't help
 https://stackoverflow.com/a/56055153

**Comment by Kiho** [comment]
You are using webpack.config for building library.
Try this webpack.config, then use ./public/app.js
```js
var path = require('path');

module.exports = {
  entry: './app.js',
  devtool: 'source-map',
  output: {
    path: path.resolve('./public'),
    filename: 'app.js'
  },
  resolve: {
    extensions: ['.js', '.jsx', '.scss', '.css', '.json'],
    alias: {
      "jquery": path.join(__dirname, "./jquery-stub.js")
    }
  },
  plugins: [
    //
  ],
  module: {
    rules: [
      {
        exclude: /node_modules/,
        test: /\.js|.jsx?$/,
        use: [
          { loader: 'babel-loader' }
        ]
      },
      {
        test: /\.scss$/,
        use: [
          {
            loader: 'style-loader'
          },
          {
            loader: 'css-loader'
          },
          {
            loader: 'sass-loader', options: {
              sassOptions: {
                includePaths: ['./node_modules'],
              },
            }
          }
        ]
      },
    ]
  },
  performance: {
    hints: false
  }
};
```

**Comment by Kiho** [comment]
Remove `devtool: 'source-map',` if you don't need debugging.

**Comment by Kiho** [comment]
`entry: './src/index.jsx',` mean you are building library, you should do `entry: './app.js',` for  application build.

**Comment by AjithKumarRaviChandran** [comment]
I tried this, but same blank screen is showing


[](var path = require('path');
var webpack = require('webpack');

module.exports = {
  entry: './app.js',
  devtool: 'source-map',
  output: {
    path: path.resolve('./public'),
    filename: 'app.js',
    publicPath: "/"
  },
  resolve: {
    extensions: ['.js', '.jsx', '.scss', '.css', '.json'],
    alias: {
      "jquery": path.join(__dirname, "./jquery-stub.js")
    }
  },
  plugins: [
    //
  ],
  module: {
    rules: [
      {
        exclude: /node_modules/,
        test: /\.js|.jsx?$/,
        use: [
          { loader: 'babel-loader' }
        ]
      },
      {
        test: /\.scss$/,
        use: [
          {
            loader: 'style-loader'
          },
          {
            loader: 'css-loader'
          },
          {
            loader: 'sass-loader', options: {
              sassOptions: {
                includePaths: ['./node_modules'],
              },
            }
          }
        ]
      },
    ]
  },
  devServer: {
    port: 8080,
    host: "localhost",
    historyApiFallback: true,
    headers: {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, PATCH, OPTIONS",
        "Access-Control-Allow-Headers": "X-Requested-With, content-type, Authorization"
    },
    watchOptions: {aggregateTimeout: 300, poll: 1000},
    contentBase: './public',
    open: true,
    proxy: {
      "/api/*": "http://127.0.0.1:5005"
    }
  }
};)

In my package.json

`["scripts": {
    "build": "webpack -p --config webpack.production.config.js",
    "build:dev": "webpack --mode development",
    "build:umd": "webpack --mode development --config webpack.production.config.js",
    "build:style": "node-sass ./scss/application.scss dist/app.css --output-style compressed",
    "build:lib": "npm run transpile && npm run build:style",
    "build:dist": "npm run build && npm run copy:dist",
    "copy:dist": "copyfiles -f \"./dist/*\" \"./public/dist\"",
    "prepublish": "npm run build:lib && npm run build",
    "watch": "webpack --watch",
    "start": "webpack-dev-server --hot --inline --mode development",
    "serve:api": "node server/index.js",
    "pretranspile": "rimraf lib",
    "transpile": "babel --out-dir lib src --copy-files"
  }`](URL)


In my console I am getting this index.html file
![Screenshot 2021-05-13 151821](https://user-images.githubusercontent.com/71871514/118109391-c1d5a000-b3fe-11eb-81bd-6c9d08153d4c.png)

**Comment by AjithKumarRaviChandran** [comment]
@Kiho Thanks alot for helping me out, I solved the issue by adding`  <script type="text/javascript" src="/app.js"></script> 
` in the index.html file and,
I replaced the wepack.production.config.js code with your above mentioned code, it worked!
