### ISSUE TITLE
Make mongo example to handle multiple forms creation

### ISSUE THREAD

**Issue by Soknath** [Kiho/react-form-builder#135]
Very nice library. May I ask for your advise.
I would like to use mongo backend to store multiple forms, which can be created, edited and deleted.
How to archive that based on current mongo example?

Thank you in advance.

**Comment by Kiho** [comment]
You can find  example of multiple form instance here https://github.com/Kiho/react-form-builder/blob/master/examples/custom/app.js and snippets of server side code here https://github.com/Kiho/react-form-builder/issues/101

**Comment by Robokishan** [comment]
the one which you have hosted seems not working...
Can you put it in example the one which you have hosted on demo?

**Comment by Kiho** [comment]
Hosted API server on Heroku runs out of free time this month, it will be back to work on starting of month.

**Comment by Robokishan** [comment]
Oh ok, that's great. Is the front end available in example?

**Comment by Kiho** [comment]
Front-end is hosted at github, you can find source here https://github.com/Kiho/react-form-builder/tree/master/docs

**Comment by Robokishan** [comment]
Thank you
