### ISSUE TITLE
npm install throwing error

### ISSUE THREAD

**Issue by AjithKumarRaviChandran** [Kiho/react-form-builder#136]
@Kiho when we try running npm install  we are getting the below error  Unknown plugin "@babel/plugin-proposal-class-properties.I have even tried installing the plugin npm install --save-dev @babel/plugin-proposal-class-properties and the when i try to install still i am getting the error not sure how to proceed further kindly help me to solve the below issues, but in local it is working fine

Here is my babelrc file:

`{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react",
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-json-strings",
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-syntax-import-meta"
  ]
}
`
![Screenshot 2021-06-04 085029](https://user-images.githubusercontent.com/71871514/120741193-3be6d980-c512-11eb-8132-2c13e12adc5e.png)
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at Object.compileFunction (node:vm:355:18)
    at wrapSafe (node:internal/modules/cjs/loader:1039:15)
    at Module._compile (node:internal/modules/cjs/loader:1073:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47

**Comment by Kiho** [comment]
I can't replicate problem. If you need help need more details on your project files.

**Comment by AjithKumarRaviChandran** [comment]
Okay, could you please share the details which you want me to share

**Comment by Kiho** [comment]
If you can create git repo with minimal code showing your error will be good.

**Comment by Kiho** [comment]
You can reopen if you still facing a issue.
