### ISSUE TITLE
Can we set default items without using url?

### ISSUE THREAD

**Issue by mitulmarsonia** [Kiho/react-form-builder#14]
Hello,

We are trying to set json data without using url but its not working.

```
 const content = [
  {
      "id": "C68B673B-3948-4D62-AF6D-5320CAB4DDB7",
      "element": "TextInput",
      "text": "Text Input",
      "required": true,
      "canHaveAnswer": true,
      "field_name": "text_input_EEA6F5DA-5C2C-43D3-AB62-62385E3925D9",
      "label": "<div>Name</div>\n"
  },
  {
      "id": "6DAF1E95-44F6-4E5B-ABDD-D9A6BCA2C08A",
      "element": "TextInput",
      "text": "Text Input",
      "required": true,
      "canHaveAnswer": true,
      "field_name": "text_input_C5305462-9704-4E77-BFAB-A43C14AB2B8E",
      "label": "<div>Email</div>\n"
  }
];

<ReactFormBuilder variables={variables} data={content} />
```

This is working fine:-

`  <ReactFormBuilder variables={variables} url="http://localhost/temp.json" />`

Can you please help me out.
Thank you.

**Comment by Kiho** [comment]
This branch should work for you. https://github.com/Kiho/react-form-builder/tree/fix-data

**Comment by mitulmarsonia** [comment]
Thank you so much for replay,

I have install through `npm i react-form-builder2`
Any suggestion for install specific branch ?

**Comment by mitulmarsonia** [comment]
One more issue once form generated then after we fill form its okay. Now we want show form with answer but its not working. I'm using like this.

```
<ReactFormGenerator
          answer_data={answer.content}
          display_short
          hide_actions
          read_only
          data={form.content}
        />
```

**Comment by Kiho** [comment]
I merged & published code, so you can reinstall from npm.
I don't see any issue with answer data, you need to make sure id for control in answer_data match with form data.
```const answer = { "text_input_EEA6F5DA-5C2C-43D3-AB62-62385E3925D9": "answer" }```

**Comment by Kiho** [comment]
Then, maybe you need to convert it to this format.
```
        {
           "date_picker_EA95C892-0CF8-4A3C-A213-9E05C61B5CF6": "01/02/2019",
           "text_input_CA7D3263-BBAA-41A1-B6D5-695D44CBCB5D": "nothing"
        }
```

**Comment by mitulmarsonia** [comment]
Thank you for answer,
I'm trying to install package like this -> `npm install --save https://github.com/Kiho/react-form-builder`

It does not work can you please update npm so we reinstall and check it.

**Comment by Kiho** [comment]
If you still have issue then I will reopen it
