### ISSUE TITLE
Cannot have two HTML5 backends at the same time.

### ISSUE THREAD

**Issue by AngelinSneha** [Kiho/react-form-builder#144]
I am using react-fom-builder in my project.
When I drag and drop more than one item into the form from the toolbox i get an error saying **Uncaught Error: Cannot have two HTML5 backends at the same time.**
But if there is only one item in the form, the form is working fine.
 My code:
```
import { ReactFormBuilder } from "react-form-builder2";
<ReactFormBuilder
       onSubmit={(e) => console(e)}
       onPost={(e) => console(e)}
/> 
```
Can someone help me out with this error?

ERROR:
<img width="956" alt="2021-07-30 (5)" src="https://user-images.githubusercontent.com/66509492/127727196-51083f70-e11d-4441-b033-a0ce2e2a0b7f.png">

**Comment by Kiho** [comment]
You have to feed source of form data to ReactFormBuilder.
By URL
```js
  <ReactFormBuilder variables={variables}
    url='/api/formdata'
    saveUrl='/api/formdata'
  />
```
or Function
``` js
  <ReactFormBuilder
    onLoad={this.onLoad}
    onPost={this.onPost}
  />
```
You can find more from examples https://github.com/Kiho/react-form-builder/tree/master/examples

**Comment by AngelinSneha** [comment]
Hi, Thank You for replying.
```
<ReactFormBuilder
    onLoad={this.onLoad}
    onPost={this.onPost}
  />
```
The above code worked when i initially fill a form, thank you.
But it is not working when i have a pre-filled form, I am getting the same error.
My code right now is:
```
<ReactFormBuilder
    data={this.state}
    onSubmit={this.onSubmit}
    onLoad={this.onLoad}
    onPost={this.onPost}
  />
```
where the `state` contains the inital form that the i created, now when i try to edit this form (by adding another toollist item to the form), I am facing the same error.

**Comment by AngelinSneha** [comment]
Hi, Thank You for replying.
```
<ReactFormBuilder
    onLoad={this.onLoad}
    onPost={this.onPost}
  />
```
The above code worked when i initially fill a form, thank you.
But it is not working when i have a pre-filled form, I am getting the same error.
My code right now is:
```
<ReactFormBuilder
    data={this.state}
    onSubmit={this.onSubmit}
    onLoad={this.onLoad}
    onPost={this.onPost}
  />
```
where the `state` contains the inital form that the i created, now when i try to edit this form (by adding another toollist item to the form), I am facing the same error.

**Comment by Kiho** [comment]
I don't think you can have both onPost & onSubmit.

**Comment by AngelinSneha** [comment]
On post i am just saving the data to the state, on Submit i am saving it in the backend, isn't that okay?

**Comment by Kiho** [comment]
ReactFormBuilder maintain states internally https://github.com/Kiho/react-form-builder/blob/master/src/stores/store.js
You should not try to do external state management. And onSubmit is property of form generator it's not for builder.
If you want to post json to server then use `onLoad` & `onPost` otherwise use `url` & `saveUrl` to post data to your back-end

**Comment by AngelinSneha** [comment]
Oh Thank you, I am not using onSubmit anymore, but the form is still **not working** when i have a pre-filled form, I am getting the same error when i am using onPost too.

**Comment by Kiho** [comment]
Try update rfb version to 0.8.8

**Comment by AngelinSneha** [comment]
Still getting the same error.

**Comment by Kiho** [comment]
I can't understand error without seeing the code.
If you need more help then please create github repo with reproducing the error.

**Comment by AngelinSneha** [comment]
I was calling the FormBuilder twice at the same time, that's why i was facing the error.
Thank you for helping with the onLoad concept.
