### ISSUE TITLE
[ONLOAD]

### ISSUE THREAD

**Issue by Robokishan** [Kiho/react-form-builder#145]
Can we load form without using onLoad, like from state variables. i am using redux where I have stored API response in redux state but then loading that into the form. 

i used this hack

```
const form = useSelector(state => state.forms.form);

const onLoad = () => {
        return new Promise(function (resolve, reject) {
            console.log(form)
          resolve( form?.form?.task_data ? form?.form?.task_data  : [] )
        });
    }
```

But its not reasonable since when the task_data changes form has to be rerender which is not happening since function has to be called manually. is there any way ?

**Comment by Robokishan** [comment]
i tried this also but it seems like it is not renredering any help ?
`<ReactFormBuilder data={form.form.task_data} />`

**Comment by Kiho** [comment]
You can try to assign a key to rfb like this https://github.com/Kiho/react-form-builder/issues/122
