### ISSUE TITLE
Getting error while implementing react form builder

### ISSUE THREAD

**Issue by kapilmrbond** [Kiho/react-form-builder#148]
Hi Kiho
I am getting below error after installing react-form-builder using '**npm -i react-form-builder**' 

"Could not find a declaration file for module 'react-form-builder2'. '.../node_modules/r**eact-form-builder2/lib/index.js' implicitly has an 'any' type**."
Tried  `**npm i --save-dev @types/react-form-builder2**` as well, but this seems not available.

Am i missing something here. Would really appricate your help in resolving this issue.

**Comment by Kiho** [comment]
Hi @kapilmrbond,

The latest version should work with your case, but still may not work in some cases.
You can try it but I do not recommend to use typescript at this point.
