### ISSUE TITLE
date, radio, star, checkbox  field  editable bug

### ISSUE THREAD

**Issue by mitulmarsonia** [Kiho/react-form-builder#15]
Hello Sir,

When we set `read_only` then after date, radio, star, checkbox field editable, text filed not editable its working fine,
Can you please help me out.

**Comment by mitulmarsonia** [comment]
Thank you so much. 
I have checked all above issue are fixed.

Same issue in Tags component can you please fixed it.

One another bug is when we use camera component, it does not save. Can you please help me out.

**Comment by Kiho** [comment]
I fixed problem Tags and also https://github.com/Kiho/react-form-builder/issues/18 probably.
But I do not have time to take care of Camera component at this time. It's much more complicate than other issues and I do not have infra structure for testing image upload functionality.

**Comment by Kiho** [comment]
May you can try implement this example if you are using node https://stackoverflow.com/questions/15772394/how-to-upload-display-and-save-images-using-node-js-and-express
I could not find any issue with posting image from Camera component.

**Comment by mitulmarsonia** [comment]
I have fixed camera component issue can i push code your branch ?

**Comment by Kiho** [comment]
Thanks! It's published
