### ISSUE TITLE
 react-form-builder2 Facing memory leak issue

### ISSUE THREAD

**Issue by krupasavadiya** [Kiho/react-form-builder#150]
I am using  "react-form-builder2": "^0.9.4" version.

```
<ReactFormBuilder
      onLoad={getById}
      onPost={onPost}
  />
```

I am getting form data but facing an issue of memory leak at the time of loading.
This is my getById method: https://ibb.co/y4t1BVr
This is an error I am getting: https://ibb.co/8Myp3JM
Let me know if you have any idea.

Thanks

**Comment by Kiho** [comment]
Looks like setFormName or setFormData is causing rerender of form-builder, you can try without those code first.

**Comment by HemaliSavaliya93** [comment]
Yes, facing the same issue if I ignoring those two.
Apart from that if I running your base code and just add console.log in that as you can see in the screenshot: https://ibb.co/tpNwW8h
Facing the same issue in that also. https://ibb.co/PTCgtyK

Thanks

**Comment by Kiho** [comment]
I can't reproduce warning myself, you can check this out, it looks same type of issue.
https://github.com/Kiho/react-form-builder/issues/92#issuecomment-680747440
