### ISSUE TITLE
How to add page break?

### ISSUE THREAD

**Issue by HemaliSavaliya93** [Kiho/react-form-builder#152]
When I click on check box of Page Break Before Element? but In Preview of form it is not showing the element in new page or next page.Is there any option to add functionality like this?

**Comment by Kiho** [comment]
I do not know how that work either, it's designed by original author, you may need to research [CSS page-break-before Property](https://www.w3schools.com/cssref/pr_print_pagebb.asp). Looks like it only works for printing.
