### ISSUE TITLE
Draghandle (Grip ) 

### ISSUE THREAD

**Issue by dohoangtung** [Kiho/react-form-builder#159]
Draghandle (Grip ) is not working!

![image](https://user-images.githubusercontent.com/40049759/150155728-cf9e0f93-3565-47bc-9bbd-d4082b6f4bf4.png)

**Comment by Kiho** [comment]
Grip is useful for moving in & out to multi column components only, otherwise drag any part of component to move around.

**Comment by dohoangtung** [comment]
So in term of UI/UX, it doesn't make sense! If you put the drag handle, users will understand that they can use the handle to move the card anywhere, either sort cards or move it to multi column placeholders. They will not understand that the drag handle just be used for the multi-column. I think the behavior should be one of following:

1. Use the drag handle as the only one way to either move card into multi-column placeholders or sort cards
2. Remove the handle and keep the current drag/drop behavior and also allow to move the card to multi-column placeholders.

**Comment by Kiho** [comment]
Technically, it's very hard to implement your suggestion, it will introduce a lot of issues, unfortunately I have too many other things on my plate. So, I can't spend too much time on this project, if you really need it then you can place PR.

**Comment by dohoangtung** [comment]
OK, I will work on it. 
Thanks
