### ISSUE TITLE
Form is not getting pre populated with the answer data.

### ISSUE THREAD

**Issue by kart1ka** [Kiho/react-form-builder#162]
The form is being generated by React Form Generator but the form is not getting populated by the answer data that I am fetching from my backend (firebase). I am passing the answer data to the `answer_data` prop of `ReactFormGenerator`. I also made sure that the answer data is also an array. Can you help me out please?

Here is the value of the answerData state - `[
    {
        "custom_name": "text_input_A0DFAA18-EDBA-4E93-8E2E-04D957D171F9",
        "name": "text_input_A0DFAA18-EDBA-4E93-8E2E-04D957D171F9",
        "value": "Kartika Goyal"
    }
]`

Here is the value of the taskData state - `
[
    {
        "canHaveAlternateForm": true,
        "canHaveAnswer": true,
        "canHaveDisplayHorizontal": true,
        "canHaveOptionCorrect": true,
        "canHaveOptionValue": true,
        "canHavePageBreakBefore": true,
        "canPopulateFromApi": true,
        "dirty": false,
        "element": "TextInput",
        "field_name": "text_input_A0DFAA18-EDBA-4E93-8E2E-04D957D171F9",
        "id": "0C990FD7-B414-458C-AAC8-A64B2DA3E495",
        "label": "Full Name ",
        "required": false,
        "text": "Text Input"
    }
]
`

![code1](https://user-images.githubusercontent.com/41051387/155878326-01245390-1511-4cb4-9a37-4161ee38ccac.png)
![code4](https://user-images.githubusercontent.com/41051387/155878613-9bd49880-d429-4272-b820-ca5d0cda5741.png)
![code3](https://user-images.githubusercontent.com/41051387/155878401-dc99eb55-8e47-4435-bd35-e7416152f843.jpg)

Also as you can see in the Screenshots the value of the Submit and Back buttons are also not changing to Approve And Reject respectively as I have provided to `ReactFormGenerator` .

**Comment by Kiho** [comment]
@kart1ka Can you try change answer_data to object like below
```json
{ "text_input_A0DFAA18-EDBA-4E93-8E2E-04D957D171F9": "Kartika Goyal" }
```

**Comment by kart1ka** [comment]
I tried doing that. It doesn't work. I did some debugging on my own and I think what's happening is that initially when the component renders the value of both answerData and taskData state is `[]`. So, the `<ReactFormGenerator />` component is rendered according to those values. But when the `useEffect` function runs and the values of `answerData` and `taskData` states get updated, the following code inside form.jsx file does not execute again for the new value of `answerData` state.
![code5](https://user-images.githubusercontent.com/41051387/155973165-446be06b-2707-418c-9ad0-1c3ae19c3bff.png)

But the following code executes again for the new value of the `taskData` state. 
![code6](https://user-images.githubusercontent.com/41051387/155973468-d8fa8b61-7105-4c9b-9b39-b4c434a6f935.png)

Hence, form fields get rendered on the screen but their value is not rendered. I have tested this by putting the initial values of `answerData` state as `[
        {
          custom_name: "text_input_A0DFAA18-EDBA-4E93-8E2E-04D957D171F9",
          name: "text_input_A0DFAA18-EDBA-4E93-8E2E-04D957D171F9",
          value: "Kartika Goyal",
        },
      ]` and in that case the fields are getting populated with the answer data. 
![code7](https://user-images.githubusercontent.com/41051387/155974736-484348c7-f74d-4964-b714-5eac84fce0ec.png)
<img width="957" alt="image" src="https://user-images.githubusercontent.com/41051387/155974828-bdce8370-a8ed-4eb8-9185-236b0d804b52.png">

Can you please check why is this happening?
Thanks.

**Comment by Kiho** [comment]
You can try to assign a key to rfb like this https://github.com/Kiho/react-form-builder/issues/122

**Comment by kart1ka** [comment]
As I understand passing a key is like passing a Unique identifier. I tried adding a key prop (and passed a Unique Identifier as the value of that prop) to the `<ReactFormBuilder />`. But that doesn't work either. It also leads to the Form Builder Page not working anymore. And how was passing a key prop to the ReactFormBuilder component supposed to resolve the issue faced in the ReactFormGenerator Component?
Below is my code - 
![code8](https://user-images.githubusercontent.com/41051387/156234642-32155001-a0ff-4a36-992a-47d0198b5ef4.png)
Below are the errors that occur when I try to load Form Builder - 
![Screenshot (1989)](https://user-images.githubusercontent.com/41051387/156234869-54a1ff2f-08cb-406a-83e1-5e99ccf8d1fd.png)
![Screenshot (1990)](https://user-images.githubusercontent.com/41051387/156234889-ac5c8c11-e582-490d-920a-2b19ef2cec5a.png)

**Comment by Kiho** [comment]
There are 2 components in rfb, builder & generator, key should be applied to generator but it's not for builder.
Also, use uuid as a key is worst choice, you should use key which is pointing unique & consistent identification of of object.

**Comment by Kiho** [comment]
https://stackoverflow.com/questions/52705335/will-using-uuid-to-as-list-keys-cause-unnecessary-re-renders-in-react
You should change key when you need force rerender. I suggest you to move key generation out to parent component.

**Comment by kart1ka** [comment]
I am updating the key inside the `useEffect` after I fetch my answer details from the backend and update the `answerData` state.  It's still not working.
I am new to this, so if you could please write a small example code in the examples folder (about how to fetch answer data from backend using create-react-app and useEffect) as you have done for Next.JS.

I went through the stackoverflow link that you shared but it didn't help much.


![code12](https://user-images.githubusercontent.com/41051387/156445140-984dd1f7-577a-4617-8182-6be207b675b7.png)

![code13](https://user-images.githubusercontent.com/41051387/156445166-555067b5-bdbc-4155-afa7-718b0f69d5b4.png)

Errors-
![image](https://user-images.githubusercontent.com/41051387/156445075-05f6ec4b-3957-4d17-bc24-add739b21143.png)

**Comment by Kiho** [comment]
Sorry, but I am too busy, don't have time to create sample in near future.
You should generate new key when you getting new answer data.

**Comment by kart1ka** [comment]
I totally understand that you are busy. Just tell me what I'm doing wrong here. I am doing exactly as you said. I am changing the key after getting the new values of answer data. But, as you can see in the above comment, it is giving me errors - Can not read properties of undefined (reading `indexOf`) - in the form.js component of the library.

**Comment by Kiho** [comment]
It maybe rfb bug, I have to check the logic but looks like you should supply task data before answer data.

**Comment by kart1ka** [comment]
I tried supplying task data before answer data. But it still does not work. It is still giving me same error -  Can not read properties of undefined (reading `indexOf`) - in the form.js (line 101) component of the library. Can you please check and resolve this bug?
Thank You.

**Comment by Kiho** [comment]
I have no idea where can be problem with your code & environment.
If you really need help then you need create and replicate problem in github project.

**Comment by kart1ka** [comment]
The problem is solved.
Thank You very much for your help.

**Comment by ingalesachin7** [comment]
@kart1ka Can you please provide the solution

**Comment by ingalesachin7** [comment]
@kart1ka Can you please provide the solution...
