### ISSUE TITLE
Facing issue in the appliaction

### ISSUE THREAD

**Issue by sumaliyareddy** [Kiho/react-form-builder#165]
Hi,

![Screenshot (464)](https://user-images.githubusercontent.com/101261923/160386040-f308ae7b-0a13-44d4-af23-bf78c2616f0b.png)

when i am trying to run the application ,i am getting the below error.could u please check this and assist me .

**Comment by Kiho** [comment]
Make sure do steps in readme.

``` bash
$ yarn install
$ yarn run build:dist
$ yarn run serve:api
$ yarn start
```
Try use bash instead of powershell
