### ISSUE TITLE
Issues with the File Attachment field & underlining a text in the form builder 

### ISSUE THREAD

**Issue by kart1ka** [Kiho/react-form-builder#166]
Hey Kiho.
I have found some issues while using the File Attachment form field. When I try to add a file to the file attachment field in its edit window. It does not allow me to choose any file. It just shows a blank dropdown menu (as shown in the image below).
![image](https://user-images.githubusercontent.com/41051387/160429418-d66e93b7-dc1a-4794-892e-502692ff81ff.png)
And When I click on the file attachment field (Sample File Attachment field in the image below) in the preview window (See Image-A). It takes me back to the form builder page (See Image-B).

Image-A:
![image](https://user-images.githubusercontent.com/41051387/160429856-03756c80-0570-4a4b-b5dd-f6926213f5ef.png)

Image-B:
![image](https://user-images.githubusercontent.com/41051387/160430119-4d73e4eb-4661-43f0-a900-95ee42b88be3.png)

The other issue I am facing is when I try to underline a text (for example a text in a label) it does not show the underlined text in the form render window. It just shows the supposed to be underlined text between `ins` tag. See the `Sample <ins>Label</ins>` in the image below.
![image](https://user-images.githubusercontent.com/41051387/160431000-0b84e20a-f9fe-44c8-b68b-9f6d5a422149.png)
 Can you please see what's happening?
Thank You.

**Comment by Kiho** [comment]
You can create list of items in app.js
```js
  <FormBuilder.ReactFormBuilder
    files={[{ id: '1', file_name: 'homeIllustration.svg', more... }]}
```
You need to setup file download API in server then put URL to
```js
  <ReactFormGenerator
     download_path="https://your.domain.com/files/"
```

**Comment by Kiho** [comment]
Try v0.10.2 for underline support.
