### ISSUE TITLE
Is is possible to input time in datepicker rather than select a time.

### ISSUE THREAD

**Issue by codepurse** [Kiho/react-form-builder#169]

**Comment by Kiho** [comment]
You can try  v0.10.4

**Comment by codepurse** [comment]
Thanks brother! But I noticed that I cant type time It doesn't do anything unless I click the timer icon near the time Input,

**Comment by Kiho** [comment]
You can type number at input box, no need for timer icon click.

**Comment by codepurse** [comment]
Yeah but for some reason I cant type :(

**Comment by Kiho** [comment]
You can type number at input box with timer icon. if your intention is  type it to InputBox hosting date-picker then you have to implement custom component by your self.

**Comment by Kiho** [comment]
Make sure you select Show Time Input on edit form.

**Comment by codepurse** [comment]
Thanks! Its just a issue in my css. Ill close this now :)
