### ISSUE TITLE
Warning: Can't call setState on a component that is not yet mounted

### ISSUE THREAD

**Issue by kart1ka** [Kiho/react-form-builder#174]
I am getting `Can’t perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application.` warning in my console (See attached image below) - 

![image](https://user-images.githubusercontent.com/41051387/163269329-bf98ffc7-3909-4d9e-b3a5-15fcd8a6d352.png)

I have reproduced the same warning message in my GitHub repo linked below:

https://github.com/kart1ka/form-builder

Just download the code and run `npm install` and then `npm start` and you will see the warning message in the console.

The message says that the error is coming from the Preview file of the React Form Builder-2 library.
Can you please take a look at it?
Thank You.

PS - The warning disappears when the `<React.StrictMode>` is removed from index.js file.

**Comment by Kiho** [comment]
Please try find answer there - https://github.com/Kiho/react-form-builder/issues/92

**Comment by kart1ka** [comment]
I already looked at that issue. I don't think it has the solution to my problem. The link mentioned in that issue suggests a solution for error occurring because of async tasks. But in the repo that I have linked above I do not have any async task running. All I have is a simple Form Builder, a Form Render & a Demobar component in my code. So the warning could not have come from an async task.
Can you please take a look at my repo?
https://github.com/kart1ka/form-builder

**Comment by Kiho** [comment]
https://github.com/RisingStack/react-easy-state/issues/196#issuecomment-766367636
Sorry, but I don't have clear idea on this issue.

**Comment by kart1ka** [comment]
I think I might have figured out why this is happening. This might have to do with the handling of the code related to the subscription in the library.
I googled a bit & found that the subscriptions must be handled inside the `componentDidMount` and not inside the `constructor` function of the component.

Below is a link for reference:

https://www.digitalocean.com/community/tutorials/react-constructors-with-react-components#:~:text=For%20things%20like%20subscriptions%20that%20will%20update%20the%20state%20and%20other%20side%2Deffects%2C%20you%20should%20put%20the%20logic%20out%20in%20componentDidMount()%20which%20will%20fire%20immediately%20after%20the%20component%20is%20mounted%20and%20won%E2%80%99t%20give%20you%20any%20trouble%20if%20you%20update%20the%20state%20inside%20of%20it.

So I tried to implement this. As you can see in the image below, I was getting error in three files of React FormBuilder library - Demobar, Preview, and Toolbar. 

![image](https://user-images.githubusercontent.com/41051387/163626177-9b916ebf-10bb-4832-8a9c-90bb05d9414f.png)

As you can see in the image below, in the Demobar.js file, the code related to the subscription is also present inside the `constructor` function.

![code3](https://user-images.githubusercontent.com/41051387/163627172-2616b792-8a41-4bd3-b5c8-44b08c21d25b.png)

So, in the Demobar.js file, I moved that code to the `componentDidMount` function and, as you can see in the image below, the error related to the Demobar file disappeared. It is only showing errors in the Preview & Toolbar files.

![image](https://user-images.githubusercontent.com/41051387/163626224-a8bc5aa5-e98f-4f51-8673-cacb6a11fc2f.png)

![code2](https://user-images.githubusercontent.com/41051387/163627160-8eedbcdf-c6c9-47be-b91d-a0c551b57215.png)

Can you please move the lines related to the subsciption, in the Preview.jsx & Toolbar.jsx files, to the `componentDidMount` from the `constructor` function?
This might solve the issue.
I have marked the lines, that I think should be moved to the `componentDidMount` function in the images below:

![code4](https://user-images.githubusercontent.com/41051387/163629034-07f4defb-26de-4765-ad93-430667ac0e67.png)

![code7](https://user-images.githubusercontent.com/41051387/163629616-2801c63d-1938-4231-b177-2b5823518750.png)


Thank You.

**Comment by Kiho** [comment]
Looks like that was the reason of warning, Thanks.
