### ISSUE TITLE
Custom Component not rendering on FormGenerator side

### ISSUE THREAD

**Issue by GUMahesh** [Kiho/react-form-builder#177]
const TestComponent = () => <h2>Hello</h2>;

Registry.register('TestComponent', TestComponent);

const items = [{
  key: 'TestComponent',
  element: 'CustomElement',
  component: TestComponent,
  type: 'custom',
  field_name: 'test_component',
  name: 'Something You Want',
  icon: 'fa fa-cog',
  static: true,
  props: { test: 'test_comp' },
  label: 'Label Test',
},.......

<ReactFormBuilder
    ...
    toolbarItems={items}
  />
ReactFormBuilder ToolBox showing the custom component, but ReactFormGenerator side is not showing custom component.
I am facing below issue..
![image](https://user-images.githubusercontent.com/104315709/164985487-ac22dfff-76ad-4bca-bfc7-9d84155f8c28.png)

![image](https://user-images.githubusercontent.com/104315709/164985525-2787e77f-5611-4967-ae7c-8fbf27a5d39f.png)

in the above image component property value is undefined. Please help me here.

**Comment by Kiho** [comment]
This example running fine without any issues, you can compare your project with it.
Please make sure to register your custom components before you using in FormGenerator.

**Comment by GUMahesh** [comment]
Hi Kiho, I do not have any issues on Form Builder side, I am able to place custom component into the form.  My custom component got registered, thats why am able to view it in the tool box at Form Builder side. I am able to save the data in DB. In the FormGenerator side to render the form, I am getting the previously saved data from the DB. FormGenerator side i am facing the issue as mentioned above.

**Comment by GUMahesh** [comment]
How to render React Form Generator with the data from DB. I am using like this...
<ReactFormGenerator
              task_id={12}
              answer_data={{}}
              data={this.state.data} // Question data
              onSubmit={(e) => this.handleSubmitAndUpdate(e)}
              submitButton={
                <button
                  type={"submit"}
                  id="saveBtn"
                  hidden
                  className={"btn btn-primary"}
                >
                  Save
                </button>
              }
            />
I am getting the error in console as **Custom Element was not registered**. I need clear example here. am i missing any configuration?

**Comment by Kiho** [comment]
There is no magic here, saving json can't transfer custom components from builder to generator.
You have to register same custom components you  are using in builder in generator side if your saved json contains custom components.
```jsx
const TestComponent = () => <h2>Hello</h2>;

const MyInput = React.forwardRef((props, ref) => {
  const { name, defaultValue, disabled } = props;
  return <input ref={ref} name={name} defaultValue={defaultValue} disabled={disabled} />;
});

Registry.register('MyInput', MyInput);
Registry.register('TestComponent', TestComponent);
  .....
<ReactFormGenerator
  task_id={12}
  answer_data={{}}
  data={this.state.data} // Question data
  onSubmit={(e) => this.handleSubmitAndUpdate(e)}
  submitButton={
  <button
    type={"submit"}
    id="saveBtn"
    hidden
    className={"btn btn-primary"}
  >
  .....
/>
```

**Comment by GUMahesh** [comment]
Thank you, it is working after registering the custom components on React Form Generator side.
