### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by finnjefferis** [Kiho/react-form-builder#183]
Trying to migrate to Next.JS and I'm getting an error (ReferenceError: window is not defined) at next-form-builder/node_modules/react-form-builder2/node_modules/react-draft-wysiwyg/dist/react-draft-wysiwyg.js (1:393).

Is this a case of react-draft-wysiwyg not being compatible with Next.JS? Are there any workarounds I could implement?

Thanks

**Comment by Kiho** [comment]
Please try v0.11.1 and let me know if it still not working.

**Comment by finnjefferis** [comment]
Seems to be all fixed! Thank you!

**Comment by TerrenceMM2** [comment]
I am getting this error now after coming back to a project. I've upgraded the package to the latest version (0.11.3). Like @finnjefferis, my project is using NextJS. All I've done is use the `<ReactFormBuilder>` component (without any props). I've done a fresh install of the packages as well as removed the `.next` cache folder.

Please let me know if I can provide any additional information.
