### ISSUE TITLE
data.forEach is not a function

### ISSUE THREAD

**Issue by finnjefferis** [Kiho/react-form-builder#184]
![gitprob3](https://user-images.githubusercontent.com/91462667/167838759-ba089606-5d67-4f35-8bfb-c5dba9952fea.PNG)

Stuck on this error and I'm struggling to find a solution. Haven't changed anything in the file the error occurs in and I've reverted my recent additions and the problem persists. Any help greatly appreciated.

**Comment by Kiho** [comment]
Looks like you got object instead of array as form data, you may need to clean up saved form data from server
