### ISSUE TITLE
Error while uploading image using camera component

### ISSUE THREAD

**Issue by kart1ka** [Kiho/react-form-builder#187]
Hey Kiho. I am using Camera component in my form. I am handling image upload using multer on my backend.
But when I try to upload an image using the Camera component I get the following error:
`
PayloadTooLargeError: request entity too large
    at readStream (C:\Users\Asus\Desktop\Project A\project-g\node_modules\raw-body\index.js:155:17)
    at getRawBody (C:\Users\Asus\Desktop\Project A\project-g\node_modules\raw-body\index.js:108:12)
    at read (C:\Users\Asus\Desktop\Project A\project-g\node_modules\body-parser\lib\read.js:77:3)
    at jsonParser (C:\Users\Asus\Desktop\Project A\project-g\node_modules\body-parser\lib\types\json.js:135:5)
    at Layer.handle [as handle_request] (C:\Users\Asus\Desktop\Project A\project-g\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Asus\Desktop\Project A\project-g\node_modules\express\lib\router\index.js:323:13)
    at C:\Users\Asus\Desktop\Project A\project-g\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\Asus\Desktop\Project A\project-g\node_modules\express\lib\router\index.js:341:12)     
    at next (C:\Users\Asus\Desktop\Project A\project-g\node_modules\express\lib\router\index.js:275:10)
    at logger (C:\Users\Asus\Desktop\Project A\project-g\node_modules\morgan\index.js:144:5) {
  expected: 418800,
  length: 418800,
  limit: 102400,
  type: 'entity.too.large'
}
`
My image is not that large. So, it's probably not because of image size.
I am only getting this error while uploading the image using camera component of form builder.
I tried uploading the same image using postman and it's working just fine.
Any idea why that might be happening?
Thanks.

**Comment by Kiho** [comment]
I can't find any issue  up to 8 MB with this test server setup - https://github.com/Kiho/react-form-builder/blob/master/server/api/form.js
Maybe you can try these solutions https://stackoverflow.com/questions/19917401/error-request-entity-too-large

**Comment by kart1ka** [comment]
Thank You. I solved the previous error.
I seem to have encountered another problem with Camera component. The uploading of the image works fine. But when I try to render the form, the image is not getting rendered in the Camera component.
Please see the attached screenshots:
Uploading of image using Camera component - 
![image](https://user-images.githubusercontent.com/41051387/168484953-90493768-54b6-432e-9527-6ba265e9cc5d.png)

Rendering of Image using Camera component - 
![image](https://user-images.githubusercontent.com/41051387/168484979-5c9ec02b-79ea-418f-a0d4-9fcda1a43f9f.png)

Can you please help me out?
Thanks.

**Comment by Kiho** [comment]
You need to make uploaded file publicly available and update field content point to URL of uploaded image https://github.com/Kiho/react-form-builder/blob/master/server/api/form.js#L45 
The code provide here is simple example, you should develop better file management system for production.

**Comment by kart1ka** [comment]
The image being displayed on the Camera component is too big in dimensions (width and height). It is messing with my page layout. Can you please add a way to specify the width and height properties of the image in the edit section of the Camera field?
In the screenshot attached below the image is overflowing, as highlighted, in both vertical and horizontal direction. The original image, that I uploaded in the Camera component of the form, is not that big.

![Screenshot 2022-05-17 022400](https://user-images.githubusercontent.com/41051387/168681011-d2f51e74-dd7d-4da0-b57a-e3876b667ba9.jpg)


Also, The Camera component is only working with png images and not with jpg/jpeg. 
Can you please tell me why this is happening?
Thank You.

**Comment by Kiho** [comment]
You should be able to adjust image size by CSS.

**Comment by kart1ka** [comment]
I could do it with CSS. But I think it makes more sense that the user who is creating the form is allowed to decide the width and height of the Image being displayed by the Camera component in Form Render. Can you please modify the form-elements-edit file to show width and height inputs, just like in the Image component below?


![Screenshot 2022-05-19 003320](https://user-images.githubusercontent.com/41051387/169136154-1a549ecc-2d11-40eb-bfce-5232b93afb71.jpg)

Thank You.
