### ISSUE TITLE
Locating answer data

### ISSUE THREAD

**Issue by finnjefferis** [Kiho/react-form-builder#188]
Hi Kiho,

Can't find the answer data anywhere before it is sent off to the API. Is there any way to generate answer JSON and log it to the frontend?

Thanks again.

**Comment by Kiho** [comment]
If you uncomment this line https://github.com/Kiho/react-form-builder/blob/master/demobar.js#L108 then you can console.log in  
function _onSubmit(data), but data will not be posted to API.

**Comment by finnjefferis** [comment]
Owe you a beer at this rate.

Lifesaver
