### ISSUE TITLE
Cannot have two HTML5 backends at the same time

### ISSUE THREAD

**Issue by finnjefferis** [Kiho/react-form-builder#191]
Hi again,

Getting this error occasionally when I'm using the form builder in Next.JS. It doesn't happen every time and I'm struggling to find steps to reproduce this error.
![gitprob](https://user-images.githubusercontent.com/91462667/170045834-04502167-05c4-4c19-beaf-32925379ed87.PNG)

Does anyone know why this could be occurring?

Thanks,

**Comment by finnjefferis** [comment]
Error seems to occur only when I rename the 'placeholder text' on any element and then drag a new element onto the form

**Comment by Kiho** [comment]
I can't replicate issue.

**Comment by martybird01** [comment]
I am facing the same issue here as well.

**Comment by Kiho** [comment]
I can't debug without code showing the error. Someone here should post minimal github project showing error.

**Comment by rwsabhishek** [comment]
@Kiho My basic code setup step - 
1 - Create project using next js and react 18.0.2
2 - Create a page  and add below code-
import { ReactFormBuilder } from "react-form-builder2";
function FormBuild() {
 
  const postData = (e) => {
    console.log("POST DATA", e);
  };
  return <ReactFormBuilder show_description={true} onPost={postData} />;
}
export default FormBuild;

3 - Now this code can be execute by next js routes
4 - I try to drag drop and after sometime i faced the error

**Comment by Kiho** [comment]
React 18 is not supported now. you need to downgrade it to React 16 or 17.

**Comment by alexllllllll** [comment]
Hello!
react 17.0.1 didn't work, like 16.14.0

**Comment by Kiho** [comment]
This https://github.com/Kiho/react-form-builder/blob/master/examples/next/package.json#L28 example is working fine with react 17.
