### ISSUE TITLE
Rename Component / Add file types

### ISSUE THREAD

**Issue by fmoulton** [Kiho/react-form-builder#193]
How can we rename the Camera component and/or allow more file types to be selected?

**Comment by Kiho** [comment]
If you want different name than Camera than you have to build custom toolbox like this.
```js
const items = [{
  key: 'Header',
}, {
  key: 'TextInput',
}, {
  key: 'Camera',
  name: 'Camera A',
  icon: 'fas fa-camera',
  label: 'Camera Place Holder',
  field_name: 'camera_',
}];
```
Then use it in form-builder
```js
<ReactFormBuilder
    ....
    toolbarItems={items}
/>
```
Camera component does not support files other than image types.

**Comment by Kiho** [comment]
New FileUpload  component should cover this issue.
