### ISSUE TITLE
File attachment

### ISSUE THREAD

**Issue by wongtaozhe123** [Kiho/react-form-builder#198]
I've had a great experience using this and this helps us a lot, everything is great besides this small issue here:

The current file attachment only allow us to upload a url link, is it possible to make it upload locally?

**Comment by Kiho** [comment]
Sorry, but I don't understand your issue. it uploads file to test server fine, it just not accepting file if file type is not allowed.
https://github.com/Kiho/react-form-builder/blob/master/server/api/form.js#L50
