### ISSUE TITLE
File Input Download

### ISSUE THREAD

**Issue by fmoulton** [Kiho/react-form-builder#199]
Hi,

So I am taking the file upload component and offloading the file to s3 then returning the url as that inputs value.

here: https://github.com/Kiho/react-form-builder/blob/master/src/form-elements/index.jsx#L675

is causing a failure on split as this is just a direct url to the file. Is there a way around this so the download file can just display the full url as a link in read mode?

**Comment by Kiho** [comment]
It's not best but I think v0.12.1 should work, You can make PR if you have better idea.

**Comment by fmoulton** [comment]
works @Kiho 👍
