### ISSUE TITLE
Demo to use in my application

### ISSUE THREAD

**Issue by abhisheksdm** [Kiho/react-form-builder#2]
Hello Kiho, 
First of all, thanks for giving us updated react-form-builder with mitigation of jquery :)
I am new to reactjs and able to run this demo by git clone, but i am unable to use this npm package 'react-form-builder2' in my application, Please give me the link for documentation to use it in my application or please make a dummy app that uses this package. i will really appreciate your help
Thanks in Advance
getting this error. 
![image](https://user-images.githubusercontent.com/32297964/44325172-9ef84600-a475-11e8-8cce-b32cfcbea7a2.png)

**Comment by Kiho** [comment]
Hi @abhisheksdm 
I will look into the issue when time permits, it might take couple of weeks.

**Comment by Kiho** [comment]
Hi @abhisheksdm 

Check example in this branch https://github.com/Kiho/react-form-builder/tree/npm/examples

**Comment by Kiho** [comment]
It's been merged to master
