### ISSUE TITLE
cannot load answer data

### ISSUE THREAD

**Issue by allen391** [Kiho/react-form-builder#202]
Hi Kiho,

Very nice form builder library for using. However, I found the answer data rendering doesn't work properly. It indeed works for the first-page render, but after refreshing, the answer data is lost.

My code is as such:

      <ReactFormGenerator
        back_action="/formBuilder"
        answer_data={data.formData}
        data={formTemplate}
        hide_actions={true}
        read_only={true}
      />

the answer data is stored in the state. It only works for the initial state rendering. Can u check it? Much appreciated!

**Comment by Kiho** [comment]
There is no structure to persist answer data in form-generator. Unfortunate but you need to implement it by yourself.
Something like this maybe... 
https://github.com/pratapshiv1992/react-hooks-express-mongodb-crud
