### ISSUE TITLE
Cannot have two HTML5 backends at the same time

### ISSUE THREAD

**Issue by ingalesachin7** [Kiho/react-form-builder#206]
Form generator 
passing the below data  
` <ReactFormBuilder variables={variables}
        edit
        key={nanoid()} 
        data={form} 
        toolbarItems={items}
       saveUrl="saveform"
       renderEditForm={props => <FormElementsEdit {...props}/>}
    />
`
It loading the data in form, but when we edit the field and then try to drag the header page goes blank
console showing that "Cannot have two HTML5 backends at the same time"
when i remove the key then it working fine but then  data is not populating

Can anyone help me with this issue?

**Comment by Kiho** [comment]
I can't understand error without seeing the code.
If you need help then please create github repo with reproducing the error.

**Comment by ingalesachin7** [comment]
`import { DndProvider } from 'react-dnd';
import { HTML5Backend } from 'react-dnd-html5-backend';
import { IntlProvider } from 'react-intl';`
import FormElementsEdit from './form-elements-edit';
import AppLocale from './language-provider';

Imported above and adding ReactFormBuilder  between them gets working

**Comment by rwsabhishek** [comment]
Hello @ingalesachin7 ,
I am also facing the same issue.As you recently told that your issue is resolved.
Can you provide me the sample code for the issue to resolved means how did you add ReactFormBuilder between other imported component?

**Comment by ingalesachin7** [comment]
`
import AppLocale from './language-provider';
import { DndProvider } from 'react-dnd';
import { HTML5Backend } from 'react-dnd-html5-backend';
import { IntlProvider } from 'react-intl';


<DndProvider backend={HTML5Backend}>
        <IntlProvider
          locale={currentAppLocale.locale}
          messages={currentAppLocale.messages}>
  <div>
   
          <ReactFormBuilder 
       variables={variables}
     
        key={nanoid()} 
        data={form} 
     
        toolbarItems={items}
      
       onPost={handleSubmit}
  
       renderEditForm={props => <FormElementsEdit {...props}/>}
       
    /> 
     </div>
     </IntlProvider>
      </DndProvider>

`
@rwsabhishek Hope it may help you

**Comment by harshajayaweeraXHJ** [comment]
> ` import AppLocale from './language-provider'; import { DndProvider } from 'react-dnd'; import { HTML5Backend } from 'react-dnd-html5-backend'; import { IntlProvider } from 'react-intl';
> 
> ```
>       <ReactFormBuilder 
>    variables={variables}
>  
>     key={nanoid()} 
>     data={form} 
>  
>     toolbarItems={items}
>   
>    onPost={handleSubmit}
> 
>    renderEditForm={props => <FormElementsEdit {...props}/>}
>    
> /> 
>  </div>
>  </IntlProvider>
>   </DndProvider>
> ```
> 
> ` @rwsabhishek Hope it may help you

Fantastic! This was the only solution which worked for me. Wrap the `ReactFormBuilder` component itself with `DnDProvider`
Thanks
