### ISSUE TITLE
signature is now showing in edit mode

### ISSUE THREAD

**Issue by bhupesh-sf** [Kiho/react-form-builder#21]
I have used signature component in the form. It renders properly and when I am successfully able to save the form as well. But when I open the same form in edit mode it throws an exception as follows:

`canvas.fromDataURL is not a function`

Data which was saved successfully reaches to this function but still it throws this exception. Can you please check this issue out?

**Comment by bhupesh-sf** [comment]
@Kiho When opening a form in edit mode, it does show signatures now but I am not able to update the signatures. They are ready only. Is there any way that I can give the option to reset the signatures and fill it again?

**Comment by Kiho** [comment]
You need to clear defaultValue property, it should turn in to edit mode.

**Comment by bhupesh-sf** [comment]
@Kiho When filling the form for the first time also if I have filled a signature, I can't change it (I am talking even before submitting the form). I believe there should be a reset button available with the signature component which will simply clear the existing value of signature field.

Amy thoughts?

**Comment by bhupesh-sf** [comment]
@Kiho Thanks for your update. Its working for edit mode but in create mode also I should be able to change my signature which is missing.

**Comment by bhupesh-sf** [comment]
@Kiho In edit mode if don't update signature and try to submit form its giving me following error

`Uncaught TypeError: Cannot read property 'toDataURL' of null
    at ReactForm._getSignatureImg (form.js?4786:189)
    at eval (form.js?4786:237)
    at Array.forEach (<anonymous>)
    at ReactForm.validateForm (form.js?4786:235)
    at ReactForm.handleSubmit (form.js?4786:204)
    at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:100)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?61bb:138)
    at Object.invokeGuardedCallback (react-dom.development.js?61bb:187)
    at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.development.js?61bb:201)`

If reset the signature then it allow me to submit the form. It has become mandatory to update the signature in edit mode. And as per my previous comment in while add form I don't have the option to update/reset the signature as well.

**Comment by Kiho** [comment]
I can't reproduce your problem. can you post your code?

**Comment by bhupesh-sf** [comment]
@Kiho I face this issue in edit mode. I am attaching my code file which is quite lengthy, but I am not doing anyting fancy there. You can still give it a try to see if some of my code is creating the issue. 

Another thing in add form also I should be able to erase and change my signature. Reset button is available only in edit mode not in add mode.

It doesn't allow to upload .JS files, so I have changed the extension to pdf. Please change it back to JS and see it.

[FormGenerator.pdf](https://github.com/Kiho/react-form-builder/files/2905669/FormGenerator.pdf)

**Comment by bhupesh-sf** [comment]
My scenario is I have opened the form in edit mode and trying to resubmit it without doing anything to signature field. If I reset and update signature then it works fine.

**Comment by Kiho** [comment]
@bhupesh-sf It's to hard to adjust your code to test myself. I just fix the code based on your trace.
It will be much easier to debug if you can provide fork of this repository showing your problem.

**Comment by bhupesh-sf** [comment]
@Kiho It fixed the issue. Now it all working fine. Thanks.
