### ISSUE TITLE
Other Dropdown

### ISSUE THREAD

**Issue by fmoulton** [Kiho/react-form-builder#215]
@Kiho before I add a PR for this, would you accept a feature to add a text input if a user selects other from a dropdown? Any requirements you would like to see on that feature? If no specifics just let me know yes/no and I will get a PR in for that feature. Thanks!

**Comment by JasonColeyNZ** [comment]
I think this really needs to be a conditional type rule process. As other form builders can do, other controls visibility/disabled controlled by values on other controls. But the author has stated somewhere he has no plans to build such a feature. Pity as this would certainly be a great feature

**Comment by Kiho** [comment]
@fmoulton Sorry about late reply, it is up to you to decide to do PR or not. If you are not willing to do then please close this issue.

**Comment by Kiho** [comment]
@JasonColeyNZ I don't know any open source free form builder has function of conditional type rule process. if you know any then let me know, I like to take a look.
