### ISSUE TITLE
Range - visible marks.

### ISSUE THREAD

**Issue by veselinovicdevelopment** [Kiho/react-form-builder#218]
Hey
I think react-form-builder is a great library, but I found issue while I am using it.
Visible marks on range slider does not work properly.
I debug the node_module and found that props.min_value and props.max_value is not defined.
Please check this screenshot.
![image](https://user-images.githubusercontent.com/94121507/192443747-2f624333-1249-4cc2-9298-7cc77070e8c6.png)

Here data list is always empty.
Please check toolbar item for Range too.
![image](https://user-images.githubusercontent.com/94121507/192443891-af53e250-b3d7-4e27-8e89-629d68cd45c1.png)

Please let me know if you fix  this issue.
Thank you.

**Comment by Kiho** [comment]
Fixed
