### ISSUE TITLE
Pointer in slider in Range does not update when I change value.

### ISSUE THREAD

**Issue by veselinovicdevelopment** [Kiho/react-form-builder#219]
Hey.
As I test Range item, I found that pointer in the slider does not update according to the value.
Here is the screenshot.
![image](https://user-images.githubusercontent.com/94121507/192444610-d6b41a95-b934-4226-922b-2da17478b1e3.png)
But if I preview the form, I could see the changes.

**Comment by Kiho** [comment]
This can't be fixed in easy way.
