### ISSUE TITLE
editor in form edit elements is not working

### ISSUE THREAD

**Issue by kart1ka** [Kiho/react-form-builder#222]
Hey Kiho.
I was editing form elements' label and content in the form edit component of rfb and found that if I try to change the size or apply other properties such as bold, italic etc on the labels it looks fine in the form genrator component but when I view the same form in the form render component it does not work. I have attached the screenshot below:

1. Form Generator component:
![Screenshot 2022-10-05 170750](https://user-images.githubusercontent.com/41051387/194053531-e62a1ba1-91e5-4a61-be8b-d94561d22215.png)

2. Form Render component:
![Screenshot 2022-10-05 170145](https://user-images.githubusercontent.com/41051387/194053577-3b59fdff-584b-4888-b17f-a307aec10394.png)

Can you see why this is happening?
Thanks.

**Comment by Kiho** [comment]
I am not sure what is your issue, I can't replicate problem in my setup. what version of `react-draft-wysiwyg` you are using?
If it's not 1.14.7 then that might be the issue.

**Comment by ShivkumarSalunkhe** [comment]
Can you please share repo link of latest react form builder i want to use it in my project urjnt please 🥺
