### ISSUE TITLE
JQuery Depedency

### ISSUE THREAD

**Issue by robertkemp77** [Kiho/react-form-builder#225]
Hello,

This looks amazing, but I am trying to stay away from using jQuery.  I'm getting a dependency error when installing (below).  Is there a way around it?

ERROR in ./node_modules/bootstrap-slider/dist/bootstrap-slider.js

Module not found: Error: Can't resolve 'jquery' in 'C:.....'  

Thanks in advance
Rob

**Comment by Kiho** [comment]
You can follow instruction here https://github.com/seiyria/bootstrap-slider#webpack

**Comment by robertkemp77** [comment]
One more question.  Is this working with 
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
