### ISSUE TITLE
Date picker console warnings when opening the form in read only

### ISSUE THREAD

**Issue by bhupesh-sf** [Kiho/react-form-builder#23]
When a open a form in read only mode I get couple of following warnings in console:

`Warning: Invalid DOM property `readonly`. Did you mean `readOnly`?
    in input (created by DatePicker)
    in div (created by DatePicker)
    in div (created by DatePicker)
    in div (created by DatePicker)
    in DatePicker (created by Card)
    in div (created by Card)
    in Card (created by DropTarget(Card))
    in DropTarget(Card) (created by DragSource(DropTarget(Card)))
    in DragSource(DropTarget(Card)) (created by Preview)
    in div (created by Preview)
    in div (created by Preview)
    in Preview (created by ReactFormBuilder)
    in div (created by ReactFormBuilder)
    in div (created by ReactFormBuilder)
    in div (created by ReactFormBuilder)
    in ReactFormBuilder (created by DragDropContext(ReactFormBuilder))
    in DragDropContext(ReactFormBuilder)`

Another one is:

`Warning: Failed prop type: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
    in input (created by DatePicker)
    in div (created by DatePicker)
    in div (created by DatePicker)
    in div (created by DatePicker)
    in DatePicker (created by ReactForm)
    in form (created by ReactForm)
    in div (created by ReactForm)
    in div (created by ReactForm)
    in ReactForm (created by Demobar)
    in div (created by Demobar)
    in div (created by Demobar)
    in div (created by Demobar)
    in div (created by Demobar)
    in Demobar`

One more is:

`react-dom.development.js:506 Warning: A component is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components
    in input (created by DatePicker)
    in div (created by DatePicker)
    in div (created by DatePicker)
    in div (created by DatePicker)
    in DatePicker (created by Card)
    in div (created by Card)
    in Card (created by DropTarget(Card))
    in DropTarget(Card) (created by DragSource(DropTarget(Card)))
    in DragSource(DropTarget(Card)) (created by Preview)
    in div (created by Preview)
    in div (created by Preview)
    in Preview (created by ReactFormBuilder)
    in div (created by ReactFormBuilder)
    in div (created by ReactFormBuilder)
    in div (created by ReactFormBuilder)
    in ReactFormBuilder (created by DragDropContext(ReactFormBuilder))
    in DragDropContext(ReactFormBuilder)`

**Comment by Kiho** [comment]
First issue should be fixed now, @bhupesh-sf can you explain how I can reproduce warnings item 2 & 3?

**Comment by bhupesh-sf** [comment]
@Kiho Other 2 warnings also disappeared along with the first one. Thanks
