### ISSUE TITLE
toolbar - canHavepageBreakBefore

### ISSUE THREAD

**Issue by gayathrig321** [Kiho/react-form-builder#231]
Hi found this link  ( https://github.com/Kiho/react-form-builder/tree/hide-column } one of your reply ( https://github.com/Kiho/react-form-builder/issues/37#top ), its dead now. could you please provide active link. I need to hide some component on edit. Thanks in advance !

**Comment by Kiho** [comment]
That branch was merged (https://github.com/Kiho/react-form-builder/pull/38), maybe your problem is just typo, it should be `canHavePageBreakBefore`

**Comment by gayathrig321** [comment]
Hi Thanks for response, where can I see sample object of toolbarItems

**Comment by Kiho** [comment]
https://github.com/Kiho/react-form-builder/pull/38/files
