### ISSUE TITLE
Elements Deleting when dragging 

### ISSUE THREAD

**Issue by Sandlee09** [Kiho/react-form-builder#232]
Has anyone dealt with this issue? When I drag a couple of items into the builder sometimes it begins to overwrite certain items. For Example I drag 1 text input and 1 email input and then try to drag a dropdown, sometimes the dropdown will overwrite the email input and delete it while adding the dropdown.

**Comment by farid-ansari** [comment]
Yes, I'm facing this issue as well. I've yet to come across a fix for this issue. @Kiho

**Comment by Sandlee09** [comment]
@farid-ansari @Kiho , solved it, by changing these functions 

![image](https://user-images.githubusercontent.com/20055278/198334415-dec365a6-6d56-4e8e-9906-9f4c7a361f1f.png)
