### ISSUE TITLE
How to save data from a custom component

### ISSUE THREAD

**Issue by Sandlee09** [Kiho/react-form-builder#233]
Anyone know how to save the input's data from a custom component

I added a custom component and its taking in the props correctly but I don't know how to safve the data, it simply never saves the data like other built in inputs do.

**Comment by Kiho** [comment]
There is example of custom component https://github.com/Kiho/react-form-builder/blob/master/examples/custom/app.js#L14
```jsx
const MyInput = React.forwardRef((props, ref) => {
  const { name, defaultValue, disabled } = props;
  return <input ref={ref} name={name} defaultValue={defaultValue} disabled={disabled} />;
});
```
Your custom component should have input element with ref associated with it.
