### ISSUE TITLE
Center in edit form view doesn't work for an Image

### ISSUE THREAD

**Issue by ItaiBolyasni25** [Kiho/react-form-builder#234]
Hi @Kiho, love all the work you are doing this library is amazing.
I was playing around with images and noticed that the center option in the edit form for an Image isn't working.

![image](https://user-images.githubusercontent.com/31418448/200973462-69cc0a79-ed55-4f5a-ad02-39528ca9ab45.png)

I am able to repro it on the demo website. Could you have a look whenever you have a spare moment.
Thank you :)

**Comment by Kiho** [comment]
It should fixed in new version from NPM.
