### ISSUE TITLE
Previous auto added element not removed when dropping into multi-column row

### ISSUE THREAD

**Issue by ammargitham** [Kiho/react-form-builder#235]
This happens when we have a multi-column row in our form builder.

When we try to drag another element into one of the columns of the row, there is chance that we hover over the blank space below the multi-column row. This auto adds the dragging element into our form. When we drop the dragging element into the column, we are left with duplicated elements in our form.

The expected behavior would be that the auto added element below is removed when the element is dropped into the row column.

[Video demonstrating the issue](https://imgur.com/a/YhAnDCn)

**Comment by Kiho** [comment]
I know it is annoying but it is really hard to fix.
Try https://github.com/Kiho/react-form-builder/tree/issue-235 branch and let me know if it is not working.

**Comment by ammargitham** [comment]
Yes, seems to be fixed on the branch.

**Comment by ammargitham** [comment]
@Kiho Any idea when you will be releasing this fix?

**Comment by Kiho** [comment]
It is published.
