### ISSUE TITLE
Camera file is empty

### ISSUE THREAD

**Issue by alexiskattan** [Kiho/react-form-builder#239]
Am looking for where the image file is so that I can upload it to s3.  

ReactFormGenerator looks like this
```
      <ReactFormGenerator
          onSubmit={onSubmit}
          data={schema}
          // @ts-ignore
          submitButton={<button type="submit" className="db_button">Submit</button>}
      />
    </>
```

then 

```
function onSubmit(formData) {
  console.log("onSubmit")
  console.log(formData)
}
```

However, in the formData, I can't seem to find the actual file that has been uploaded.  It has everthing else like the size, name, and date of the file.

Where should I be looking for it?

PS: I'm using 0.13.2 becuase of an issue with `window` but I tested it with current version in a vanilla project and had the same issue.

**Comment by Kiho** [comment]
The value of field contains File object, everything should be there.
You can try convert it to base64 format like this.

```js
function getBase64(file) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => resolve(reader.result);
    reader.onerror = error => reject(error);
  });
}
```
```js
  async _onSubmit(data) {
    console.log('onSubmit', data);
    // I assume first field is Camera
    const fileData = await getBase64(data[0].value);
    console.log('onSubmit', fileData);
  }
```

**Comment by alexiskattan** [comment]
Thank you that worked.  `reader.readAsDataURL(file)` was the key that I was missing.

I was looking at data and saw.  Didnt know about the `.value` and `reader` part
```{
   lastModified:  1644750842682
   lastModifiedDate:  Sun yyy {}
   name:  "xyz.png"
   size: 22041
   type: "image/png"
   webkitRelativePath: ""
}```

Thank you!
