### ISSUE TITLE
Failed to run Demo when clone the project from github

### ISSUE THREAD

**Issue by ntt2k** [Kiho/react-form-builder#24]
Hi Team,

I'm using Node v10 LTS, when first clone the project from github into my local machine and doing "npm install", I got the following errors:

> ERROR in ./node_modules/react-bootstrap-slider/dist/react-bootstrap-slider.js
Module not found: Error: Can't resolve '/Users/michaelbrown/Development/react-bootstrap-slider/node_modules/@babel/runtime/helpers/esm/assertThisInitialized' in '/Users/ntt2k/hobby_projects/react-form-builder/node_modules/react-bootstrap-slider/dist'
 @ ./node_modules/react-bootstrap-slider/dist/react-bootstrap-slider.js 20:53-180
 @ ./src/form-elements.jsx
 @ ./src/form.jsx
 @ ./src/index.jsx

> ERROR in ./node_modules/react-bootstrap-slider/dist/react-bootstrap-slider.js
Module not found: Error: Can't resolve '/Users/michaelbrown/Development/react-bootstrap-slider/node_modules/@babel/runtime/helpers/esm/classCallCheck' in '/Users/ntt2k/hobby_projects/react-form-builder/node_modules/react-bootstrap-slider/dist'
 @ ./node_modules/react-bootstrap-slider/dist/react-bootstrap-slider.js 12:46-166
 @ ./src/form-elements.jsx
 @ ./src/form.jsx
 @ ./src/index.jsx

![screen shot 2019-02-23 at 8 15 57 am](https://user-images.githubusercontent.com/4227421/53287539-461aaa80-3743-11e9-862a-937f2eab062e.png)

Please help?

**Comment by ntt2k** [comment]
It seems that I figured it out, new version of "react-bootstrap-slider" is incompatible with "react-form-builder2"

"react-bootstrap-slider": "2.1.5"

**Comment by Kiho** [comment]
I need more investigation on this, but it seems to be workable solution for now.

**Comment by Kiho** [comment]
https://github.com/brownieboy/react-bootstrap-slider/commit/ff201116237b01c17f24941559f88e824fe1cb18
