### ISSUE TITLE
Updating custom Element using props Issue

### ISSUE THREAD

**Issue by ashwinimiri** [Kiho/react-form-builder#242]
hey i am using custom Component for Address, where i pass data using props property in toolbar Items, then i update the same using my custom editor. but it will reflect to the another instance of the Address.

![Untitled design](https://user-images.githubusercontent.com/67318508/208602022-d5f765ff-b064-4029-9516-0b26f86363bb.png)

**Comment by ShivkumarSalunkhe** [comment]
Can you please share repo link of latest react form builder i want to use it in my project urjnt please 🥺

**Comment by Kiho** [comment]
Can't reproduce issue.
