### ISSUE TITLE
In my application preview/ submit/ save button is not visible pls help 

### ISSUE THREAD

**Issue by ShivkumarSalunkhe** [Kiho/react-form-builder#245]
### In my application preview/ submit/ save button is not visible  ### 
![Screenshot 2023-01-20 225018](https://user-images.githubusercontent.com/105507602/213763363-3482ff7a-42a6-4099-a398-b9ac4b664ed5.png)

**Comment by ShivkumarSalunkhe** [comment]
I tried this too can you please help me with providing repository link that will have all things in on place please it's very much important for me to build form also there is no comparative npm package like this so can you pls update with preview and save button or provide me repo link please 🥺

**Comment by anthony-sap** [comment]
I have the same issue, that line of code you'velinked too dones't show any components. 

I'm unable to see my buttons

`<ReactFormBuilder
        actionName="Set this to change the default submit button text"
        submitButton={
          <button type="submit" className="btn btn-primary">
            Submit
          </button>
        }
        backButton={
          <a href="/" className="btn btn-default btn-cancel btn-big">
            Back
          </a>
        }
        action_name="Save"
        hide_actions={true}
        onPost={onPost}
        toolbarItems={items}
      />`

**Comment by Kiho** [comment]
There are  ReactFormBuilder & ReactFormGenerator components, submitButton & backButton properties are applicable to ReactFormGenerator only.

**Comment by anthony-sap** [comment]
Ok, So the FormBuilder doesn't have a save button as is posts changes as they occur within editor.

**Comment by Kiho** [comment]
Yes, it will post anytime you make changes. However, if you don't like that then set saveAlways property to false and post changes manually.
https://github.com/Kiho/react-form-builder/blob/master/docs/form-builder.js#L23
https://github.com/Kiho/react-form-builder/blob/master/docs/form-generator.js#L43
