### ISSUE TITLE
React v18 support

### ISSUE THREAD

**Issue by hasanablak** [Kiho/react-form-builder#247]
How can I use this project in my project with React 18 installed?

"@reduxjs/toolkit": "^1.9.1",
		"axios": "^1.2.3",
		"bootstrap": "^5.2.3",
		"i18next": "^22.4.9",
		"i18next-browser-languagedetector": "^7.0.1",
		"i18next-chained-backend": "^4.2.0",
		"i18next-fetch-backend": "^5.0.2",
		"i18next-http-backend": "^2.1.1",
		"i18next-redux-languagedetector": "^1.1.0",
		"jwt-decode": "^3.1.2",
		"moment": "^2.29.4",
		**"react": "^18.2.0",**
		"react-bootstrap": "^2.7.0",
		"react-content-loader": "^6.2.0",
		"react-datepicker": "^4.10.0",
		**"react-dom": "^18.2.0",**
		"react-form-builder2": "^0.14.2",
		"react-helmet": "^6.1.0",
		"react-i18next": "^12.1.5",
		"react-redux": "^8.0.5",
		"react-router-dom": "^6.6.2",
		"react-select": "^5.4.0",
		"react-time-picker": "^5.2.0",
		"styled-components": "^5.3.6",
		"sweetalert2": "^11.7.0",
		"translation-check": "^1.0.2",
		"vite-aliases": "^0.10.0"

**Comment by Kiho** [comment]
I am not sure what is your problem, this demo project works OK to me.
https://github.com/Kiho/react-form-builder/tree/master/examples/demo
