### ISSUE TITLE
Edit form elements 

### ISSUE THREAD

**Issue by ShivkumarSalunkhe** [Kiho/react-form-builder#249]
From should be edit with previous data. When we try to edit previous data is prefilled in preview modal but elements are not showing in drag zone 

please find attached pic and if anyone is using this kind of functionality pls put repo link here
![Screenshot_20230207_230413](https://user-images.githubusercontent.com/105507602/222975144-685f3398-8254-4a89-a6d5-bb92a39462bb.png)

its showing empty data in drop zone 

![image](https://user-images.githubusercontent.com/105507602/222975913-f558cbfb-1148-40a4-99d4-173218b8fa2a.png)

**Comment by Kushal0891** [comment]
@ShivkumarSalunkhe  is this fixed ? areu able to prepopulate the data in dropzone
