### ISSUE TITLE
Need a Time picker component for Form builder

### ISSUE THREAD

**Issue by bhupesh-sf** [Kiho/react-form-builder#25]
We have a date picker component available in Form Builder but not the time picker. If you don't have time can you simply guide so I may create one?

**Comment by Kiho** [comment]
I implemented time part of react-datepicker, check this https://github.com/Kiho/react-form-builder/tree/datetime out and let me know if you find any issues. or you can fix it.

**Comment by bhupesh-sf** [comment]
I just checked and seems fine. Please publish it on NPM. I will integrate it with my project and fully test it there. If found any issue will let you know. Thanks.

**Comment by bhupesh-sf** [comment]
@Kiho It working perfectly fine on our end. Thanks for such a quick update
