### ISSUE TITLE
types clarification 

### ISSUE THREAD

**Issue by mikewongblinx** [Kiho/react-form-builder#250]
base on type definition. `renderEditForm` function  first argument should be `BaseElement`. However follow codebase we are passing `formElementEditProps` (ie an object contains baseElement and other function helper like updateElement.). We need clarifying it as it make typescript complaining  
![image](https://user-images.githubusercontent.com/85168171/223073839-2378acd6-c52c-4c9f-9b18-a8a554e4d5be.png)

**Comment by Kiho** [comment]
You are right, it should to be fixed.
