### ISSUE TITLE
onChange in ReactFormGenerator

### ISSUE THREAD

**Issue by herbnspice** [Kiho/react-form-builder#251]
Hi @Kiho this library is awesome !
Would like to ask if is there a way to add a onChange in ReactFormGenerator that monitors and get the states of the form answers
Any help would be great.

**Thank you**

**Comment by Kiho** [comment]
Unfortunately onChange event handler is wired internally. Anyway it does not needed for most of use case IMHO.
If you want to implement it in fork then you can try it by yourself.
Add handler in form.js
```js
  handleChange = (evt) => {
    console.log('handleChange', evt);
    this.props.onChange && this.props.onChange(evt);
  }
```
And add handler to all of input elements, this example is for TextArea
```js
class TextArea extends React.Component {
  constructor(props) {
    super(props);
    this.inputField = React.createRef();
  }

  render() {
    const props = {};
    props.className = 'form-control';
    props.name = this.props.data.field_name;
    props.onChange = this.props.handleChange;

    if (this.props.read_only) {
      props.disabled = 'disabled';
    }

    if (this.props.mutable) {
      props.defaultValue = this.props.defaultValue;
      props.ref = this.inputField;
      props.onChange = this.props.handleChange;
    }

....

}
```

**Comment by herbnspice** [comment]
> Unfortunately onChange event handler is not wired internally. Anyway it does not needed for most of use case IMHO. If you want to implement it in fork then you can try it by yourself. Add handler in form.js
> 
> ```js
>   handleChange = (evt) => {
>     console.log('handleChange', evt);
>     this.props.onChange && this.props.onChange(evt);
>   }
> ```
> 
> And add handler to all of input elements, this example is for TextArea
> 
> ```js
> class TextArea extends React.Component {
>   constructor(props) {
>     super(props);
>     this.inputField = React.createRef();
>   }
> 
>   render() {
>     const props = {};
>     props.className = 'form-control';
>     props.name = this.props.data.field_name;
>     props.onChange = this.props.handleChange;
> 
>     if (this.props.read_only) {
>       props.disabled = 'disabled';
>     }
> 
>     if (this.props.mutable) {
>       props.defaultValue = this.props.defaultValue;
>       props.ref = this.inputField;
>       props.onChange = this.props.handleChange;
>     }
> 
> ....
> 
> }
> ```

Thanks @Kiho works,  I will just need to create custom input elements that handle onChange events.
