### ISSUE TITLE
Camera element not working with PNG files

### ISSUE THREAD

**Issue by cometfish** [Kiho/react-form-builder#254]
Hi, uploading JPG and GIF works with the default Camera component, but PNGs fail. They seem to be missing the "data:image/png;base64," part from the src when rendered on the page.

I noticed the following lines which seem to be specific to PNGs:
[../blob/master/src/form-elements/index.jsx line 651](../blob/master/src/form-elements/index.jsx#L651)
```
      if (this.props.defaultValue.indexOf(name > -1)) {
        sourceDataURL = this.props.defaultValue;
      } else {
        sourceDataURL = `data:image/png;base64,${this.props.defaultValue}`;
      }
```
Is the `indexOf` end bracket in the first line in the wrong spot?
```
      if (this.props.defaultValue.indexOf(name) > -1) {
```

I'm not very familiar with React, so I am not sure how to test a change to the source code (my project just pulls the built version from npm) - so I don't know if this will actually help with the PNG issue!

**Comment by Kiho** [comment]
I have no problem with uploading PNG file. not sure why you are facing problem.

**Comment by cometfish** [comment]
Hi @Kiho, this is what I am seeing when viewing the completed form with `read_only=true` set, with a PNG upload:
![image](https://user-images.githubusercontent.com/19256498/226487615-4d0ef097-69c1-46f6-a137-bfa98c399b3c.png)
The correct data is there in the `src`, but it's missing the "data:image/png;base64," part.

I'm using Chrome on Windows, and the sample PNG image from here: https://sample-videos.com/img/Sample-png-image-200kb.png

**Comment by Kiho** [comment]
Can you try this in the place?
```js
      if (this.props.defaultValue.length < 1000 || this.props.defaultValue.indexOf(name > -1)) {
        sourceDataURL = this.props.defaultValue;
      } else {
        sourceDataURL = `data:image/png;base64,${this.props.defaultValue}`;
      }
```

**Comment by cometfish** [comment]
Thanks Kiho - I ended up changing quite a bit of the code (because I wanted to show the existing image if the page was reloaded), which as a side effect means I'm no longer experiencing this issue.

So I'll close this issue, but for reference, I replaced the initial upload value of `blob:http://localhost:3000/blah-blah` with an instant conversion to a source data string instead, then just checked: `this.props.defaultValue.indexOf('data:')` in that section of code.
