### ISSUE TITLE
How to use same element 2 times 

### ISSUE THREAD

**Issue by ShivkumarSalunkhe** [Kiho/react-form-builder#256]
I am using range element I want to use same range element for different purpose, also I want to customize the range editor drawer, I have passed key prop as range in toolbaritems  but it is saying range is already used/registered  

pls respond

**Comment by Kiho** [comment]
You can do it like settings below with latest version v.0.15.0.
```js
  {
    key: 'Range',
    element: 'Range',
    name: 'Range 1',
    icon: 'fas fa-sliders-h',
    label: 'place-holder-label',
    field_name: 'range_',
    step: 1,
    default_value: 3,
    min_value: 1,
    max_value: 5,
    min_label: 'easy',
    max_label: 'difficult',
  },
  {
    key: 'Range2',
    element: 'Range',
    name: 'Range 2',
    icon: 'fas fa-sliders-h',
    label: 'place-holder-label',
    field_name: 'range2_',
    step: 1,
    default_value: 3,
    min_value: 1,
    max_value: 10,
    min_label: 'easy',
    max_label: 'difficult',
  },
```

**Comment by ShivkumarSalunkhe** [comment]
I am tired above code but Problem is 1) I am not able to access the edit drawer (side bar) for range -2 element able to access only for range-1 element.  

![Screenshot 2023-05-08 121111](https://user-images.githubusercontent.com/105507602/236753892-37b600d7-5641-4ea0-9ff9-3df929158fc4.png)
![Screenshot 2023-05-08 121126](https://user-images.githubusercontent.com/105507602/236754089-f473d01d-8be4-4e1a-bf14-df743ebf2784.png)

2) I want to customize both drawers for eg:- 2.1 I want to change labels min max to min value max value  2.2 Hide step input field.
![image](https://user-images.githubusercontent.com/105507602/236754978-d136a473-4e44-48c5-aab5-69654adfe53e.png)


Please respond
