### ISSUE TITLE
invalid phone no error showing.

### ISSUE THREAD

**Issue by aliyazahid** [Kiho/react-form-builder#259]
its really annoying that i am entering the correct phone no but still getting the invalid phone no error. i tried all the formats. can you please look into this 
![image](https://user-images.githubusercontent.com/82146877/234791168-2df1253a-bf81-4d99-b2ba-719bcfadf691.png)

**Comment by Kiho** [comment]
I can't find issue with this. it is using standard input control with tel type.

**Comment by aliyazahid** [comment]
I didn't do anything. I just use the toolbox item. and getting this error
on submitting the form. Can you please check the condition for this
validation? also tell me the number format you are entering

**Comment by Kiho** [comment]
Phone validation work with US only for now.
You can update regex here https://github.com/Kiho/react-form-builder/blob/master/src/form.jsx#L257 to match to your country.

**Comment by aliyazahid** [comment]
Ok thanks. I more thing i want to ask as i created form and if user upload
any file in file upload field how can i see its uploaded file? There is no
option to donwload its uploaded file

**Comment by Kiho** [comment]
You should run backend to upload and download file, also you can use Camera component to upload and show image.

**Comment by aliyazahid** [comment]
Ok, thanks.
