### ISSUE TITLE
No option to import image from device

### ISSUE THREAD

**Issue by aliyazahid** [Kiho/react-form-builder#260]
I am facing an issue in image Item. there is only option to add link url for image. but what if user wants to add their logo from his or her device. how can we achieve this. not every time they have live image url. please suggest me the solution its urgent
![image](https://user-images.githubusercontent.com/82146877/236180745-8e49cf2c-e705-4638-b10b-7d24720cbeb4.png)

**Comment by Kiho** [comment]
You can use Camera component for that.
