### ISSUE TITLE
Indent and outdent icons of html editor is not working

### ISSUE THREAD

**Issue by aliyazahid** [Kiho/react-form-builder#262]
two icons are not working Indent and outdent when i open edit form to edit the label of input field
![image](https://user-images.githubusercontent.com/82146877/236206888-32fe14f1-aac5-43b0-8230-38676d58a59a.png)

**Comment by aliyazahid** [comment]
Ok so now the version will update?

**Comment by Kiho** [comment]
It is done. v0.15.4 is available on NPM.

**Comment by aliyazahid** [comment]
Ok, thanks.
