### ISSUE TITLE
How to use same Range elements 2 times

### ISSUE THREAD

**Issue by ShivkumarSalunkhe** [Kiho/react-form-builder#263]
I am using range element I want to use same range element for different purpose, also I want to customize the range editor drawer, I have passed key prop as range in toolbaritems but it is saying range is already used/registered.

I am tired  [https://github.com/Kiho/react-form-builder/issues/256](https://github.com/Kiho/react-form-builder/issues/256) code but Problem is 1) I am not able to access the edit drawer (side bar) for range -2 element able to access only for range-1 element.  

![Screenshot 2023-05-08 121111](https://user-images.githubusercontent.com/105507602/236753892-37b600d7-5641-4ea0-9ff9-3df929158fc4.png)
![Screenshot 2023-05-08 121126](https://user-images.githubusercontent.com/105507602/236754089-f473d01d-8be4-4e1a-bf14-df743ebf2784.png)

2) I want to customize both drawers for eg:- 2.1 I want to change labels min max to min value max value  2.2 Hide step input field.
![image](https://user-images.githubusercontent.com/105507602/236754978-d136a473-4e44-48c5-aab5-69654adfe53e.png)

Please respond

**Comment by Kiho** [comment]
I will not support customizing edit dialog. you can try to change code here https://github.com/Kiho/react-form-builder/blob/master/src/form-elements-edit.jsx#L348 it should not be too hard.

**Comment by ShivkumarSalunkhe** [comment]
Okay it's I'll try to customizing edit dialog. I want to use 2 range inputs with edit drawer. I tired https://github.com/Kiho/react-form-builder/issues/256 code but Problem is 1) I am not able to access the edit drawer (side bar) for range -2 element able to access only for range-1 element. 

refer attached screenshot 1 & 2

**Comment by Kiho** [comment]
I don't see that problem myself, make sure you got latest code v0.15.2

**Comment by ShivkumarSalunkhe** [comment]
`Hello, I want to use 2 Range elements for custom elements kindly see this code let me know how can we achieve this.




const Value_Tolerance = React.forwardRef((props, ref) => {
  const { name, defaultValue, disabled } = props;

  return (
    <>
      <div
        style={{
          display: "flex",
          margin: "20px `200px",`
          alignItems: "center",
          width: "400px"
        }}
      >
        <div>
          <div
            style={{ display: "flex", alignItems: "center", margin: "20px" }}
          >
            <input
              className="form-control"
              placeholder="Enter Correct Value"
              id="1"
              type="number"
              style={{ width: "250px" }}
              ref={ref}
              name={name}
              defaultValue={defaultValue}
              disabled={disabled}
            />
          </div>

          <div
            style={{ display: "flex", alignItems: "center", margin: "20px" }}
          >
            <div className="input-group" style={{ width: "250px" }}>
              <input
                className="form-control"
                placeholder="Min Value"
                id="2"
                type="number"
                ref={ref}
                name={name}
                defaultValue={defaultValue}
                disabled={disabled}
                value={props.data.min_value}
              />
              <div className="input-group-append">
                <span className="input-group-text" id="basic-addon2">
                  {props.data.min_label}
                </span>
              </div>
            </div>

            <label
              style={{
                fontSize: "0.8rem",
                fontWeight: "bold",
                margin: "auto 20px",
              }}
            >
              Min Value
            </label>
          </div>
          <div
            style={{ display: "flex", alignItems: "center", margin: "20px" }}
          >
            <div className="input-group" style={{ width: "250px" }}>
              <input
                className="form-control"
                placeholder="Max Value"
                id="3"
                type="number"
                ref={ref}
                name={name}
                defaultValue={defaultValue}
                disabled={disabled}
                value={props.data.max_value}
              />
              <div className="input-group-append">
                <span className="input-group-text" id="basic-addon2">
                  {props.data.max_label}
                </span>
              </div>
            </div>

            <label
              style={{
                fontSize: "0.8rem",
                fontWeight: "bold",
                margin: "auto 20px",
              }}
            >
              Max Value
            </label>
          </div>
        </div>
      </div>
    </>
  );
});

const Percentage_Tolerance = React.forwardRef((props, ref) => {
  const { name, defaultValue, disabled } = props;

  return (
    <>
      <div
        style={{
          display: "flex",
          margin: "20px 200px",
          alignItems: "center",
        }}
      >
        <div>
          <div
            style={{ display: "flex", alignItems: "center", margin: "20px" }}
          >
            <input
              className="form-control"
              placeholder="Enter Value"
              id="2"
              type="number"
              style={{ width: "250px" }}
              ref={ref}
              name={name}
              defaultValue={defaultValue}
              disabled={disabled}
            />
          </div>
          <div
            style={{ display: "flex", alignItems: "center", margin: "20px" }}
          >
            <input
              className="form-control"
              placeholder="Enter Tolerence"
              id="3"
              type="number"
              style={{ width: "250px" }}
            />
            <label
              style={{
                fontSize: "1rem",
                fontWeight: "bold",
                margin: "auto 20px",
              }}
            >
              %
            </label>
          </div>
        </div>
      </div>
    </>
  );
});

Value_Tolerance.displayName = "Value_Tolerance";
Percentage_Tolerance.displayName = "Percentage_Tolerance";

Registry.register("Value_Tolerance", Value_Tolerance);
Registry.register("Percentage_Tolerance", Percentage_Tolerance);

const items = [
  {
    key: "Range",
    element: "Range",
    component: Value_Tolerance,
    type: "custom",
    forwardRef: true,
    field_name: "Value_Tolerance_",
    name: "Value Tolerance",
    icon: "fa fa-cog",
    label: "Value Tolerance",
    step: 1,
    min_value: 0,
    max_value: 0,
    min_label: "Unit",
    max_label: "Unit",
  },
  {
    key: "Range2",
    element: "Range",
    component: Percentage_Tolerance,
    type: "custom",
    forwardRef: true,
    field_name: "Percentage_Tolerance_",
    name: "Percentage Tolerance",
    icon: "fa fa-cog",
    label: "Percentage Tolerance",
    step: 1,
    min_value: 1,
    max_value: 10,
    min_label: "Unit",
    max_label: "Unit",
  },
  { key: "Header" },
  { key: "TextInput" },
  { key: "TextArea" },
  { key: "NumberInput" },
  { key: "Dropdown" },
  { key: "DatePicker" },
  { key: "RadioButtons" },
  { key: "Rating" },
  { key: "MultiColumnRow" },
  { key: "ThreeColumnRow" },
  { key: "TwoColumnRow" },
  { key: "Checkboxes" },
  { key: "Image" },
];`

**Comment by ShivkumarSalunkhe** [comment]
This is my project were we are trying to impalement Form builder custom range elements, check the project in codesanbox and responed as soon as possible  https://codesandbox.io/s/zealous-pond-hhcxor?file=/src/FormBuilderReact.jsx

**Comment by Kiho** [comment]
You should match key to component name.
```js
Registry.register("Value_Tolerance", Value_Tolerance);
Registry.register("Percentage_Tolerance", Percentage_Tolerance);

const items = [
  {
    key: "Value_Tolerance",
    element: "CustomElement",
    component: Value_Tolerance,
    type: "custom",
    forwardRef: true,
    field_name: "Value_Tolerance_",
    name: "Value Tolerance",
    icon: "fa fa-cog",
    label: "Value Tolerance",
    step: 1,
    min_value: 0,
    max_value: 0,
    min_label: "Unit",
    max_label: "Unit",
  },
  {
    key: "Percentage_Tolerance",
    element: "CustomElement",
    component: Percentage_Tolerance,
    type: "custom",
    forwardRef: true,
    field_name: "Percentage_Tolerance_",
    name: "Percentage Tolerance",
    icon: "fa fa-cog",
    label: "Percentage Tolerance",
    step: 1,
    min_value: 1,
    max_value: 10,
    min_label: "Unit",
    max_label: "Unit",
  },
```

Please think about your words, I have no reason to respond ASAP, this is totally volounteer work.

**Comment by ShivkumarSalunkhe** [comment]
Sorry for the words.

I want to use above 2 custom components with range element so we can set range values in edit dialog drawer..

**Comment by Kiho** [comment]
what is not working? It looks ok if match key & component to me.
```js
    key: "Percentage_Tolerance",
    element: "CustomElement",
    component: Percentage_Tolerance,
```

**Comment by ShivkumarSalunkhe** [comment]
I want to customize range element with above two elements Percentage_Tolerance & Value_Tolerance , I want it to be range because I want edit drawer like this,

![image](https://github.com/Kiho/react-form-builder/assets/105507602/c1235093-541c-4af5-bfe7-e03bef7224d3)

![image](https://github.com/Kiho/react-form-builder/assets/105507602/f41ab6d6-4bb5-4ac9-9da3-f75f4c713ced)

If this is not possible, then please suggest any other approach to achieve this.

**Comment by Kiho** [comment]
You can try v0.15.3

**Comment by ShivkumarSalunkhe** [comment]
Thank u so much it's working fine as expected in v0.15.3.
