### ISSUE TITLE
getting text with html tag on website link

### ISSUE THREAD

**Issue by aliyazahid** [Kiho/react-form-builder#264]
I am facing this issue. and its very urgent to resolve it. kindly check this. when i format the test with html editor. i am getting  this issue.
![image](https://user-images.githubusercontent.com/82146877/236825986-f77a66bf-13bf-419f-b147-367dcb30158f.png)

![image](https://user-images.githubusercontent.com/82146877/236825438-177d4704-3f7e-4bac-acca-151e2d272d64.png)

**Comment by Kiho** [comment]
You can use Label component for now.

**Comment by aliyazahid** [comment]
I am using website link item in my toolbox how can i use label component
for this?

**Comment by Kiho** [comment]
Sorry, I don't have time to fix format issue now, you can insert Link with bold text in Label component

**Comment by aliyazahid** [comment]
Hi Kiho,
I showed the demo to my client so I can't change it now. if you don't have
time can i fix this bug? if you allow me. you have to add only one line
just to format the text. we need to give it to my client

**Comment by Kiho** [comment]
You can submit PR.

**Comment by aliyazahid** [comment]
What is the process of it?  PR pull request?

**Comment by Kiho** [comment]
Nothing special, fix the code and submit pull request to kiho/react-form-builder master branch.

**Comment by aliyazahid** [comment]
ok thanks. once i done i will let you know

**Comment by aliyazahid** [comment]
i don't have permission can you please provide me the permission
[image: image.png]

**Comment by Kiho** [comment]
You should fork the project first, fix & push it in your fork, then you can create pull request.

**Comment by aliyazahid** [comment]
I cloned the project created new branched and resolve the. Now i fork the
code?

**Comment by Kiho** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

**Comment by aliyazahid** [comment]
Hi Kiho,
Can you please approve it, I have created the pull request having fixation
for website link label format issue and other field alignment. Thanks.

*Pull Request*: https://github.com/Kiho/react-form-builder/pull/268

[image: image.png]

**Comment by Kiho** [comment]
Updated on v0.15.4
