### ISSUE TITLE
Way to assign a fieldname to an input?

### ISSUE THREAD

**Issue by JasonColeyNZ** [Kiho/react-form-builder#266]
How can we assign field names to elements, I would like to use the form builder and allow users to enter data that will be persisted to a db in standard fields and custom fields.

But I can't really see how this would be done with the form builder, can we have list of fields to choose from populated from the app at runtime?

**Comment by Kiho** [comment]
You can implement at server-side https://github.com/Kiho/react-form-builder/issues/55
