### ISSUE TITLE
Extra <div> tag is coming when trying to use web site component

### ISSUE THREAD

**Issue by bhupesh-sf** [Kiho/react-form-builder#27]
When I try to use web site component and when I update placeholder text it shows the text wrapped with an extra <div> tag.

For e.g. if my placeholder text is google it will show as  <div>google</div>

Let me know if any further details are required.

**Comment by Kiho** [comment]
@bhupesh-sf 
I hope this https://github.com/Kiho/react-form-builder/commit/4ed771546de46945483955024c095c658f006579 fixes your problem without side effect.
Btw, I was working on demo page here https://kiho.github.io/react-form-builder/, I had to fix bunch of problems with posted answer data binding with form.  
So, I don't think those affect you but can you test it before publish?

**Comment by bhupesh-sf** [comment]
I just checked this one out and working as expected. You can freely publish it. And keep us posted any fixes as well. Thanks.
