### ISSUE TITLE
Onsubmit and Onchange not firing

### ISSUE THREAD

**Issue by AustinMKerr** [Kiho/react-form-builder#275]
Maybe I'm just crazy. I've installed this and have the reactFormGenerator successfully displaying my form however when I input data into the form I'm getting nothing from the onSubmit or onChange methods.  am I crazy?

<ReactFormGenerator
                    ref={(c)=>setChildRef(c)}
                    onChange={(data)=>console.log("dataonSubmit")}
                    onSubmit={(data,stuff)=>console.log("dataonSubmit")}
                    actionName="Set this to change the default submit button text"
                    submitButton={<button type={"submit"} hidden={true} className={"btn btn-primary"}>Submit</button>}
                    data={data}
                />

**Comment by Kiho** [comment]
Looks like your submit button has invalid markup. you should have closing tag.

**Comment by AustinMKerr** [comment]
Ahh, you're right. That makes sense. I can see the submit button and clicking the submit button works. but the on change method doesn't work. In my use case I want to store the state while the form is being entered. is there any way?

**Comment by Kiho** [comment]
Sorry about confusion but onChange is not supported and not easy to implement it.

**Comment by AustinMKerr** [comment]
oh gotcha. Thanks! I ended up downloading the repo and figuring it out. I did a private repo install, but I'll push here as a change in case you want to merge. Thanks so much for building a great package!
