### ISSUE TITLE
Date on mobile seems to show twice

### ISSUE THREAD

**Issue by ljorgens** [Kiho/react-form-builder#279]
Using the demo site found here: https://kiho.github.io/react-form-builder/

It appears that on mobile devices Date seems to show twice, see attached image 

<img width="322" alt="Screenshot 2023-08-02 at 10 58 43 PM" src="https://github.com/Kiho/react-form-builder/assets/6325586/8d4dcf00-9f20-4541-9ad6-766db7eb0acb">

**Comment by ljorgens** [comment]
It looks like this could be fixed by removing the placeholder on line 129 in react-form-builder/src/form-elements/date-picker.jsx

Not sure of all the implications of that change but it seems to have solved it from a quick test

**Comment by Kiho** [comment]
It should be ok with latest version
