### ISSUE TITLE
How to Implement react form builder in next js?

### ISSUE THREAD

**Issue by sptclr** [Kiho/react-form-builder#28]
so I'm new to programming and learning to react with next.js

I am interested in these depedencies, and want to try them. when you want to try it only works to display the form,

but when added with props in it the application doesn't work, maybe this isn't the right forum but I don't know who I want to ask.

I am confused when in implements with props and form generator
what should I prepare and what should I do

thank you

**Comment by Kiho** [comment]
Can you push the code what you have issues to github?

**Comment by sptclr** [comment]
it's just a normally setup in next.js, 

here's my github repo: https://github.com/sptclr/next-formbuilder

```
import React from 'react';
import FormBuilder from 'react-form-builder2';


//i think the url must place in static folder in next.js
import get from '../../static/json/GET/dummy-get.json'
import post from '../../static/json/POST/dummy-post.json'

var items = [{
    key: 'Header',
    name: 'Header Text',
    icon: 'fa fa-header',
    static: true,
    content: 'Placeholder Text...'
  },
  {
    key: 'Paragraph',
    name: 'Paragraph',
    static: true,
    icon: 'fa fa-paragraph',
    content: 'Placeholder Text...'
  }];

class Index extends React.Component {
    render(){
        return(
            <div>
                {/* this code works but i don't get it alternate form/preview form to get my json  */}
                <FormBuilder.ReactFormBuilder /> 

                {/* then i change my code from the above to like this. in this documentation when using props */}
                <FormBuilder.ReactFormBuilder
                url={get} //i dont know how put the url
                toolbarItems={items}
                saveUrl={post} />

                {/* then I put reactformgenerator under formbuilder, am i wrong? */}
                <FormBuilder.ReactFormGenerator
                    form_action={post}
                    form_method="POST"
                    
                    // for this part I have not understood what arguments I have to fill.
                    // Do I have to make blank files or do something else?
                    // because I also don't understand running the demo in the reactformbuilder master even though I have entered the demo folder and run npm install and npm start but it doesn't work

                    task_id={12} // Used to submit a hidden variable with the id to the form from the database.
                    answer_data={JSON_ANSWERS} // Answer data, only used if loading a pre-existing form with values.
                    authenticity_token={AUTH_TOKEN} // If using Rails and need an auth token to submit form.
                    data={JSON_QUESTION_DATA} // Question data
                />

            </div>
        )
    }
}

export default Index
```
this files included in pages/index.js

**Comment by Kiho** [comment]
I made changes to fix form builder in the PR. You need to run app with npm run server https://github.com/Kiho/next-formbuilder/blob/master/package.json#L11 then go to localhost:5050
Keep in mind I am new to NEXT.js, so maybe myway is not the best.

You need to fix ReactFormGenerator based on demobar.jsx of react-form-builder and implement user data receiver like this sample https://github.com/Kiho/react-form-builder/blob/master/server/server.js#L37

**Comment by Kiho** [comment]
One more important part, this library does not work with bootstrap 4.x.

**Comment by sptclr** [comment]
i still don't get it.. i was trying and still got an error..

i do following your steps.. and i got an error, when it needs a form.js i confusing reading that codes. maybe cause i'm new in programming and react.
it says: `No default engine was specified and no extension was provided`

so.. if you have some time, pls. give me an example should works on npm start. with reactFormGenerator in nextJS

i'm stuck.. sorry

**Comment by Kiho** [comment]
I do not know NEXT.js because I don't need SSR for my day job.
The error is coming from ejs view part, I don't think you can use ejs & NEXT same time.
So, probably you need to process data recieved here https://github.com/Kiho/react-form-builder/blob/master/server/api/form.js#L29 with normal react component.
Sorry, but I don't have time to resolve all your problems now. Maybe, I will try to make sample later If I can find time.

**Comment by sptclr** [comment]
okay sir.. thank you for your response.. I hope you can give examples faster than you think for next.js

**Comment by Kiho** [comment]
And you need to implement form generator like this https://github.com/Kiho/react-form-builder/blob/master/demobar.js#L99 This should render the form without server side implementation

**Comment by sptclr** [comment]
btw sir.. i have last question.. [https://raw.githubusercontent.com/Kiho/react-form-builder/master/screenshot.png](url) 
in that image, which explains the react form or react generator part? 

cause.. Reactform working well, but there's no preview or submit form

or maybe the question is.. how reactgenerator looks when it can run? i still curious with that

**Comment by Kiho** [comment]
You can find demo here https://kiho.github.io/react-form-builder/ I still need to work on the page but most of parts are working

**Comment by Kiho** [comment]
@sptclr I added next.js example here https://github.com/Kiho/react-form-builder/tree/master/examples/next

**Comment by sptclr** [comment]
there's missing next folder when i try download this file from [https://github.com/Kiho/react-form-builder](url)

btw thank you sir for fast response

and.. i still don't get it, when i try following basic usage when it needs custom form, could you update documentation? be more specific i think

**Comment by sptclr** [comment]
oh ya i think there was a bug when we preview form and got scrolled.. the preview can not to scroll down.

**Comment by Kiho** [comment]
You need to do `npm run build` in examples/next folder after `npm install`, it will create `.next` folder.
For preview form, you need to modify modal-content class in styles/site.css like this 
`.modal-content { padding: 30px; max-height: 500px; overflow-y: auto }`

**Comment by sptclr** [comment]
okay thank you sir,

i still hoping the documentation would be updated make it clear for noobie like me hehe

**Comment by sptclr** [comment]
hello sir, sorry to bother again, now what I want to ask is how to save data to mongodb? What should I do?
because actually I'm still confused to follow the program (nextjs) flow
I have tried the latest update of your nextjs version and it is working properly.

**Comment by Kiho** [comment]
This is only article I can search on net http://thecodebarbarian.com/building-a-nextjs-app-with-mongodb.html
You can save answer data here https://github.com/Kiho/react-form-builder/blob/master/examples/next/server/api/form.js#L30
And form data here https://github.com/Kiho/react-form-builder/blob/master/examples/next/server/api/routes.js#L18

**Comment by sptclr** [comment]
```
/* eslint-disable import/no-extraneous-dependencies */
/* eslint-disable no-const */
// eslint-disable-next-line import/no-extraneous-dependencies
// const handleForm = require('./form');
const mongoose = require('mongoose');
const express = require('express');
const handleForm = require('./form');
const formData = require('./formData');

const Schema = mongoose.Schema;
const formSchema = new Schema({
  data: String
})
const Builder = mongoose.model("Form-builder", formSchema);

const app = express();

app.route('/formdata/')
  .get((req, res) => {
    const getForm = formData.data.task_data
    // getForm.save()
    // console.log('get formdata: ', getForm);
    res.send(getForm);
  })
  .post((req, res) => {
    formData.data = req.body;
    // formData.data = req.body.task_data
    console.log(typeof formData.data);
    console.log('data', formData.data);
    const a = JSON.stringify(formData.data.task_data)
    const getForm = new Builder(a)
    getForm.save()
    console.log('post formdata: ', a);
    // res.status(200).json(getForm);
  });

app.route('/form/')
    .get((req, res) => {
      // console.log('a', formData.answers);
            
      res.send(formData.answers);
    })
    .post(handleForm);


module.exports = app;

```
i tried save like this but the result is error
ObjectParameterError: Parameter "obj" to Document() must be an object

any wrong with my code?

**Comment by sptclr** [comment]
sorry sir i forgot to describe my data.. i was fixing this error

new Builder({data: a})

thank you2 again,

btw there was an error with date.. i couldn't saved it

**Comment by Kiho** [comment]
This should fix your date picker problem.
https://github.com/Kiho/react-form-builder/blob/master/examples/next/server/server.js#L19

**Comment by sptclr** [comment]
hehe sorry to bother you again, sir, I want to ask again regardless of my question above, I'm done with that. thank you very much

now I want to ask, how to save data from the handleform, yesterday you told me to save this [line](https://github.com/Kiho/react-form-builder/blob/master/examples/next/server/api/routes.js#L18), but I can't log in that data, is there a clearer explanation? I want to save the image that I uploaded, but in the public /temp folder there are no files image i was uploaded. thanks again

**Comment by Kiho** [comment]
https://github.com/Kiho/react-form-builder/blob/master/examples/mongo/server/api/routes.js

**Comment by sptclr** [comment]
i still doesnt get it.. 

in this [part](https://github.com/Kiho/react-form-builder/blob/c32664d0602b6f1203b393c0b7b1e7334b79ffd9/examples/mongo/server/api/routes.js#L14) 

why you `await formData.load(req.db)` maybe it's same point but i using mongoose.. maybe the syntax bit different.. i mean, load is what for?
then next line is  `formData.task_data = data;` <-- why formData not nested from formData.data.task_data? only formData.task_data

btw thanks a lot sir.. now i can save my data and answer, but i still confusing with that get..

**Comment by Kiho** [comment]
It is waiting for data from mongo https://github.com/Kiho/react-form-builder/blob/master/examples/mongo/server/api/formData.js#L22, I am using standard driver here.
You can pull the repo and try the sample project.

**Comment by sptclr** [comment]
ok sir, thank you very much for your help so far, the example that you gave is very clear. now, it is my turn to do my own business by changing it to mongoose
