### ISSUE TITLE
Unable to add edit and delete buttons on dropbox

### ISSUE THREAD

**Issue by nitishpratap18** [Kiho/react-form-builder#282]
Hi,
How can i add the edit and delete buttons to the
  <ReactFormBuilder
             toolbarItems={items}
         />
         also most of the examples are not working.

**Comment by nitishpratap18** [comment]
getting error
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/tokenize' is not defined by "exports" in /Users/nitishyadav/Desktop/repos/react-form-builder/examples/cra/node_modules/postcss-safe-parser/node_modules/postcss/package.json

**Comment by nitishpratap18** [comment]
Can you provide me the links

**Comment by Kiho** [comment]
Just pull master branch then build and run start.
