### ISSUE TITLE
Full list data for standard components 

### ISSUE THREAD

**Issue by HuyvictoryTego** [Kiho/react-form-builder#286]
Can I have the full list of standard components (in json form) of the toolbar. So that I could use some of those for my customized toolbar.
Here is the currrent list on npmjs
![image](https://github.com/Kiho/react-form-builder/assets/117971752/fe3e8ae3-9d83-4882-aa86-ec7c7fe32482)

**Comment by medic345** [comment]
Have you found an update to this? I'm trying to find the component name for Date

**Comment by HuyvictoryTego** [comment]
No update for now. Currently using on everything provided on the npmjs document

**Comment by Kiho** [comment]
You can build json with keys extract from this function - https://github.com/Kiho/react-form-builder/blob/master/src/toolbar.jsx#L95
