### ISSUE TITLE
Need a new component for Elastic Search

### ISSUE THREAD

**Issue by bhupesh-sf** [Kiho/react-form-builder#30]
Hi @Kiho in our project we have a specific need to have elastic search component as part of Form Builder so we can search the required stuff and post it to the API endpoint.

Currently the package for elastic search we are using in our application is 
https://opensource.appbase.io/reactivesearch/

Its quite a good component and I would like to implement the same in Form Builder.

Can you help me out in this OR guide me how to write such a component?

**Comment by Kiho** [comment]
@bhupesh-sf Sorry, but I could not figure what could be done with reactive search in this project.

**Comment by bhupesh-sf** [comment]
@Kiho Can you at least help me in the direction so that I can go ahead try it out?

**Comment by Kiho** [comment]
Looks like you need another modal dialog or navigate to other page and then come back after search.
