### ISSUE TITLE
Edit Pre-existing Form Elements

### ISSUE THREAD

**Issue by SirajNu10** [Kiho/react-form-builder#302]
I would like to know the process to load and edit the existing form element that was created a while ago when the form was built and submitted. The form was saved in our DB and rendered separately if user wants to edit the form element label or anything else in that element. but when I use the editMode I am unable to edit the elements but I am able to see all the existing form elements in the ReactFormBuilder.
I get the below error
```
Cannot read properties of null (reading 'trim')
TypeError: Cannot read properties of null (reading 'trim')
    at convertFromHTMLToContentBlocks (http://localhost:3000/static/js/bundle.js:70737:15)
```

below is the code
```
<ReactFormBuilder
          editMode
          locale="en"
          saveAlways={false}
          onSubmit={handleSubmit}
          data={formData}
          //onLoad={()=> Promise.resolve(formData)} tried this too I get the following error
        />
```

**Comment by SirajNu10** [comment]
resolved

**Comment by sinbargit** [comment]
@SirajNu10  Did you find a way to edit existing form? Please tell me how

**Comment by Kushal0891** [comment]
@SirajNu10  were you able to prepopulate the data in dropzone
