### ISSUE TITLE
Cannot have two HTML5 backends at the same time 

### ISSUE THREAD

**Issue by boomihere** [Kiho/react-form-builder#304]
@Kiho first of all thank you for creating such a wonderful utility, i did follow all the recommendations said in the closed cases[refer to picture below], none of this helped in our situation, ours is a CRA i am using your utility as a component in our application,  i tried with node version 16.1 and the latest 21 the issue still exist. could you please help. 

here is the code snip, 
   <FormBuilder.ReactFormBuilder
                // toolbarItems={items}
                key={"nanoid()"} 
                data={form} 
                url={url}
                saveUrl={saveUrl}
                locale='en'
                saveAlways={false}
                showCorrectColumn={true}
                show_description={false}
                editMode={true}
                onPost={handleSubmit}
                // className="flex-col flex-1 px-10 sm:px-6 lg:px-4 py-4 w-full "
                renderEditForm={props => <FormElementsEdit {...props}/>}
              />

the closest match was issue #220 however calling twice is react native approach, it always call it twice, unless the user have explicitly called it twice,  

steps to reproduce,
1.  add a item from the Toolbox, 
2. click edit, 
3. close the FormElementsEdit window
4. drag another item from Toolbox 

then the crash occurs.

i did try to run your program standalone, it works like a perfectly. please suggest what can go wrong.

![image](https://github.com/Kiho/react-form-builder/assets/11548523/85f0a654-b887-44a2-8c18-dcbe77268d5c)
i am getting following error message,

react-dom.development.js:12056 Uncaught Error: Cannot have two HTML5 backends at the same time.
    at HTML5BackendImpl2.setup (HTML5BackendImpl.js:403:15)
    at DragDropManagerImpl2.handleRefCountChange (DragDropManagerImpl.js:38:25)
    at Object.dispatch (redux.js:297:7)
    at HandlerRegistryImpl2.addSource2 (HandlerRegistryImpl.js:92:18)
    at registerSource (registration.js:10:27)
    at DragDropContainer3.receiveType (decorateHandler.js:151:34)
    at DragDropContainer3.receiveProps (decorateHandler.js:136:16)
    at DragDropContainer3.componentDidMount (decorateHandler.js:112:16)
    at commitLayoutEffectOnFiber (react-dom.development.js:23305:30)
    at commitLayoutMountEffects_complete (react-dom.development.js:24688:9)

**Comment by richardpickett** [comment]
[Here's a quick fix](https://github.com/Kiho/react-form-builder/pull/308#issuecomment-2216476936) while you wait for the PR update.
