### ISSUE TITLE
Saved answer structure does not match the one needed to load a value

### ISSUE THREAD

**Issue by andreujuanc** [Kiho/react-form-builder#31]
Hi, 
The data I get from the builder has this format:
```js
[ { name: 'date_picker_C2950C61-B205-47C3-A616-F3B2655AB10C',
    value: '03/01/2019' }]
```
And the structure needed to fill the built form is like so:
```js
{ 'date_picker_C2950C61-B205-47C3-A616-F3B2655AB10C':  '03/01/2019' }
```

Should the builder unity the structure/format? 
If not, then it should be clearly stated in the documentation.

Cheers

**Comment by Kiho** [comment]
Form posting is working without issues. I will find time to update data format in json posting.
You can implement something like this for now.
https://github.com/Kiho/react-form-builder/blob/master/examples/next/pages/form.js#L69

**Comment by andreujuanc** [comment]
Thanks for replying @Kiho . I did solve it in a similar fashion. 
I opened the issue just to report it in, as I thought it might help someone who's using the library, specially since there was no open issue about it.

Thanks

**Comment by Kiho** [comment]
@andreujuanc Either case should work without extra code.
