### ISSUE TITLE
Issue with Multi-Checkbox Fields in ReactFormGenerator After Update to Version 0.18.2

### ISSUE THREAD

**Issue by madhavawasthi6430** [Kiho/react-form-builder#323]
Multi-checkbox fields are not working after updating to version 0.18.2. I have attached a video link for reference.

In the video, you can see that I have checked two fields, but after submitting, the checkboxes are not getting checked.

I also tried to debug the issue, and I found that the payload data coming from ReactFormGenerator is in a different format compared to the previous version. Here’s a comparison:

Old Format- 
{"id":"20E70237-C366-4111-BC62-EB15D9B3DD86","name":"20E70237-C366-4111-BC62-EB15D9B3DD86","custom_name":"20E70237-C366-4111-BC62-EB15D9B3DD86","value":["checkboxes_option_470CD458-20C0-4C8B-8963-D42E9114A528","checkboxes_option_D8F08F29-FD2C-4D47-BEFA-615DB34D36B3"]}

New Format- 
{"id":"20E70237-C366-4111-BC62-EB15D9B3DD86","name":"20E70237-C366-4111-BC62-EB15D9B3DD86","custom_name":"20E70237-C366-4111-BC62-EB15D9B3DD86","value":["place_holder_option_1","place_holder_option_2"]}

The discrepancy in how the values are named (e.g., "place_holder" vs. "checkboxes_option") seems to be the root cause of the checkboxes not appearing as checked after submission. You might need to either modify how the new payload is handled or convert the new format back to the old one for consistency.

#https://www.awesomescreenshot.com/video/32447558

**Comment by Kiho** [comment]
You are right, consistency is important. I reverted changes in 0.19.0

**Comment by madhavawasthi6430** [comment]
Now it's working fine. Thanks for your quick response!
