### ISSUE TITLE
Compiles but without any styling

### ISSUE THREAD

**Issue by wzawisa** [Kiho/react-form-builder#33]
I am trying to compile a basic example and I can get it to compile with 100% functionality but there is no styling.  I have included screenshots of my code and the rendering.  Could this be that I do not have the correct version of bootstrap? I installed all dependencies using npm so I am not sure what I am missing. Maybe a peer dependency?

![Screen Shot 2019-05-09 at 11 06 01 AM](https://user-images.githubusercontent.com/30123931/57464578-f419f900-724a-11e9-9f2d-d30bd0175531.png)

![Screen Shot 2019-05-09 at 11 05 45 AM](https://user-images.githubusercontent.com/30123931/57464565-efeddb80-724a-11e9-8217-c650da0a6e27.png)

**Comment by Kiho** [comment]
@wzawisa You need to add bootstrap & font-awesome CSS references https://github.com/Kiho/react-form-builder/blob/master/index.html#L4

**Comment by nnettin** [comment]
I have imported fontawesome styles and bootsratp styles. bjut still some styles are missing. could you please look into it. TIA.
![react-form-builder-no-styles](https://user-images.githubusercontent.com/27203111/58772821-4515d680-85d8-11e9-84f7-d8ef8b8ab681.png)

**Comment by wzawisa** [comment]
I also have this issue.

**Comment by Kiho** [comment]
Not sure what's your problem. You can try CDN like this
https://github.com/Kiho/react-form-builder/blob/master/docs/index.html#L7
