### ISSUE TITLE
'download_path' property is missing from the interface FormGeneratorProps in index.d.ts

### ISSUE THREAD

**Issue by goldenpine** [Kiho/react-form-builder#330]
The property is supposed to be used by 'File Attachment' field. Without it in the interface FormGeneratorProps , there is always a compile error when \<ReactFormGenerator\> is being used with that property in TypeScript. The error is captured as the below screenshot.

![image](https://github.com/user-attachments/assets/1d7a9778-3dec-4999-9a37-514134ce7ee0)

**Comment by Kiho** [comment]
Try latest version.
