### ISSUE TITLE
How can I call onPost in form builder?

### ISSUE THREAD

**Issue by leandrobviana** [Kiho/react-form-builder#34]
I am using **ReactFormBuilder** with other input fields. For example, a have a input text field for a "title" for the form. I edited the post call using the **"onPost"** prop to also send the title. 
But I don't want to post just when the form is edited, I want to post also when the other input fields are edited. 
**There is a way to "call" the "onPost"?** 
**Or, if not possible, a way to get the ReactFormBuilder data?**
If it is obvious, sorry for the question, I couldn't find a way.

**Comment by Kiho** [comment]
I am not sure what is your problem, please check this sample code first https://github.com/Kiho/react-form-builder/blob/master/examples/custom/app.js#L18 you can intercept form data and modify data for your end point as needed. If this is not the answer then explain the issue in more detail.

**Comment by leandrobviana** [comment]
Yeah, I am already using what you suggested. The problem is the function in "onPost" is only called when the form is changed. 
I want to be able to post the form data if other input also change , not just when the form is edited. 
I can call the function anyways, **the problem is that I don't know how to get the data from the editor.** 
**I simplified my code below:**
```javascript

import React, { Component } from 'react';
import 'bootstrap/dist/css/bootstrap.css';
import 'font-awesome/css/font-awesome.css';
import 'react-form-builder2/dist/app.css';
import './App.css';
import axios from 'axios';
import FormBuilder from 'react-form-builder2';

let component;

class form_editor extends Component {
 componentDidMount() {
    component = this;
}
post_form_edit(data) {
  axios.post(url, {
    "name": component.refs.form_name.value,
    "questions": data
  })
  .then(function (response) {
      console.log('posted!');
    })
    .catch(function (error) {
      console.log(error);
    });
}
render() {
  return (
    <div className="App">
    <input type="text" ref="form_name" />
    <hr></hr>
    <FormBuilder.ReactFormBuilder onPost={this.post_form_edit} ref='test_builder' />
    </div>
  );
}
}
```
As you can se in the onPost prop of ReactFormBuilder I pass the function `post_form_edit`, if the ReactFormBuilder is edited it call that function. **I want to be able to call the same function passing the data from the ReactFormBuilder.** I didnt find any "getdata()" in ReactFormBuilder.

**Comment by Kiho** [comment]
Your code only dealing with form structure data. If you need data from generated form then try it from here
https://github.com/Kiho/react-form-builder/blob/master/examples/custom/demobar.js#L51
Currently, you can't get both data at same time.

**Comment by leandrobviana** [comment]
Yeah got it, but I need to get the form structure data, also if I change the input in "form_name" (`<input type="text" ref="form_name" />`) in my editor page. Not the form generated. I want something like `ReactFormEditor.get_data()`.  I don't if I am been clear. LoL

**Comment by Kiho** [comment]
String ref is deprecated, so it may not work with newer version of react. You can try this
```
import React, { Component } from 'react';
import 'bootstrap/dist/css/bootstrap.css';
import 'font-awesome/css/font-awesome.css';
import 'react-form-builder2/dist/app.css';
import './App.css';
import axios from 'axios';
import FormBuilder from 'react-form-builder2';

class form_editor extends Component {
post_form_edit(data) {
  axios.post(url, {
    "name": this.formNameRef.value,
    "questions": data
  })
  .then(function (response) {
      console.log('posted!');
    })
    .catch(function (error) {
      console.log(error);
    });
}
render() {
  return (
    <div className="App">
    <input type="text" ref={ c => this.formNameRef = c } />
    <hr></hr>
    <FormBuilder.ReactFormBuilder onPost={this.post_form_edit} ref='test_builder' />
    </div>
  );
}
}
```

**Comment by leandrobviana** [comment]
Ok, got it, but how can I get the form structure data on the input change? With that I can post it to the backend again. For example when I put a handleChange in the input tag, like:
```javascript
import React, { Component } from 'react';
import 'bootstrap/dist/css/bootstrap.css';
import 'font-awesome/css/font-awesome.css';
import 'react-form-builder2/dist/app.css';
import './App.css';
import axios from 'axios';
import FormBuilder from 'react-form-builder2';

class form_editor extends Component {
  constructor(props) {
    super(props);
    this.state = {value: ''};
    this.handleChange = this.handleChange.bind(this);
  }
post_form_edit(data) {
  axios.post(url, {
    "name": this.formNameRef.value,
    "questions": data
  })
  .then(function (response) {
      console.log('posted!');
    })
    .catch(function (error) {
      console.log(error);
    });
}
  handleChange(event) {
    this.setState({value: event.target.value});
    let dataFromReactFormBuilder = ? //how can i get the form structure data, 
                                     //and post to the backend again?
    post_form_edit(dataFromReactFormBuilder)
  }
render() {
  return (
    <div className="App">
    <input type="text" ref={ c => this.formNameRef = c } onChange={this.handleChange}/>
    <hr></hr>
    <FormBuilder.ReactFormBuilder onPost={this.post_form_edit} ref='test_builder' />
    </div>
  );
}
}
```

**Comment by Kiho** [comment]
I updated example here you can follow https://github.com/Kiho/react-form-builder/blob/master/examples/custom/app.js

**Comment by leandrobviana** [comment]
It worked like a charm, thanks a lot! Very helpful. Sorry for bad explaning LoL. Anyway, thanks! This project is amazing.
