### ISSUE TITLE
Is there any way to choose which options to show when editing a question?

### ISSUE THREAD

**Issue by joseluishaddad** [Kiho/react-form-builder#37]

**Comment by joseluishaddad** [comment]
I would like to be able to choose which of the provided options to show when editing a question. For example in this case, i just want the "Required" checkbox to be shown.

![image](https://user-images.githubusercontent.com/20782393/58356526-b5d52a00-7e45-11e9-93f9-81096904ff8d.png)

**Comment by Kiho** [comment]
You need to update from NPM and then do this in app.js
```
const items = [
  {
    key: 'TextInput',
    canHaveAnswer: true,
    canHaveAlternateForm: false,
    name: 'Text Input',
    label: 'Placeholder Label',
    icon: 'fa fa-font',
    field_name: 'text_input_',
  },
  {
    key: 'NumberInput',
    canHaveAnswer: true,
    canHavePageBreakBefore: false,
    name: 'Number Input',
    label: 'Placeholder Label',
    icon: 'fa fa-plus',
    field_name: 'number_input_',
  },
];

ReactDOM.render(
  <FormBuilder.ReactFormBuilder variables={variables}
    url={url}
    toolbarItems={items}
    saveUrl={saveUrl}
  />,
  document.getElementById('form-builder'),
);
```

**Comment by joseluishaddad** [comment]
That's awesome! Thank You,
Is there also any way to hide the "Correct", "value", and "Display horizontal" options when editing Multiple Choice and Checkboxes? Like something similar to `canHavePageBreakBefore` and `canHaveAlternateForm` ??

**Comment by Kiho** [comment]
Please check anything is missing here? https://github.com/Kiho/react-form-builder/tree/hide-column

**Comment by joseluishaddad** [comment]
It seems to be ok :ok_hand:
