### ISSUE TITLE
Skip validations

### ISSUE THREAD

**Issue by parayab** [Kiho/react-form-builder#39]
First of all, thanks for maintaining this project 😄 

Is it possible to skip validations under certain conditions?
I want to be able to save changes without submitting them. For this purpose, I need to validate answers only when submitting them, so I can save them even when required questions aren’t answered

**Comment by Kiho** [comment]
@parayab  Check this branch https://github.com/Kiho/react-form-builder/tree/skip-validations and please let me know if I am missing any.

**Comment by parayab** [comment]
I checked and everything seems fine 👌
The only thing missing is `skip_validations` prop in readme.

**Comment by Kiho** [comment]
Merged & published
