### ISSUE TITLE
Add more features to each component

### ISSUE THREAD

**Issue by MrMegamind** [Kiho/react-form-builder#41]
Hi
We want to add more features when we edit any component like Radio / Checkbox
An example of what we require can be seen at http://prntscr.com/o3uc53

If you can guide us how do we do it on our own we will be gald to pay for your time

Thank you

**Comment by Kiho** [comment]
Hi @MrMegaMind,

Please send detail by email to kchang22@socal.com or set up the call to 714-423-5889

Thanks.

**Comment by DeepakM02** [comment]
can we have any feature where we can add a checkbox or any input type?
