### ISSUE TITLE
css is not loading

### ISSUE THREAD

**Issue by Silassiai** [Kiho/react-form-builder#42]
Integrated this in my own application.
Any idea why the css is not loaded? (no errors in my console)

This is my file.

```
import React, {Component, Fragment} from "react";
import {CardBody, CardTitle, Row, Card} from "reactstrap";
import IntlMessages from "Util/IntlMessages";
import {Colxx, Separator} from "Components/CustomBootstrap";
import {BreadcrumbItems} from "Components/BreadcrumbContainer";

import 'bootstrap/dist/css/bootstrap.css';
import FormBuilder from "react-form-builder2";

export default class FormCreate extends Component {
    render() {
        return (
            <Fragment>
                <Row>
                    <Colxx xxs="12">
                        <div className="mb-2">
                            <h1>
                                <IntlMessages id="menu.forms"/>
                            </h1>
                            <BreadcrumbItems match={this.props.match}/>
                            <Separator className="mb-5"/>
                        </div>
                    </Colxx>
                </Row>
                <Row>
                    <Colxx xxs="8">
                        <Card>
                            <CardBody>
                                <CardTitle/>
                                <CardBody>
                                </CardBody>
                            </CardBody>
                        </Card>
                    </Colxx>
                    <Colxx xxs="4">
                    <Card>
                        <CardBody>
                            <CardTitle/>
                            <CardBody>
                                <FormBuilder.ReactFormBuilder />
                            </CardBody>
                        </CardBody>
                    </Card>
                    </Colxx>
                </Row>
            </Fragment>
        )
    }
}

```

**Comment by Kiho** [comment]
Try load css files in index.html, I am not recommend to load styles from node.
https://github.com/Kiho/react-form-builder/blob/master/index.html#L5
You need to make sure css files are deployed to the location or use CDN.

**Comment by vardank37** [comment]
@Kiho   @Silassiai I am getting the same issue, have you solved it? adding CSS files in the index or using CDN didn't work for me

**Comment by Kiho** [comment]
@vardank37 @Silassiai You must have 3 css files referenced in index.html for correct styling.
```
  <link rel="stylesheet" type="text/css" href="css/font-awesome.min.css">
  <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="node_modules/react-form-builder2/dist/app.css">
```
If still problem then please post your sample project to github.
I don't have much idea without actual code to see.

**Comment by Kiho** [comment]
I update example project here https://github.com/Kiho/react-form-builder/blob/master/examples/demo/app.js#L7
You can download and start from there without css issue.

**Comment by vardank37** [comment]
@Kiho thank you so much for the response, CSS is loading now but only with the same version of bootstrap and font-awesome that you used in your project?

**Comment by Kiho** [comment]
I believe you can load CSS from CDN but restriction might be bootstrap 3.x.x and font-awesome 4.x.x.
Unfortunately I am not a CSS expert, so I don't think I can upgrade it to use newer version of vendor libraries in anytime soon. looks included bootstrap.css need to load fonts from ../fonts folder.

**Comment by Silassiai** [comment]
@vardank37 no I stopped trying and moved on to other things in my project.

@Kiho it is not convenient for me to load it into my .html file since I only use 1 main .html file for my entire application.
Should it also work with bootstrap 4? This is already being loaded in my entire project.

**Comment by Silassiai** [comment]
i added import "react-form-builder2/dist/app.css";
So, almost there, any idea what i am missing?

![image](https://user-images.githubusercontent.com/18419961/60573630-4e7d9480-9d78-11e9-9826-62f94771130b.png)

**Comment by Kiho** [comment]
@Silassiai You can setup font awesome follow by this article https://medium.com/@estherfalayi/setting-up-webpack-for-bootstrap-4-and-font-awesome-eb276e04aaeb
But I don't think you can use bootstrap 4 with this library.

**Comment by Silassiai** [comment]
Hi @Kiho , thanks!

I think I have to look for another library because it doesn't work completely with bootstrap 4. As you can see, not only does the awesome font miss but the css also doesn't work properly. Dragging the elements also does not work properly.

If someone knows a library that works with bootstrap 4, I'd love to hear it.

**Comment by Kiho** [comment]
@Silassiai Sorry about the situation but it's not a simple matter. I have to check all of used components are supporting bootstrap 4, and another hard part is I can't drop supporting bootstrap 3.

**Comment by Silassiai** [comment]
Hi @Kiho Kiho

No problem. It is my fault that I did not first check whether the library was compatible with bootstrap 4.
