### ISSUE TITLE
We need a pagination

### ISSUE THREAD

**Issue by aneepct** [Kiho/react-form-builder#43]
I am creating a project and needs a pagination feature on that. Can you suggest how can I do that?

Thank you in advance for all your help.

**Comment by Kiho** [comment]
I am not sure what pagination means.
You might need this https://github.com/andrewhathaway/Winterfell

**Comment by Kiho** [comment]
@aneepct Please check this sample code https://github.com/Kiho/react-form-builder/blob/master/examples/custom/app.js#L49 you can navigate the multiple forms with Drop Down.
