### ISSUE TITLE
How to store a builder form

### ISSUE THREAD

**Issue by heilgar** [Kiho/react-form-builder#44]
Ho to save data from builder? Can not find any action to add the button to the builder component.

**Comment by Kiho** [comment]
You don't need a save button.
```
<FormBuilder.ReactFormBuilder
  url='path/to/GET/initial.json'
  toolbarItems={items}
  saveUrl='path/to/POST/built/form.json' />
```
Just provide `saveUrl` to point where you want to post json data and `url` property to get data from.
When form builder detected the changes it will post automatically.

**Comment by ingalesachin7** [comment]
@Kiho How can we post more variable with save URL post URL like form_id ?
