### ISSUE TITLE
Adding save button to forms and receiving answer data?

### ISSUE THREAD

**Issue by bilemedimkq** [Kiho/react-form-builder#46]
Hi Kiho i have another question regarding the form creator:

How can we add a save button to a form we created by ReactFormGenerator and how can we recieve the answer data when we press the save button?

**Comment by Kiho** [comment]
Check this example https://github.com/Kiho/react-form-builder/tree/master/examples/mongo
You can save answer data to Mongo DB.

**Comment by bilemedimkq** [comment]
Thank you :)
