### ISSUE TITLE
how get more value from onSubmit ?

### ISSUE THREAD

**Issue by sptclr** [Kiho/react-form-builder#47]
hello, sir, long time no see, sorry, I bothering your time again.. want to ask about the results of the form submit,

```[{"text_input_207D331C-0EAF-4D63-AD42-EDFAA74268F5":"Rice","text_input_2E5BAE90-AB31-4800-91C2-8A1858CC1DF9":"1kg"}]```

can it be edited and added some results from the submit form, because for now the data obtained is only the name and value,

how do I want to get like a label and others?

thank you

**Comment by Kiho** [comment]
In constructor of demobar.jsx
```
constructor(props) {
    super(props);
    this.state = {
      data: [],
      previewVisible: false,
      shortPreviewVisible: false,
      roPreviewVisible: false,
    };
    
    // bind submit event handler to this.
    this._onSubmit = this._onSubmit.bind(this);
    const update = this._onChange.bind(this);
    ElementStore.subscribe(state => update(state.data));
  }
```
In _onSubmit method, you can find form data from state.
```
  _onSubmit(data) {
    console.log('this.state.data', this.state.data);
    console.log('onSubmit', data);
    // Place code to post json data to server here
  }
```

**Comment by sptclr** [comment]
thank you for the answer, but there is another question that is offensive. How do I retrieve data if from the onsubmit form preview? or others not from the builder form.

sorry forgot to ask this one

**Comment by Kiho** [comment]
I am not sure I am following you. 
https://github.com/Kiho/react-form-builder/blob/master/examples/custom/demobar.js#L92
Form Generator just use form data supplied from outside to render the form.

**Comment by sptclr** [comment]
ok sir.. thank you..

**Comment by mike1011** [comment]
> In constructor of demobar.jsx
> 
> ```
> constructor(props) {
>     super(props);
>     this.state = {
>       data: [],
>       previewVisible: false,
>       shortPreviewVisible: false,
>       roPreviewVisible: false,
>     };
>     
>     // bind submit event handler to this.
>     this._onSubmit = this._onSubmit.bind(this);
>     const update = this._onChange.bind(this);
>     ElementStore.subscribe(state => update(state.data));
>   }
> ```
> 
> In _onSubmit method, you can find form data from state.
> 
> ```
>   _onSubmit(data) {
>     console.log('this.state.data', this.state.data);
>     console.log('onSubmit', data);
>     // Place code to post json data to server here
>   }
> ```

both... `data` and `this.state.data` confused me but now it helped.
Great work Kiho. I love you.
