### ISSUE TITLE
Form Render Problem

### ISSUE THREAD

**Issue by bilemedimkq** [Kiho/react-form-builder#49]
Hello Kiho i have another issue about form builder. When i change the state pointed in the screenshot, the form does not render again and i see the old form.

https://prnt.sc/ond0nx

**Comment by Kiho** [comment]
Sorry, but it's hard to know without whole source code.
At least you need to show me content of data.

**Comment by bilemedimkq** [comment]
Here is the complete code:

https://gist.github.com/bilemedimkq/014f82144b82b8f55e36cbb31da513a2

**Comment by Kiho** [comment]
It was a bug, you should pull newer version.
Thanks.

**Comment by Kiho** [comment]
@bilemedimkq let me know if you still experiencing the issue.

**Comment by bilemedimkq** [comment]
issue solved.
