### ISSUE TITLE
how is the form type being saved?

### ISSUE THREAD

**Issue by rush86999** [Kiho/react-form-builder#5]
i can't seem to understand the flow?

is onPost used to save user typed data or form generated from drag and drop?

what are the functions for saving to a backend with the user-generated data and form type generation form drag and drop?

i need to control the form submission process so i can save it to my own server with authorization headers. any help would be appreciated.

**Comment by Kiho** [comment]
If you like to post JSON instead of form then uncomment this https://github.com/Kiho/react-form-builder/blob/master/demobar.js#L94 and put your code here https://github.com/Kiho/react-form-builder/blob/master/demobar.js#L55

**Comment by csKangGdcomm** [comment]
I think onSubmit prop is quit important feature.
I can't find description about it on README.md.
Can you update the file? Thank you!

**Comment by Kiho** [comment]
I am very busy at this point, I will find out time to update README.md soon.
