### ISSUE TITLE
 edit from in FormBuilder.ReactFormBuilder ?

### ISSUE THREAD

**Issue by alihbk** [Kiho/react-form-builder#51]
hi
thanks for this project.
how can i edit from in FormBuilder.ReactFormBuilder ?

**Comment by Kiho** [comment]
You can find examples here https://github.com/Kiho/react-form-builder#examples

**Comment by alihbk** [comment]
I couldn't find this feature

**Comment by Kiho** [comment]
I am not sure what's your question? 
Can you explain details?

**Comment by alihbk** [comment]
id like to display generated form before to the user , so he/she can edit and update it again but now formbuilder just show raw elements and there is no way to load generated form

**Comment by Kiho** [comment]
You need to setup server to store form data.
If you can follow this example https://github.com/Kiho/react-form-builder/tree/master/examples/mongo then you can save and load form with Mongo DB

**Comment by alihbk** [comment]
i know this section . i would show created form element from db to Edit Element . such as i Would add item to dropDown from old Form

**Comment by alihbk** [comment]
> 
> 
> You need to setup server to store form data.
> If you can follow this example https://github.com/Kiho/react-form-builder/tree/master/examples/mongo then you can save and load form with Mongo DB

can you help me?

**Comment by Kiho** [comment]
You can get more information from this issue https://github.com/Kiho/react-form-builder/issues/28

**Comment by Kiho** [comment]
Let me know if you need any help.
