### ISSUE TITLE
Drag and drop bug

### ISSUE THREAD

**Issue by bilemedimkq** [Kiho/react-form-builder#52]
https://gyazo.com/5e0eaff4a5a7e089d41f1cd1ee5717cb

Version: 0.2.4

**Comment by Kiho** [comment]
It should not be a bug from drag & drop. I believe that is caused by slow heroku back-end.
I added backdrop to demo to block form-builder access while waiting API call.

**Comment by Kiho** [comment]
Let me know if you still find issue.
