### ISSUE TITLE
Form are not responsive.

### ISSUE THREAD

**Issue by DeepakM02** [Kiho/react-form-builder#53]
I checked react-form-builder on mobile but it is not responsive and there are no preview button anywhere in desktop or all devices. when scroll form, content is not scrollable.

**Comment by Kiho** [comment]
Sorry, but I have no plan to make react-form-builder to work on mobile devices.

**Comment by DeepakM02** [comment]
form preview, the action button is not visible and form CSS is not responsive in desktop please check it and if you want I can share my code setup here.

**Comment by DeepakM02** [comment]
Can you share working code here [https://codesandbox.io/s/new](here)
