### ISSUE TITLE
how to replace id with the name as we want

### ISSUE THREAD

**Issue by sptclr** [Kiho/react-form-builder#55]
hello sir,

I want to ask, how do I get the name I want from a label in react form generator?

because the data generated from the react-form is in the form (field name) of an id, and the id does not match the name of the label that I want.

as an example : 
![image](https://user-images.githubusercontent.com/37174371/65810902-fae5e000-e1da-11e9-8294-aef33fedfd1d.png)

and here's the data when i submit the form
![image](https://user-images.githubusercontent.com/37174371/65811281-3a62fb00-e1e0-11e9-8710-7aa43ae350d3.png)

how to change field name in react form as an id into the name what i want..

thank you sir

**Comment by Kiho** [comment]
I this example https://github.com/Kiho/react-form-builder/blob/master/examples/mongo/server/api/form.js#L64
you can get label in this way
```
function saveAnswers(db, answers) {
  if (answers && answers.length) {
    answers.forEach(o => {
      const field = formData.task_data.find(x => x.field_name === o.name);
      o.label = field.label;
    });
    db.collection('answers').insertMany(answers);
  }
}
```

**Comment by sptclr** [comment]
ok sir.. i will try it.

thanks for the answer..
