### ISSUE TITLE
How to Call Data from Database in Form Builder Component?

### ISSUE THREAD

**Issue by sptclr** [Kiho/react-form-builder#56]
hello kiho-chang, sorry interupt your time again. i wanna ask you something about form builder. 

how can we get data from the database and apply it to the formbuilder?

For example, I choose a select box, and when I want to display contents in a select box, I have to manually enter the options and fill them in,
![image](https://user-images.githubusercontent.com/37174371/66740014-44e9e980-ee9c-11e9-946b-f7c30556a580.png)

from the statement above, can I when select the select box and in the options section there are database options that I want to display the data?

![image](https://user-images.githubusercontent.com/37174371/66740343-220c0500-ee9d-11e9-878c-97281428de65.png)

thank you..

**Comment by Kiho** [comment]
Database is not possible here, maybe I can add text box to save API URL for options.
Still it's not simple...

**Comment by sptclr** [comment]
or maybe you can tell us how to edit these options? and we can use it or change it according to what we want, so there is no need to change the core.

because there could be an error when changing the core, the form-builder update error returned to default again.

**Comment by Kiho** [comment]
Let me know if this branch works for you?
https://github.com/Kiho/react-form-builder/tree/api-options

**Comment by sptclr** [comment]
how do i use it? isn't that the same? when I clone the link you gave

**Comment by Kiho** [comment]
Do `git checkout api-options` after clone

**Comment by sptclr** [comment]
thank you kiho-chang it worked

and this is in accordance with what is desired

**Comment by sptclr** [comment]
sir.. sorry bothering you again..

i just wanna ask, in your package.json your react is 16.3,
is it possible? if you update the react into newest? so we can use react hooks..

thank you

**Comment by Kiho** [comment]
You should be able to use newer version of react and hooks in your project. just does not allow to you use lower than 16.3 of react.
