### ISSUE TITLE
Loading JSON from dragged form elements

### ISSUE THREAD

**Issue by PavanKumarHRao** [Kiho/react-form-builder#59]
How to get Dragged Item JSON from the form,I am not able to follow the flow? Can anyone please help regarding this?
I can connect with skype,zoom!

**Comment by Kiho** [comment]
You can get it from moveCard method in preview.jsx
```
  moveCard(dragIndex, hoverIndex) {
    const { data } = this.state;
    const dragCard = data[dragIndex];
    console.log(dragCard);
    this.saveData(dragCard, dragIndex, hoverIndex);
  }
```
