### ISSUE TITLE
is it possible to set validation on input?

### ISSUE THREAD

**Issue by csKangGdcomm** [Kiho/react-form-builder#6]
Thank you for maintaining awesome project.

I look around readme.md and source code, there is no option for setting validation except required.

For example, I want to set 65 length limit on 'Text Input'.

Without the feature that setting some extra validation, it seems that this one is only suitable for internal use..

I am considering some libraries ( this one and https://github.com/mozilla-services/react-jsonschema-form ) but the target of our product is external users not internal ones.

I just check out that google form has no features about validation like this one!

Is it OK to use this one without validation for google form likely feature? I just wonder your(maintainer) opinion.

**Comment by Kiho** [comment]
Usually, you need both client & server side validation for form in public website in my opinion.

**Comment by Kiho** [comment]
I will consider adding more client side validation to lib when time is permitted.
Close issue for now.
