### ISSUE TITLE
Reactformbuilder form element label does not update after closing edit panel

### ISSUE THREAD

**Issue by johnschimmel** [Kiho/react-form-builder#60]
Noticed that version 0.4.0 does not update the form element label in ReactFormBuilder if you edit label in WYSIWYG edit panel then close the panel. I can see the element's state is marked dirty though.

I rolled back to 0.3.2 and the label updating was working as expected.

Wish I had some time to dig deeper - but wanted to report here.

And thanks for the great library.

**Comment by Kiho** [comment]
0.4.1 should work as expected. 
Let me know if still can see the issue.

**Comment by johnschimmel** [comment]
That was it! thank you
