### ISSUE TITLE
Is there any possibility to add upload image element?

### ISSUE THREAD

**Issue by komangteguh** [Kiho/react-form-builder#62]
Just wondering if there is any possibility to add upload image (base64) when creating form, that would be very helpful. thanks

**Comment by Kiho** [comment]
Camera component does not work for you?

**Comment by komangteguh** [comment]
In my case it doesn't work, since user wants to upload image (url base64) while creating the form.

**Comment by Kiho** [comment]
You can submit base64 image with custom submit handler.

https://github.com/Kiho/react-form-builder/blob/master/demobar.js#L68
https://github.com/Kiho/react-form-builder/blob/master/demobar.js#L108
