### ISSUE TITLE
Pasted text in paragraph element contains markup

### ISSUE THREAD

**Issue by noslouch** [Kiho/react-form-builder#64]
If I paste in text copied from another source (like a google doc) into a Paragraph element, the component saves the hidden markup as the `content` property of the field.

Take a look a this demo form: https://safe-springs-35306.herokuapp.com/api/form?cid=811670bf_8710_3b23_2dfd_de57573897fb

![image](https://user-images.githubusercontent.com/2090382/73377566-3e398380-428d-11ea-93c1-7719d8992121.png)

**Comment by noslouch** [comment]
bump

**Comment by Kiho** [comment]
Sorry but I  don't think I can fix this issue.
I am using 3rd party code to converting HTML, it does support only limited set of tags.
