### ISSUE TITLE
Module not found: Can't resolve 'jquery'

### ISSUE THREAD

**Issue by utahisnotastate** [Kiho/react-form-builder#68]
Hi!

I am trying to get a very basic example going in my React/Electron project. I installed via yarn add and did the following: 

    import {ReactFormBuilder} from 'react-form-builder2'
    export default function Example() {
    return (
          <div>
                <ReactFormBuilder />
          </div>
    );
    }

I get a Failed to compile error with: 
"./node_modules/bootstrap-slider/dist/bootstrap-slider.js
Module not found: Can't resolve 'jquery' in '`/node_modules/bootstrap-slider/dist'"

I'm trying to figure out what im doing wrong and any help you can provide would be great. 

Thanks!

**Comment by Kiho** [comment]
Check this out at bootstrap-slider repo https://github.com/seiyria/bootstrap-slider#webpack
I never tried form-builder with electron, not sure this can apply...
