### ISSUE TITLE
Click event is not working and not opening the edit element pane

### ISSUE THREAD

**Issue by bhupesh-sf** [Kiho/react-form-builder#7]
After debuggin I got this point 

`editModeOff(e) {
    //  const $menu = $(".edit-form");
    //  let click_is_outside_menu = (!$menu.is(e.target) && $menu.has(e.target).length === 0);
    let click_is_outside_menu = !(e.target && e.target.closest(".edit-form")) && e.screenX > 0;
  
    if (this.state.editMode && click_is_outside_menu) {
      this.setState({
        editMode: false,
        editElement: null
      });
    }
  }`

And if I comment below line then I can see edit element pane (which open from left on clicking the edit icon)
`let click_is_outside_menu = !(e.target && e.target.closest(".edit-form")) && e.screenX > 0;
`

There is another code in header bar
`{ this.props.data.element !== "LineBreak" &&
            <div className="btn is-isolated btn-school" onClick={this.props.editModeOn.bind(this.props.parent, this.props.data)}><i className="is-isolated fa fa-pencil-square-o"></i></div>
          }`

Seems like both the click events are fired at the same time and in my case editModeOn fired first and then editModeOff.

But in your demo its working perfectly. Right now I am working with commenting this line in node_modules but now going to deploy so its not working there.

Any solution for this?

**Comment by Kiho** [comment]
I am not sure this can fix your problem. 
https://github.com/Kiho/react-form-builder/blob/master/src/index.jsx#L27
If it's not then you need to reproduce problem with code

**Comment by bhupesh-sf** [comment]
Can you publish it on nmp?

**Comment by Kiho** [comment]
It was published at npm, but I don't think it works for you.
I can't guess your problem without seeing the code.
Or probably I need to implement layer to block form-builder and attach click-handler there.

**Comment by bhupesh-sf** [comment]
That fix didn't helped me and neither I could find that on npm. Anyways please find attached my coderender function. I am doing nothing fancy here. I believe you have to do something else to sort this issue. 
Can we expect it sooner?
![carbon](https://user-images.githubusercontent.com/6471510/49019677-7d190880-f1b4-11e8-8917-bbdd90c260b0.png)

**Comment by bhupesh-sf** [comment]
@Kiho Any update in this?

**Comment by Kiho** [comment]
Try this branch https://github.com/Kiho/react-form-builder/tree/click-event

**Comment by bhupesh-sf** [comment]
Can you publish it on npm?

**Comment by Kiho** [comment]
It is published.

**Comment by bhupesh-sf** [comment]
Sorry above was my mistake, I need to update the version in my package.json. Now I have the latest code but its still not working.

I put the break point in the code, so what it does is open the left pane (when its stopped on left pane) and as soon as I move from break point it immediately closes.

Problem is below is always evaluating to true:

`let click_is_outside_menu = !(e.target && e.target.closest(".edit-form")) && e.screenX > 0;`

What could be the reason for this?
