### ISSUE TITLE
Having issues when i build

### ISSUE THREAD

**Issue by edmundopolos** [Kiho/react-form-builder#72]
I'm unable to build any of the examples it usually revolves around react-bootstrap-slider

**Comment by Kiho** [comment]
Pull update from repo, demo & custom should work.
Still working on other demos.

**Comment by Kiho** [comment]
next example should work now.

**Comment by edmundopolos** [comment]
oh great! you are awesome, after generating a form and a user selects answers e.g from a dropdown; does the form validate the selected responses in preview mode or readonly mode

**Comment by Kiho** [comment]
I don't understand what is your problem, please get me more detail.

**Comment by Kiho** [comment]
All samples are current.
