### ISSUE TITLE
Need Help!

### ISSUE THREAD

**Issue by monizb** [Kiho/react-form-builder#73]
Hey I am a newbie in React, could you please help me get started, I got the demo working properly, but when I try to use custom or next, it compiles successfully but the page shows nothing, and could you also please help me set up my mongodb to save the survey results.Thanks!

**Comment by DeepakM02** [comment]
@monizb Please look at the readme file. There is everything in detail. You have to just follow documentation. Please implement and share code or something so that we can help.

**Comment by Kiho** [comment]
@monizb I can't find error when running samples, you need to get me more context.
With mongo example you got most of basic functions, you should make sure install mongo and running at localhost:27017

**Comment by monizb** [comment]
@Kiho @DeepakM02 Hey, thanks for the quick reponse although when i was running the mongo example , I got the following error. I dont know if I am doing something wrong here.

The error: 

 throw error;
          ^

TypeError: Cannot read property 'db' of undefined
    at /Users/monish/Desktop/Survey Tool 2/react-form-builder/examples/mongo/server/server.js:33:21
    at /Users/monish/Desktop/=Survey Tool 2/react-form-builder/examples/mongo/node_modules/mongodb/lib/utils.js:722:9
    at /Users/monish/Desktop/Survey Tool 2/react-form-builder/examples/mongo/node_modules/mongodb/lib/mongo_client.js:219:23
    at connectCallback (/Users/monish/Desktop]/Survey Tool 2/react-form-builder/examples/mongo/node_modules/mongodb/lib/operations/connect.js:350:5)
    at /Users/monish/Desktop/Survey Tool 2/react-form-builder/examples/mongo/node_modules/mongodb/lib/operations/connect.js:417:14
    at Server.<anonymous> (/Users/monish/Desktop/=Survey Tool 2/react-form-builder/examples/mongo/node_modules/mongodb/lib/topologies/server.js:230:11)
    at Object.onceWrapper (events.js:418:26)
    at Server.emit (events.js:311:20)
    at Pool.<anonymous> (/Users/monish/Desktop/Survey Tool 2/react-form-builder/examples/mongo/node_modules/mongodb/lib/core/topologies/server.js:436:21)
    at Pool.emit (events.js:311:20)

**Comment by Kiho** [comment]
I can see same error if I stop mongo db server.
Did you install and run mongo db on your machine?
https://docs.mongodb.com/manual/installation/

**Comment by monizb** [comment]
@Kiho Thanks that seemed to work perfectly now! I don't know why my server was stopping abruptly. Just one last help, could you please tell me about some of the files and what they do cause I feel really lost 😅. This would be really helpful to be put in the documentation as well!
