### ISSUE TITLE
Accessing saved forms and user data error

### ISSUE THREAD

**Issue by quinamatics** [Kiho/react-form-builder#76]
Hi, I'm currently using your mongo db example and trying to 1) save a form i make, 2) access a saved form, and 3) be able to enter data to a form and see it. Right know I can only do 1) but I can't see any saved forms or enter/see any user data. I'm running mongo concurrently on the correct port (simply opened another terminal and ran the command "mongo") with npm run dev running.

When I try to go to localhost:3000/form the page shows an error: Cannot read property 'split' of undefined as in the photo (I've also attached a screenshot of the forms page without any forms or user data). Could you help list out the steps/commands to access a saved form and user data?

Thanks!!

<img width="1240" alt="Screen Shot 2020-05-20 at 10 23 05 PM" src="https://user-images.githubusercontent.com/28470823/82516612-3bd39180-9ae9-11ea-96ed-cc83dc56af5b.png">
<img width="1230" alt="Screen Shot 2020-05-20 at 10 23 19 PM" src="https://user-images.githubusercontent.com/28470823/82516615-3d9d5500-9ae9-11ea-88d9-9dc1eb4572e2.png">

**Comment by Kiho** [comment]
Try and let me know if you still facing a issue.

**Comment by quinamatics** [comment]
I don't seem to be having the same crash, but the form page is still blank. In particular how do I create and save a second form (in addition to the one I already made), and how do I enter user data and where can I view that data (the public/temp folder is empty)
