### ISSUE TITLE
Show Horizontal Error and also Saving/Loading multiple forms

### ISSUE THREAD

**Issue by quinamatics** [Kiho/react-form-builder#78]
Two questions: 1) For the checkboxes and multiple choice, when I select "Show horizontal" the form doesn't work (the choices aren't horizontal)

Also, how do I submit answers to the form? The /forms page is still empty and the answers I choose don't appear in db.answers.find()

**Comment by Kiho** [comment]
1) It's a bug came from one of PR, I will resolve soon.
2) You can submit answers from preview form, it will navigate to /forms page with results.

**Comment by quinamatics** [comment]
Found another bug,

When I try to create a long form, when I click preview the modal (where you can submit answers) isn't scrollable so long forms cannot be submitted. Could this also be fixed?

**Comment by Kiho** [comment]
Update to 0.5.8, it should work as expected.

**Comment by quinamatics** [comment]
The horizontal checkboxes feature works now, but long forms still cannot be submitted. Here's what I mean, when I have like 10 fields the form extends to the bottom of the page, and when I try scrolling the background page scrolls but not the preview modal. 

<img width="1676" alt="Screen Shot 2020-05-24 at 3 13 49 PM" src="https://user-images.githubusercontent.com/28470823/82762816-2dc78e80-9dd1-11ea-88f7-900d3b0460e0.png">
