### ISSUE TITLE
Multiple Choice and Checkbox overlapping with Label

### ISSUE THREAD

**Issue by quinamatics** [Kiho/react-form-builder#80]
After migrating the app over to Next.js, I'm starting to see that multiple choice and checkbox forms are not appearing the way they should, and the checkboxes/radio buttons are overlapping their corresponding labels. I've imported site.css as well as the index.html links to my code, is there a css fix?
<img width="1334" alt="Screen Shot 2020-05-31 at 6 03 56 PM" src="https://user-images.githubusercontent.com/28470823/83363728-97174680-a369-11ea-8649-2e596aa62172.png">
<img width="957" alt="Screen Shot 2020-05-31 at 6 03 44 PM" src="https://user-images.githubusercontent.com/28470823/83363731-98487380-a369-11ea-943f-6f90df2f5fc1.png">

**Comment by Kiho** [comment]
I can't know reason without actual code.
You should to make sure you have latest version on dependencies https://github.com/Kiho/react-form-builder/blob/master/examples/mongo/package.json#L32 and import css at application start-up https://github.com/Kiho/react-form-builder/blob/master/examples/mongo/pages/_app.js#L6
