### ISSUE TITLE
Demo page doesn't work

### ISSUE THREAD

**Issue by MedinaGitHub** [Kiho/react-form-builder#82]
Hi ! thanks you for the proyect =)

button Preview Form doesn't show anything
![image](https://user-images.githubusercontent.com/16387514/85075842-10e26900-b18d-11ea-8d81-a6d9bfae5a1f.png)

**Comment by Kiho** [comment]
This demo is running on github & heroku without pay under some restrictions, so I don't think same problem exists on actual code. I will try to find out time to check it out but it's not a priority.

**Comment by tflanagan** [comment]
Demo isn't working :(

**Comment by Kiho** [comment]
Free time runs out for month, it will be back to work at September 1st
