### ISSUE TITLE
Description field

### ISSUE THREAD

**Issue by Sandip-Z** [Kiho/react-form-builder#83]
Along with question, question's description field where user is allowed to describe that particular question is quite necessary.
It would be amazing if you could add this feature.

**Comment by Kiho** [comment]
I do not understand your requirement. Can you make it more clear with details?

**Comment by Sandip-Z** [comment]
to be more precise..
https://photos.app.goo.gl/sUmzvr31pyH2jom56

**Comment by Kiho** [comment]
It is implemented but not as default, so you should enable it to use.
```js
  <FormBuilder.ReactFormBuilder
    variables={variables}
    url={url}
    saveUrl={saveUrl}
    show_description
  />,
```
