### ISSUE TITLE
Tried to include it in my app but it didn't work.

### ISSUE THREAD

**Issue by RoosterH** [Kiho/react-form-builder#86]
I am a newbie for React.  I tried to include the form-builder in my app.  I followed the instruction to render <FormBuilder.ReactFormBuilder /> but I only got texts: 

![Screen Shot 2020-07-18 at 12 57 42 AM](https://user-images.githubusercontent.com/25292210/87848130-17e6bf00-c892-11ea-958c-c9f702f34b4d.png)

What am I missing here?  Please help.

**Comment by RoosterH** [comment]
This post had the same question as mine: https://stackoverflow.com/questions/58608159/how-can-i-use-react-form-builder-2-in-react-js-project

**Comment by Kiho** [comment]
You should add bootstrap & font-awesome style sheets to index.html https://github.com/Kiho/react-form-builder/blob/master/public/index.html#L5

**Comment by RoosterH** [comment]
@Kiho Thanks a lot for your answer.  After including both, I got the content showing.  However the layout is off also the editor modal not only way off but also not able to type anything inside.  Is it css issue?  Thanks again!
![Screen Shot 2020-07-19 at 12 25 37 AM](https://user-images.githubusercontent.com/25292210/87869673-6cec0900-c956-11ea-8733-23de28aa6873.png)
![Screen Shot 2020-07-19 at 12 24 50 AM](https://user-images.githubusercontent.com/25292210/87869685-7a08f800-c956-11ea-8435-366bb97203f9.png)

**Comment by Kiho** [comment]
You have to import app.css in your application.
```
import 'react-form-builder2/dist/app.css';
```

**Comment by Kiho** [comment]
https://github.com/Kiho/react-form-builder/blob/master/examples/demo/app.js#L7

**Comment by RoosterH** [comment]
Kiho, after including app.css, it does work now.  However, I found out bootstrap & font-awesome style sheets ruined my css. So I tried to remove both but I couldn't.  Even though I removed them from index.html, somehow they always stay there.  I tried to search online to find a way to get rid of them but no luck.  Do you know how to get rid of them now?

**Comment by Kiho** [comment]
Bootstrap is referenced in index.html only, you might need to clean up browser cache. but without Bootstrap react-form-builder will not work anyway.

**Comment by RoosterH** [comment]
Eventually got them cleared.  I actually cleared cache before asking the question but then I found out I also need to restart npm to make the line removal take effect.  Thanks very much for the help!
