### ISSUE TITLE
Adding DemoBar

### ISSUE THREAD

**Issue by RoosterH** [Kiho/react-form-builder#87]
Hi Kiho, 
If I understand correctly. DemoBar is for Preview Form.  I copied demobar.js and variables.js to my work directory then followed the code to add
```
import FormBuilder from 'react-form-builder2';
import DemoBar from './demobar';
import * as variables from './variables';

const CustomForm = () => {
	return (
		<React.Fragment>
			<div className="formbuilder-container">
				<FormBuilder.ReactFormBuilder
					url="../../shared/json"
					saveUrl="../../shared/json"
				/>
			</div>
			<DemoBar variables={variables} />
		</React.Fragment>
	);
};

export default CustomForm;
```
Somehow it's complaining a Module not found 
```
./src/event/components/demobar.js
Module not found: Can't resolve './src/form' in '/Users/hung-jenhung/Projects/MySeatTime/FrontEnd/src/event/components'
```
I could keep adding them to my code but that does not look right to me.  What did I do wrong?

**Comment by RoosterH** [comment]
I did an experiment by changing demobar.js to:
```
import store from 'react-form-builder2';
import ReactFormGenerator from 'react-form-builder2';
```
Got an error for store:
![Screen Shot 2020-07-21 at 3 21 46 PM](https://user-images.githubusercontent.com/25292210/88113073-edcd1f80-cb65-11ea-831b-34b78eb9f148.png)

**Comment by RoosterH** [comment]
Another update, with some changes, I am able to see DemoBar now but still issue. 

Changed demobar.js to include:
```
import ReactFormGenerator from 'react-form-builder2';
import store from 'react-form-builder2/lib/stores/store';
```
The component that uses FormBuilder has:
```
import React from 'react';
import FormBuilder from 'react-form-builder2';
import DemoBar from './demobar';
import * as variables from './variables';

import './FormBuilder.css';
import '../../shared/scss/application.scss';

const CustomForm = () => {
	return (
		<React.Fragment>
			<DemoBar variables={variables} />
			<div className="formbuilder-container">
				<FormBuilder.ReactFormBuilder
					url="../../shared/json"
					saveUrl="../../shared/json"
				/>
			</div>
		</React.Fragment>
	);
};

export default CustomForm;
```
"Toolbox" is now blocking the preview button.
![Screen Shot 2020-07-21 at 4 41 14 PM](https://user-images.githubusercontent.com/25292210/88118413-5fab6600-cb72-11ea-8476-c2828f0d85e9.png)

  Also if I hit "Preview Form" button, it crashes at demobar.js where it calls <ReactFormGenerator />
```
	{this.state.previewVisible && (
		<div className={modalClass} role="dialog">
		    <div className="modal-dialog" role="document">
			<div className="modal-content">
				<ReactFormGenerator
					download_path=""
					back_action="/"
					back_name="Back"
					answer_data={answers}
					action_name="Save"
					form_action="/api/form"
					form_method="POST"
					// skip_validations={true}
					// onSubmit={this._onSubmit}
					variables={this.props.variables}
					data={this.state.data}
				/>
```
![Screen Shot 2020-07-21 at 4 48 57 PM](https://user-images.githubusercontent.com/25292210/88118301-1a873400-cb72-11ea-99c7-7c2baaee9ebd.png)

Kiho, I got a few questions here.  Please help answer them.

1. To make it work with my App, I will have to adjust css such as change how to present Editing Modal and change the place of Preview bar and such.  Could you point me out where those css files are?

2.  I looked through the closed questions and in one post you suggested to make a pre-defined form.  My design will be a bit different.  I am planning to offer a customize toolbar. For example, I may have pre-defined "Name" text field and "Choices" as radio button group on ToolBar so users could just DND them without editing them.  How do I do that?

3. For all the customizations that I am planning to do. If I understand correctly, I cannot simply import the component. I will need to copy your source codes to my work area and modify it accordingly.  In that case, what are the codes that I need to copy over and how do I set them up?

Please help when you can.  Thanks very much for the great project!

**Comment by Kiho** [comment]
If you use bootstrap.css in your index.html then following code should work without css issues.
```
import React from 'react';
import ReactDOM from 'react-dom';
import { ReactFormBuilder } from 'react-form-builder2';
import DemoBar from './demobar';
import * as variables from './variables';

import 'react-form-builder2/dist/app.css';

class CustomForm extends React.Component {
  render() {
    return (
      <div>
        <DemoBar variables={variables} />

        <ReactFormBuilder
          url='/api/formdata'
          saveUrl='/api/formdata' />
      </div>
    );
  }
}

export default CustomForm;
```
In demobar you should import ElementStore, it's not recommended to import store from source.
https://github.com/Kiho/react-form-builder/blob/master/examples/demo/demobar.js#L2
You can find all the sass source file here https://github.com/Kiho/react-form-builder/tree/master/scss
So you can copy, modify and  build css with webpack in your project.
You can select items you need and then set to toolbarItems property of ReactFormBuilder.
If you think these are not covering all your requirements then fork the lib and can do whatever you like to do.

**Comment by RoosterH** [comment]
Thanks very much for the quick reply.

Yes, I did put back bootstrap.css in index.html. I think because my page has a navigation bar that messed up FormBuilder layout.  I just change margin-top values in form-builder.scss so the issue is fixed now.

I will check the examples regarding setting toolbaritems proprety.

BTW, pressing "Preview Form" button, still caused crash @ demobar.js that calls ReactFormGenerator.  How do I fix that?

**Comment by Kiho** [comment]
You should DO
```
import { ReactFormGenerator, ElementStore } from 'react-form-builder2';
```
DON'T DO
```
import ReactFormGenerator from 'react-form-builder2';
```

**Comment by RoosterH** [comment]
Kiho, thank you so much.  Preview Form works now.  
Here is what I did:
'''
import {
	ReactFormGenerator,
	ElementStore as store
} from 'react-form-builder2';
'''

**Comment by RoosterH** [comment]
Kiho, a question regarding store.js
In load() and save() functions, what are the if conditions of _onLoad and _onPost doing?   Can you please explain the logic of if statements in both functions to me?
```
load(context, { loadUrl, saveUrl, data }) {
	saveUrl = saveUrl;
	if (_onLoad) {
		_onLoad().then(x => this.setData(context, x));
	} else if (loadUrl) {
		console.log('loadUrl = ', loadUrl);
		get(loadUrl).then(x => {
			if (data && data.length > 0 && x.length === 0) {
				data.forEach(y => x.push(y));
			}
		this.setData(context, x);
	         });
	} else {
		this.setData(context, data);
		}
	}
```
```
save(data) {
	if (_onPost) {
		_onPost({ task_data: data });
	} else if (_saveUrl) {
		post(_saveUrl, { task_data: data });
	}
}
```

**Comment by Kiho** [comment]
If you don't like default form post, you can plugin your own logic.
Check this thread https://github.com/Kiho/react-form-builder/issues/34

**Comment by RoosterH** [comment]
No, it's not I don't like the default.  I only want to understand what _onLoad and _onPost represent for?

**Comment by Kiho** [comment]
https://github.com/Kiho/react-form-builder/blob/master/examples/custom/app.js#L55

**Comment by RoosterH** [comment]
Got it!  Thanks a lot. I love the way that we could customize it.

**Comment by RoosterH** [comment]
Another thing to clarify.  What does requests.js do?  To post and get data from backend?  It uses localhost:3000 not 5000 so I am confused.  If it's for sending data to backend, how to configure the port to 5000?  Sorry, I've never used 'isomorphic-fetch'.  

Also demobar _onSubmit(data) is used to post data to server.  What's the difference between the two?

**Comment by Kiho** [comment]
`_onSubmit` is for form-generator, so it handles users data to different end-point. You can use any port if it's not used by other application. Mongo & Next examples use server-side rendering, so you need isomorphic-fetch.

**Comment by RoosterH** [comment]
Kiho, I was checking server side of codes in mongo example.  I am also new to mongo.  From my understanding, the type of form_task is Array, am I correct?  I thought we will have to defined schema for mongo but I did not see that in your code.  How do you specify the mongo datatype then?  Could you please explain it?  Thanks!

**Comment by RoosterH** [comment]
Kiho, a question regarding the logic in the following function:
```
async function save(db, taskData) {
  const oldData = await loadFormData(db);
  const missing = findRemovedItem(taskData, oldData);

  if (missing.length) {
    missing.forEach((doc) => deleteFormData(db, doc));
  } else {
    taskData.forEach((doc) => saveFormData(db, doc));
  }
}
``` 
Wondering why calling  deleteFormData(db, doc)) inside if (missing.length)?   If missing has a length, doesn't it mean there are new fields that we need to add?  Why deleting them instead?

**Comment by Kiho** [comment]
You could find some info about mongo & next here https://github.com/Kiho/react-form-builder/issues/28
I am not familiar with either next or mongoose schema, so I can't tell much about it.
Every change of form data will hit save function, it can be new, update or delete operation for one of array data.
missing will contain one item if you remove any item from form builder.
Anyway this sample code is not production ready, it just to show you how you can handle the form data.
