### ISSUE TITLE
Winterfell Compatibility?

### ISSUE THREAD

**Issue by rrjanbiah** [Kiho/react-form-builder#9]
I posted something similar in Winterfell https://github.com/andrewhathaway/Winterfell/issues/114

Ideally, Winterfell compliant form generation would be very useful (with conditional logic)

**Comment by Kiho** [comment]
Winterfell looks nice, but I feel that need a lot of work to make it.
Unfortunately, I do not have free time these days.

**Comment by rrjanbiah** [comment]
@Kiho Thank you for your reply

**Comment by rrjanbiah** [comment]
I understand @Kiho doesn't have time.

Just mentioning Mozilla's JSON form schema https://github.com/mozilla-services/react-jsonschema-form/issues/588 in case if anyone is interested
