### ISSUE TITLE
line break inside of form-builer

### ISSUE THREAD

**Issue by RoosterH** [Kiho/react-form-builder#90]
Hi Kiho,

Is there any way to honor line break inside of "Paragraph", "Text Input", or "Multi-line Input"?  Adding list items will start at a new line but "carriage return" is not treated as newline.  

Also can you point me out where the code is to control Editing mode  "Paragraph", "Text Input", and "Multi-line Input" window sizes? 

Thanks so much!

**Comment by Kiho** [comment]
Shift + Enter usually works.

**Comment by RoosterH** [comment]
Yes, Shift + Enter does work but is there any way to make the code to take Enter as a new line?

**Comment by Kiho** [comment]
It's more like upstream issue than this library, and I don't think it's worth for the effort needed.
