### ISSUE TITLE
Can't call setState on a component that is not yet mounted.

### ISSUE THREAD

**Issue by samlovescoding** [Kiho/react-form-builder#92]
I am receiving 'Can't call setState on a component that is not yet mounted.' from Chrome Console when I try to use React Form Builder.

import React from "react";
import Dashboard from "../layouts/Dashboard";
import { ReactFormBuilder } from "react-form-builder2";
import "react-form-builder2/dist/app.css";

function ApplicationBuilder() {
  return (
    `<Dashboard>`
      `<h1>`Application Builder`</h1>`
      `<ReactFormBuilder />`
    `</Dashboard>`
  );
}

export default ApplicationBuilder;
 

Here is the complete error.

`index.js:1 Warning: Can't call setState on a component that is not yet mounted. This is a no-op, but it might indicate a bug in your application. Instead, assign to `this.state` directly or define a `state = {};` class property with the desired state in the Toolbar component.
    in Preview (created by ReactFormBuilder)
    in div (created by ReactFormBuilder)
    in div (created by ReactFormBuilder)
    in div (created by ReactFormBuilder)
    in Unknown (created by ReactFormBuilder)
    in ReactFormBuilder (at ApplicationBuilder.js:11)
    in div (at Dashboard.js:16)
    in div (at Dashboard.js:13)
    in div (at Dashboard.js:12)
    in div (at Dashboard.js:9)
    in Dashboard (at ApplicationBuilder.js:8)
    in ApplicationBuilder (created by Context.Consumer)
    in Route (at App.js:12)
    in Switch (at App.js:10)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:9)
    in App (at src/index.js:8)
    in StrictMode (at src/index.js:7)`

**Comment by Kiho** [comment]
I am not sure where to look at it. I can't see the warning myself.

**Comment by samlovescoding** [comment]
I think this is the warning.

 Can't call setState on a component that is not yet mounted. This is a no-op, but it might indicate a bug in your application. Instead, assign to this.statedirectly or define astate = {}; class property with the desired state in the Toolbar component.

**Comment by RoosterH** [comment]
Please read this that explains what the warning message is and how to fix it.
https://www.debuggr.io/react-update-unmounted-component/#:~:text=Warning%3A%20Can't%20perform%20a,in%20a%20useEffect%20cleanup%20function.

If you are using components instead of class, useEffect can be used.
