### ISSUE TITLE
Layout radio option items by specifying row and column number?

### ISSUE THREAD

**Issue by RoosterH** [Kiho/react-form-builder#95]
Hi Kiho,

I have a long list of items, 20+, for a radio option.  Is there anyway to layout items by specifying row and column number?

**Comment by Kiho** [comment]
No we do not have it, and I don't have time to implement it.
If you want do by yourself then check this out and try to convert it.
https://kiho.github.io/svelte-formgrid/
https://github.com/Kiho/svelte-formgrid/blob/master/src/FormGrid.html

**Comment by RoosterH** [comment]
Will check it. Thanks a lot.
