### ISSUE TITLE
Custom id/names?

### ISSUE THREAD

**Issue by petrisorcibian** [Kiho/react-form-builder#97]
Is there a way to set custom field names, instead of automatically generated ones (like "text_input_0D5DFDED-50BA-4C88-B59D-19AAFEB1CB32") ?

**Comment by Kiho** [comment]
No but you can try something like this at server-side https://github.com/Kiho/react-form-builder/issues/55

**Comment by petrisorcibian** [comment]
Hi @Kiho , thanks for the reply! Already saw and checked that issue, but we want to give full control of the user that designs the form, to also set the custom field name :(

**Comment by petrisorcibian** [comment]
@Kiho this would be the only change, to have support in builder, so field name can be edited:
`label>Field name</label>
            <input type="text" className="form-control" defaultValue={this.props.element.field_name} onBlur={this.updateElement.bind(this)} onChange={this.editElementProp.bind(this, 'field_name', 'value')} />
            <br />`

Added after the "Display Label" field. Do you think it's ok to create a pull request for this one?

**Comment by mike1011** [comment]
you can use [shortId](https://www.npmjs.com/package/shortid)...for example ..in `toolbar.jsx`

```
const shortid = require("shortid");

...something like...
  create(item) {
    const elementOptions = {
      id: shortid.generate(),
      .....
      .....
    };

```

**Comment by petrisorcibian** [comment]
But the functionality that I want is to allow user, when creating the form, to define its own field name. So in the end, when form gets submitted, it will have a friendly name, like here: https://www.dropbox.com/s/w8br30ch9htlgpg/Screenshot%202020-09-22%20at%2015.32.14.png?dl=0

**Comment by Kiho** [comment]
I am not sure this is good move. user can change field name anytime.... it's not looks good to me.

**Comment by petrisorcibian** [comment]
Ok, well :) In this case, I need the user to change the field name, so he can control the output :) If you don't think it's useful on a long term for the component, that's ok :) You decide what's better for it :)
Thank you for your replies and support :)
