### ISSUE TITLE
Cannot have two HTML5 backends at the same time.

### ISSUE THREAD

**Issue by sundarshahi** [Kiho/react-form-builder#98]
I tried to generate the form  by loading the question data like:
``` <ReactFormBuilder toolbarItems={Items} data={questions} show_description /> ```
But getting errors **`Cannot have two HTML5 backends at the same time.`** It seems error of Dnd.

**Can anyone please look into this issue?**

**Comment by mike1011** [comment]
Try this `<ReactFormBuilder toolbarItems={Items}  show_description={true} />`
