### ISSUE TITLE
How could I remove certain option on Edit ? [Help Needed]

### ISSUE THREAD

**Issue by sundarshahi** [Kiho/react-form-builder#99]
**I want to remove/disable certain option that are marked in screenshot** 

 I could able to remove these while building a form like passing a below key:value in Items
` canHaveAlternateForm: false,
    canHavePageBreakBefore: false,
    canPopulateFromApi: false,`

But, If i load the question and then edit,  these options are enabled again

![tools](https://user-images.githubusercontent.com/25520597/93872844-772cd980-fcf0-11ea-990a-27fabecd33b5.png)

**Comment by mike1011** [comment]
if you want to hide the default input elements during `edit`...

check `form-elements-edit.jsx` which has all the toolbar components and then you may render them in the way you want as they all are just simple react class components.

**Comment by Kiho** [comment]
@sundarshahi It might be little bit of work but you can build toolbar items configured as you want like `Dropdown` in code below.
You should aware one thing, toolbox item configuration only affect to new items. 
Any existing item will sustain original configuration if it was saved in the database.
```js
const items = [
  {
    key: 'TextInput',
    canHaveAnswer: true,
    canHaveAlternateForm: false,
    name: 'Text Input',
    label: 'Placeholder Label',
    icon: 'fas fa-font',
    field_name: 'text_input_',
  },
  {
    key: 'Dropdown',
    canHaveAnswer: true,
    canHavePageBreakBefore: false,
    canPopulateFromApi: false,
    canHaveAlternateForm: false,
    name: 'Dropdown',
    icon: 'fa fa-caret-square-o-down',
    label: 'Placeholder Label',
    field_name: 'dropdown_',
    options: [],
  },
  {
    key: 'RadioButtons',
    canHaveOptionValue: false,
    name: 'Multiple Choice',
    icon: 'fas fa-dot-circle',
    label: 'Placeholder Label',
    field_name: 'radiobuttons_',
    options: [],
  },
];

ReactDOM.render(
  <FormBuilder.ReactFormBuilder
    variables={variables}
    toolbarItems={items}
    url={url}
    saveUrl={saveUrl}
  />,
  document.getElementById('form-builder'),
);
```
